### ISSUE TITLE
Forms elements - updates (component webpage)

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1068]
Make updates to this page based on decisions from the Contact us updates (#525)
 https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/form-elements.html

**Comment by sharon-rabang** [comment]
Work on 1068 and [1080](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/1080) at the same time.

**Comment by kkoryaka** [comment]
Check if there any differences with contact. If not close it. @kkoryaka

**Comment by kkoryaka** [comment]
Closing this issue. Elements that are used in contact forms are the same
