### ISSUE TITLE
Form elements - component updates (code)

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1080]
Make components updates based on contact us updates. (https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/525)

These are development updates.

Related to the webpage update: https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/1068

**Comment by sharon-rabang** [comment]
Work on [1068](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/1068) and 1080 at the same time.
