### ISSUE TITLE
Remove Beta feedback banner

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#1102]
- [ ] Please remove feedback banner from top of site. We can continue to collect feedback through the "Partner with us" section.
- [ ] Add [Give feedback](https://airtable.com/shro9V6ry2Cf4mpgG) to footer (Include external link icon)

**REMOVE:**
![Screen Shot 2022-12-21 at 7 40 47 AM](https://user-images.githubusercontent.com/98193284/208944285-d3fd49d2-17b0-491b-9347-8f96143abf06.png)

**ADD TO FOOTER**
![Screen Shot 2022-12-21 at 8 23 07 AM](https://user-images.githubusercontent.com/98193284/208959213-eb34b706-3c1f-4acb-8f9a-4306d213ea4a.png)

KEEP:
![Screen Shot 2022-12-21 at 7 41 24 AM](https://user-images.githubusercontent.com/98193284/208944419-4e17241f-0cd5-4862-a6ea-b8f5d3adb627.png)

**Comment by yesenia-gtz** [comment]
FYI, I added this issue for production release.

@artuoma @extinah @carterm

**Comment by yesenia-gtz** [comment]
@Greg-Watanabe assigning to you

**Comment by extinah** [comment]
@yesenia-gtz Good call. I recommend we also include this at the bottom of the contact us page. that's where people would expect to provide feedback (since we don't have page level feedback). 

We should have page level feedback - can you add that to the backlog?

**Comment by yesenia-gtz** [comment]
@Greg-Watanabe @extinah issue updated to include footer link to feedback form.

**Comment by Greg-Watanabe** [comment]
@extinah 
done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/

**Comment by yesenia-gtz** [comment]
thank you @Greg-Watanabe, looks great! Closing this out.

**Comment by extinah** [comment]
Looks great. :)
