### ISSUE TITLE
Navigation menu bug

### ISSUE THREAD

**Issue by hamiltonryan** [Office-of-Digital-Services/California-State-Web-Template-Website#1123]
We found a strange bug in the navigation menu at the top of the page. When starting in one landing page and switching to another, the navigation responds correctly, but as soon as you go to another page in the side navigation, the menu shows you on a different landing page. When going to a second page, no pages are selected in the navigation menu. 

I tested in edge and chrome and it is happening on both

First landing page (correct):
![image](https://user-images.githubusercontent.com/101579462/209244396-15ac27d2-5746-4612-9625-ed4c96a7c74e.png)
Second landing page(correct):
![image](https://user-images.githubusercontent.com/101579462/209244501-cc9aeeb4-4825-48e7-8fe5-4e063f30fc61.png)
Secondary page 1:
![image](https://user-images.githubusercontent.com/101579462/209244596-268db223-a205-4c8a-bc50-a4ed8350465d.png)
Secondary page 2:
![image](https://user-images.githubusercontent.com/101579462/209244670-35ea8ff9-5790-49b7-9763-63014bfe7d61.png)

@timothyshambra @yesenia-gtz @extinah

**Comment by yesenia-gtz** [comment]
Recorded issue here for context:
https://www.loom.com/share/55d30e673d454c32a752c182fd1e450d

**Comment by timothyshambra** [comment]
- https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/commit/4a562a965cfa1fb2bf02516363d946659923bd88 Updated the page landing fields to match their parent pages 
- Added parent pages to the breadcrumb data file for the what's new page.

**Comment by yesenia-gtz** [comment]
@timothyshambra  this is working as expected on my end now, @hamiltonryan @extinah  how about you?

**Comment by yesenia-gtz** [comment]
Resolved!
