### ISSUE TITLE
Homepage: Design fixes

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#1135]
Post launch homepage design fixes:

- [ ] Header logo text: Change font from Asap Condensed to Public Sans
  - [ ]  State of California: Public Sans, Regular
  - [ ] Web Template: Public Sans, Bold

- [x] Under Partner with us, change the indicator for links (from [#950](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/950))
  - [x] Change font weight from bold to regular
  - [x] Add underline
![image](https://user-images.githubusercontent.com/99768807/209396680-dddcc236-3680-43f4-ad97-83b916197fba.png)

- [x] Under "The State Template is one step closer to the Design System": Add a link to the Design System in this sentence:
The final release (V6) of the State Web Template is part of a planned move to the [Design System](https://designsystem.webstandards.ca.gov/).

- [x] Fill in this gap to continue the dark blue banner to the edge, or replace with [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A441&t=DW3xOHNGnjCjVres-1)'s screenshot
![image](https://user-images.githubusercontent.com/99768807/209398448-20175118-9465-4d3a-a8f3-6f4a382f6b7e.png)

- [x] Mobile view: Fix the Timeline's vertical progress tracker graphics
![image](https://user-images.githubusercontent.com/99768807/209397068-7855827d-bdf5-4520-b782-af245a9718af.png)

- [x] Mobile view: Fix the left-alignment of the Abortion website screenshot and content
![image](https://user-images.githubusercontent.com/99768807/209396869-771c1506-e520-4a8d-b241-128252b6511f.png)

**Comment by sharon-rabang** [comment]
@kkoryaka Here's a list of design fixes for dev to make.

**Comment by kkoryaka** [comment]
@sharon-rabang the fixes are made https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks! 

I'll create a new issue for the header issue I listed above, now that I realized it's not part of the homepage:
- [ ]  Header logo text: Change font from Asap Condensed to Public Sans
  - [ ]  State of California: Public Sans, Regular
  - [ ]  Web Template: Public Sans, Bold

**Comment by sharon-rabang** [comment]
@kkoryaka Please check to see what happened to your progress tracker design fix:
![image](https://user-images.githubusercontent.com/99768807/214133798-96dcce13-ad4c-4394-8543-6a6f7e0c965e.png)

**Comment by sharon-rabang** [comment]
01/26/23: Learned that all of these edits will remain in staging until they go live in production. Will close issue.
