### ISSUE TITLE
Colors: Design fixes

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#1140]
Post launch Color design fixes:

- [ ] [Color](https://template.webstandards.ca.gov/visual-design/color.html) themes cards: Change hover state to be consistent with all other cards' hover states
        - Card: Drop shadow
        - Heading
          Font color: Primary #046B99
          Font hover color: #035376
        - Tool tip text: Card title in heading
![image](https://user-images.githubusercontent.com/99768807/209408810-1dd25da8-1548-42c6-a3a2-a482077e9dbf.png)

**Comment by extinah** [comment]
Ready for dev

**Comment by jon-grant-state-ca-gov** [comment]
Ready for review:
[https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/visual-design/color.html](https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/visual-design/color.html)

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov Looks good to go, thanks!
