### ISSUE TITLE
Veracode issue on contact-us.html

### ISSUE THREAD

**Issue by jon-grant-state-ca-gov** [Office-of-Digital-Services/California-State-Web-Template-Website#1146]
Issue with console.log of unsanitized response; @carterm recommended deleting those two console.logs to resolve the issue.

![veracode-6 1 1-console-error](https://user-images.githubusercontent.com/89486837/210434052-11209d62-7320-49ea-bbb3-8c136086c857.png)

**Comment by carterm** [comment]
This is resolved.  New builds don't show this issue anymore.
