### ISSUE TITLE
Color themes: Fix the circles of color

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#1149]
When you click through the side navigation links, the large circles of color flash a bright color palette, before the selected color theme displays.

**Comment by kkoryaka** [comment]
it's css color scheme that loads second after bootstrap css. Will be fixed in DS.

**Comment by kkoryaka** [comment]
Carter might consider 12 different core css files in the newest core repo

**Comment by kkoryaka** [comment]
Or use transition effects similar to header. @kkoryaka

**Comment by carterm** [comment]
Fixed with https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1349

**Comment by carterm** [comment]
Deployed to dev.  There is much smoother 0.5 second fade that matches the rest of the theme fade.
https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/visual-design/color/?delta

compared to production...
https://template.webstandards.ca.gov/visual-design/color/?delta

**Comment by sharon-rabang** [comment]
@carterm Thanks, this looks good to go! The smoother 0.5 fade is bit easier on the eyes.
