### ISSUE TITLE
Update CDN links for v6!!!!!

### ISSUE THREAD

**Issue by artuoma** [Office-of-Digital-Services/California-State-Web-Template-Website#1150]
The CDN for the new V6 code has not been updated!!!!!!!

**Comment by kkoryaka** [comment]
@artuoma CDN links are updated in production. Or did you see some other CDN links not updated?
![Screen Shot 2023-01-09 at 9 57 29 AM](https://user-images.githubusercontent.com/31669748/211375472-b07432e7-9f59-4448-bc03-8e7e4a1b43cf.png)

**Comment by artuoma** [comment]
The links have been updated, thanks!
