### ISSUE TITLE
Fix site search function

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#1153]
Currently, site search points to the Beta site.

Our team should assume ownership of site manager and site search control.

**Comment by kkoryaka** [comment]
@Leeendahh could you please check our search console and make sure it indexes template.webstandards.ca.gov? Not the beta one

**Comment by carterm** [comment]
I have access to the search products now.  The sitemap file that is generated is pointing to beta.  I've requested index removals for the beta pages, and filtered the main search to only use non-beta pages.  The sitemap file still needs to be fixed.

https://template.webstandards.ca.gov/sitemap.xml

**Comment by carterm** [comment]
Need to deploy a hot fix to production to fix the sitemap.xml file.

**Comment by carterm** [comment]
Sitemap hotfixed and re-added to crawl console.  

https://template.webstandards.ca.gov/sitemap.xml

Check the search in a few days and see if we win.

**Comment by carterm** [comment]
Verified search is working.

**Comment by ashleydraper** [comment]
I concur! Thanks @carterm, looks good to go.

**Comment by ashleydraper** [comment]
@extinah @yesenia-gtz The bug is fixed and this issue is ready to close.
