### ISSUE TITLE
Fix the headings in the examples section on the buttons page (a11y fix)

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1157]
make sure the headings are h3 (not p)
![Screen Shot 2023-01-11 at 3 39 27 PM](https://user-images.githubusercontent.com/31669748/211941344-baa9f0bf-7e46-4662-b3f9-7ce6cddad9fb.png)

**Comment by kkoryaka** [comment]
@pglomboy this is now updated: https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/button.html

**Comment by pglomboy** [comment]
@kkoryaka looks good and done
