### ISSUE TITLE
Fix countdown

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1159]
The countdown component example date is expired. Setup a new date
![Screen Shot 2023-01-11 at 4 05 00 PM](https://user-images.githubusercontent.com/31669748/211944470-add6d7b8-76f6-445d-91ce-56c2c7f8d7fb.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/countdown-timer.html

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
