### ISSUE TITLE
Header: Logo text

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#1171]
Post launch header design fix:
- [x]  Header logo text: Change font from Asap Condensed to Public Sans
  - [x]  State of California: Public Sans, Regular 18/32px
  - [x]  Web Template: Public Sans, Bold 40/50px

**Comment by kkoryaka** [comment]
@jon-grant-state-ca-gov I am assigning ing it to you.

**Comment by extinah** [comment]
@sharon-rabang ready for your review

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov Thanks! Please increase the website title's font size from 24.64px to 28px, to be consistent with the [Design System](https://designsystem.webstandards.ca.gov/). It's actually much larger in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A441&t=3hZdhuWuryPKecR5-1) at 40px, but we should go with the Design System's website title size for consistency at this time.

**Comment by jon-grant-state-ca-gov** [comment]
Thanks @sharon-rabang :)
I updated the title font size to be 1.75rem, which should equate to 28px.

You should be able to see the update on the [Dev site](https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/).

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov The title's font size looks good, thanks! 

Since we're here, can we fix the colors, too?
California: Change from #333333 to #3B3A48 (Gray-900)
Web Template: Change from #333333 to #323A45 (Oceanside-Standout)

**Comment by jon-grant-state-ca-gov** [comment]
@sharon-rabang Those color updates should be showing on the [Dev site](https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/) now :)

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov Looks good to go, thanks!
