### ISSUE TITLE
Implementation steps (feedback improvements)

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1176]
Make updates to the implementation steps page based on user feedback.

Broke this issue out into separate issues. https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/846

Feedback:
> "nunjucks ... eleventy ...?"
> sure hope you plan to explain — whether directly or by linking to a resource — what those are.”
> Need to clarify what these items are for users.

**Comment by ashleydraper** [comment]
We are making improvements to the "**Download and Setup**" content in this next release. To that end, we have separated out the content for Using Eleventy and edited our Implementation Steps. 

Please review all of the content as track changes made it bit too messy to follow.

- [Implementation steps](https://docs.google.com/document/d/1oTuNVoCxmXnX-uDrZAG1ODlRYcvNUnmNQNnRXa2ScG0/edit#)
- [Using Eleventy](https://docs.google.com/document/d/1JxWpKK0mnRx_ndmUpoF1j2LXZ5R7YjoYlT7e6aMuTYY/edit#)

Cc: @hamiltonryan

**Comment by extinah** [comment]
@carterm @artuoma @rkojik  this is ready for our review/feedback
[Implementation steps](https://docs.google.com/document/d/1oTuNVoCxmXnX-uDrZAG1ODlRYcvNUnmNQNnRXa2ScG0/edit#)
[Using Eleventy](https://docs.google.com/document/d/1JxWpKK0mnRx_ndmUpoF1j2LXZ5R7YjoYlT7e6aMuTYY/edit#)

**Comment by hamiltonryan** [comment]
@extinah Can we hold off on the Implementation one. we may have some changes based off of the implementation interviews I'm  doing. The eleventy  one should be good to go though.

**Comment by extinah** [comment]
@carterm @artuoma @rkojik this is ready for your review/feedback
[Implementation steps](https://docs.google.com/document/d/1oTuNVoCxmXnX-uDrZAG1ODlRYcvNUnmNQNnRXa2ScG0/edit#)
[Using Eleventy](https://docs.google.com/document/d/1JxWpKK0mnRx_ndmUpoF1j2LXZ5R7YjoYlT7e6aMuTYY/edit#)

**Comment by kkoryaka** [comment]
@extinah looks good to me. The only thing is that source files paths in the step 4 applied only to eleventy structure template. (Maybe we need to mention it. And make link to using eleventy page.)
![Screen Shot 2023-03-06 at 9 16 26 AM](https://user-images.githubusercontent.com/31669748/223191701-58114414-6fc1-44ee-bc64-5346feed3e95.png)

**Comment by kkoryaka** [comment]
@extinah this is now updated https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/get-started/implementation-steps.html

**Comment by hamiltonryan** [comment]
Looks great, thank you! Moving to Ready for close.
