### ISSUE TITLE
HTML core code with implementation instructions (commented in) user feedback)

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1177]
Received feedback from CalVet to improve the core code.
Make the HTML core code more usable/useful with some guidance commented in.
Per feedback meeting on 1/26/23.

**Comment by extinah** [comment]
Assigned to @carterm  and @artuoma to intake/discuss and decide when to complete (which milestone).

**Comment by extinah** [comment]
@artuoma will set up a meeting with Ryan, Christina, and Carter to come up with a plan. (what to work on, what to consider later on)

**Comment by artuoma** [comment]
@hamiltonryan to setup a meeting

**Comment by hamiltonryan** [comment]
Meeting complete. I wanted to include the Miro board here too, so it doesn't get lost.
[Miro board](https://miro.com/app/board/uXjVPmdlDe8=/)

Next steps, I'll schedule a follow up meeting to finalized the next steps based on the board.

**Comment by extinah** [comment]
PS - this is dev in progress. After dev, it should go into leads review. Thanks!
