### ISSUE TITLE
Web Accessibility Issues (FTB)

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1180]
Fix accessibility issues. These are prioritized in coda: https://coda.io/d/Web-Accessibility_dZDaNvuZCxk/State-Template-V6-A11y-Defects_suBBJ#_luBW1

Here's the original report (attached)

[StateWebTemplate-AccessibilityReview-(ATP).pdf](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/files/10539193/StateWebTemplate-AccessibilityReview-.ATP.pdf)

**Comment by Greg-Watanabe** [comment]
@extinah 
\# 1 - H1 is not required. If you want to add one anyways, I need content.
\# 6 - I need the descriptions that you want to add.

**Comment by extinah** [comment]
@Greg-Watanabe I talked to Sharon. She'll work on these with you. Thanks!

**Comment by extinah** [comment]
Looks great. Thanks so much. Ready for you, Greg. Let us know if you have questions.
