### ISSUE TITLE
Make sure that all tabs on the template's website are accessible

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1201]
Use this accessible tabs https://template.webstandards.ca.gov/components/tabs.html#Sample  on the state web template website displaying components samples and source code samples. 

But add responsiveness to the accessible tabs, so tabs would work as accordion in mobile.

**Comment by extinah** [comment]
Christina: Ask Harvey to test the solution (tab accessibility).

**Comment by extinah** [comment]
@kkoryaka I'm assigning to Pia to check.
@pglomboy Please review for accessibility. Look at the the first comment on what to check. Thanks!

**Comment by kkoryaka** [comment]
@extinah link to test is this: https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/alert.html
it's for Harvey, not Pia.

**Comment by kkoryaka** [comment]
@extinah tabs sample page is now updated https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/tabs.html

**Comment by extinah** [comment]
Can you delete this line?
"Use tabs sparingly."
Then looks good! approved.

@kkoryaka

**Comment by kkoryaka** [comment]
@extinah this is now updated https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/tabs.html

**Comment by extinah** [comment]
This looks good. Thanks @kkoryaka
