### ISSUE TITLE
Website SEO improvements

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1236]
Capturing work Carter is doing. Beta search was highly indexed, so applying redirects. Also working on the 404 page (real one).

@carterm: feel free to edit this if I captured anything wrong. Thanks!

**Comment by carterm** [comment]
Noindex support...

https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1241

**Comment by carterm** [comment]
Fixing 403 folder root error messages...
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1219

**Comment by carterm** [comment]
Beta site, permanent redirect...https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1213

**Comment by carterm** [comment]
Hotfix for incorrect 404 response...https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1207

**Comment by carterm** [comment]
Canonical page selection...https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1206

**Comment by carterm** [comment]
blocking search results in robots...https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1205

**Comment by carterm** [comment]
All soft 404s are resolved.
