### ISSUE TITLE
Icons: Add more key words

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#1238]
Based on usability testing results, the icons need more key words. 

Please include the key words that Sharon added to this Excel doc, after an initial list was already done.
Excel doc: [icon-keywords-220801](https://stateca.sharepoint.com/:x:/s/statewideinnovation/EbWgqPeyY6ZNmS43zIi0BTcBjNqLrAjb52vNH-TuAgX2NA?e=MLUl2V)

**Comment by jon-grant-state-ca-gov** [comment]
I believe the folder containing the font JSON data is [in this Storage Account on Azure](https://portal.azure.com/#@digitalca.onmicrosoft.com/resource/subscriptions/005fa005-b981-47d8-8b39-5b82adf6569c/resourceGroups/PROD-ODI-SHARED/providers/Microsoft.Storage/storageAccounts/prododisharedstore01/storagebrowser). Requesting access from DevOps to hopefully get a better understanding of how to update the JSON file.

**Comment by kkoryaka** [comment]
@sharon-rabang do you have those new words in the new column so devs would know which icon needs to be updated? Or they simply are added to the existing spreadsheet (which means we need to go through every icon and replaces every keyword)?

**Comment by jon-grant-state-ca-gov** [comment]
@kkoryaka I made an updated CSV file with all the old tags plus the new ones Sharon added in the Excel file.

[icon-keywords-220801.csv](https://github.com/Office-of-Digital-Services/California-State-Web-Template-
Website/files/10902130/icon-keywords-220801.csv)

**Comment by jon-grant-state-ca-gov** [comment]
Not sure if the file attachment worked here, but I can send you the CSV I have

**Comment by sharon-rabang** [comment]
> @sharon-rabang do you have those new words in the new column so devs would know which icon needs to be updated? Or they simply are added to the existing spreadsheet (which means we need to go through every icon and replaces every keyword)?

@kkoryaka:
@jon-grant-state-ca-gov reached out last week and made some updates. Not sure if the background info I gave him was of any help. I shared that When I worked in this Excel doc [icon-keywords-220801](https://stateca.sharepoint.com/:x:/s/statewideinnovation/EbWgqPeyY6ZNmS43zIi0BTcBjNqLrAjb52vNH-TuAgX2NA?e=MLUl2V), I just picked up where Courtney left off and stopped working on it when I learned that you had already done most of the work. I don't remember where I started, but to answer your question about where I put new words - I just followed what Courtney did, which was add all the proposed words under the "Key words" column. Since then, I haven't revisited the doc to make any changes or comparisons.

**Comment by jon-grant-state-ca-gov** [comment]
@sharon-rabang The updated tags are working in the [development site.](https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/visual-design/icons.html).

I was also able to improve the content update process, so it should be a bit easier to add names and tags in the future :)

**Comment by jon-grant-state-ca-gov** [comment]
Hi @sharon-rabang, the icons should now include everything from that old excel doc and the updates. I'm seeing those icons you mentioned to me when I search for "social" or "social media" now.

[Link to dev site with updates](https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/visual-design/icons.html)

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov Looks good to go from my end, too. Thanks!
