### ISSUE TITLE
Newsroom pattern

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1251]
Create a newsroom pattern. Goes with List of articles and Article patterns.
https://docs.google.com/document/d/1aPWK7zosSLLlAALkJ5zOiqyVBGYRwLqkisCkD8WLHAw/edit#

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @extinah @kkoryaka 
These related Pattern pages and each of their templates are ready for Leads review. Please let us know if you have questions or if they're ready for dev. Thanks!

Here are the Figma prototypes and Google docs:
**Figma**
- [Patterns](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3339%3A31097&t=EhAkPulHfeAooRYe-1)
  - Add "Page templates" subsection to:
    - All the Pattern pages' side nav as links
    - The bottom of the Patterns landing page with an H2, its description, and cards

 - [#1251](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/1251
 - ) [Newsroom](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3344%3A32115&t=EhAkPulHfeAooRYe-1)
 - [#475](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/475) [List of articles or content](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3339%3A31859&t=EhAkPulHfeAooRYe-1)
- [#476](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/476) [Article](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3339%3A31664&t=EhAkPulHfeAooRYe-1)
	
**Google docs**
- [Newsroom](https://docs.google.com/document/d/1aPWK7zosSLLlAALkJ5zOiqyVBGYRwLqkisCkD8WLHAw/edit)
- [List of articles or content](https://docs.google.com/document/d/1u8jrMFxo0bGM5FfyCvrCOIBMZbt1c91H5ck5gbZhVF0/edit#heading=h.7i9rg0jspn25)
- [Article](https://docs.google.com/document/d/1L9rSVMU7o_oM9WA57RCH3eZaz890s_zmCBl1G4ibkq8/edit)

**Comment by sharon-rabang** [comment]
**03/03/23 UX/Dev meeting notes**

Feasible live template examples:
- Generic header footer
- Open example in a new tab
- Not a part of the template download (just provide source code)
- Option: CAWeb - Possibly make these page template available (make it easy for users)

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @extinah @kkoryaka @carterm Hi! This is a friendly reminder for Leads review of this content. 
Please let us know if it looks ready for dev. Thanks!

**Comment by kkoryaka** [comment]
@sharon-rabang this isn now in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/patterns/newsroom.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some fixes to make:

**On this page:** Change "Sample" to "Landing page with feature banner"
**Fix Sample heading:** Change "Sample" to "Landing page with feature banner"

**Both Examples**
- Live examples (in new tabs): Add underline to last letter 'g'
![image](https://user-images.githubusercontent.com/99768807/226411265-01644d36-f059-415a-b8da-0040ba06802c.png)

- Buttons: 
  - Change from "Live example" to "Live example in new tab" for accessibility,
  - Change outline and text colors from gray to Primary #046B99 for consistency
  - Add arrow for consistency
![image](https://user-images.githubusercontent.com/99768807/226411344-5bae9dbe-f49a-45aa-9d2f-e4345e33b783.png)

**Usage, bullets:** Use Sentence case 
  - News releases
  - Subscription services
  - Press information
  - Trending topics

**Comment by kkoryaka** [comment]
@sharon-rabang page is fixed except underlining. That is how browser renders underlining. It simply skip the letter's defenders.  
![Screen Shot 2023-03-20 at 2 04 15 PM](https://user-images.githubusercontent.com/31669748/226465705-54c6a8cd-de52-41ee-8d74-2af9ce00ccdf.png)

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks for sharing how the browser renders underlines.

Everything looks fixed except for the Sample template image examples - they don't as sharp as the [Article template](https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/patterns/article.html) example. 

Let me know if they were or weren't replaced with the attached .png files above for better quality display. Thanks!
