### ISSUE TITLE
New CDN paths

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1254]
Change state template CDN from https://california.azureedge.net/cdt/statetemplate/6.1.0/css/cagov.core.css
to something like this https://cdn.webstandards.ca.gov/cdt/statetemplate/6.1.0/css/cagov.core.css

Use SHA integrity, can be generated here...
https://www.srihash.org/

We can make CDN refs look like Bootstrap CDN refs.
example...
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">`

**Comment by artuoma** [comment]
Please keep all of the old CDN links up and running - this is moving forward only!

**Comment by carterm** [comment]
We can't "change" but we can start offering a new location.  Like...
`statetemplate.cdt.ca.gov/6.2.0...`

**Comment by carterm** [comment]
Recommend we just keep the old ones running and phase out the use of CDNs going forward.  After our ca.gov outage yesterday, it's just too risky to have website dependencies in two places.

**Comment by gocrusade** [comment]
Cross posted on another CAWEB repo, but the CDN links for font-only CSS doesn't work after 6.0.7.  Files might be missing from intended location. Minified files aren't there either. 

**Works:**
https://california.azureedge.net/cdt/statetemplate/6.0.7/css/cagov.font-only.css

**Doesn't work:** 
https://california.azureedge.net/cdt/statetemplate/6.2.0/css/cagov.font-only.css
https://california.azureedge.net/cdt/statetemplate/6.1.1/css/cagov.font-only.css
https://california.azureedge.net/cdt/statetemplate/6.1.0/css/cagov.font-only.css
https://california.azureedge.net/cdt/statetemplate/6.0.9/css/cagov.font-only.css
https://california.azureedge.net/cdt/statetemplate/6.0.8/css/cagov.font-only.css

![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/39092137/e4228cec-b395-4c4e-896d-6bd5714c8279)

**Comment by carterm** [comment]
> Cross posted on another CAWEB repo, but the CDN links for font-only CSS doesn't work after 6.0.7. Files might be missing from intended location. Minified files aren't there either.
> 
> **Works:** https://california.azureedge.net/cdt/statetemplate/6.0.7/css/cagov.font-only.css
> 
> **Doesn't work:** https://california.azureedge.net/cdt/statetemplate/6.2.0/css/cagov.font-only.css https://california.azureedge.net/cdt/statetemplate/6.1.1/css/cagov.font-only.css https://california.azureedge.net/cdt/statetemplate/6.1.0/css/cagov.font-only.css https://california.azureedge.net/cdt/statetemplate/6.0.9/css/cagov.font-only.css https://california.azureedge.net/cdt/statetemplate/6.0.8/css/cagov.font-only.css
> 
> ![image](https://user-images.githubusercontent.com/39092137/262743767-e4228cec-b395-4c4e-896d-6bd5714c8279.png)

Thanks for noticing.  The font-only CSS files were removed after 6.0.7.  The CDN page has been updated to reflect that.

**Comment by carterm** [comment]
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Development/issues/67

**Comment by kkoryaka** [comment]
There was idea of using code.ca.gov domain to host State Template CDN:
Blocker: needed to apply www on from to domain to avoid cookies inheritance. Blocker could be resolved with implementation of the new GA cookies flags code.
Blocker: need approval form upper management
