### ISSUE TITLE
Change footer links

### ISSUE THREAD

**Issue by artuoma** [Office-of-Digital-Services/California-State-Web-Template-Website#1290]
Let's change the links in the footer under the Resources heading to:

- Content style guide (https://designsystem.webstandards.ca.gov/style/content/)
- Principles (https://designsystem.webstandards.ca.gov/principles/)
- Web accessibility toolkit (https://dor.ca.gov/Home/WebAccessibilityToolkit)

**Comment by artuoma** [comment]
@kkoryaka @extinah If this looks good please move to dev and assign a developer.

**Comment by extinah** [comment]
That looks great to me. I'll move it to ready for dev :)

**Comment by kkoryaka** [comment]
@extinah please review: https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/
