### ISSUE TITLE
Accessibility updates

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1307]
In the footer:

![image](https://user-images.githubusercontent.com/33840424/228031120-9e1c866c-256d-4ba7-afec-46ecb25f31ed.png)

- Add the Accessibility link as the last link under "Web State Template". 
-- Link to: https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/accessibility.html
- Update the current accessibility link to "Website accessibility certification." 
-- Link to https://legacy.template.webstandards.ca.gov/images/WebAccessibilityCert-template.webstandards.ca.gov.pdf

**Comment by kkoryaka** [comment]
@extinah this is done https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/

**Comment by extinah** [comment]
Approved. Thanks!
