### ISSUE TITLE
Add all developed pattern cards

### ISSUE THREAD

**Issue by artuoma** [Office-of-Digital-Services/California-State-Web-Template-Website#1339]
Not all pattern cards available on the /patterns landing page.

**Comment by artuoma** [comment]
@timothyshambra  can you please add this - this is needed before the DWSN this week!
![image](https://user-images.githubusercontent.com/20782462/232520863-2e4b75bf-d7b2-45d0-b21b-eca8c73c3aa1.png)

**Comment by sharon-rabang** [comment]
Figma: [Patterns](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3339%3A31097&t=gLlnP4Gi9JiggsKf-1) landing page
