### ISSUE TITLE
Fix linting JS issues

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1353]
Update all JS files in /src/js/cagov/ file to satisfy linting requirements.

**Comment by kkoryaka** [comment]
@carterm @jon-grant-state-ca-gov @Greg-Watanabe please use this issue to tackle JS linting updates.

**Comment by carterm** [comment]
Many JS files were updated.  All GitHub code scan issues were resolved.
Dev branch is clear of issues.
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/security/code-scanning?query=is%3Aopen+branch%3Adev
