### ISSUE TITLE
favicon.ico needs a size reduction

### ISSUE THREAD

**Issue by carterm** [Office-of-Digital-Services/California-State-Web-Template-Website#1385]
favicon.ico is 223 KB.  It is the largest download on the website.  It is a classic 256x256 32bit ICO/BMP raster file with 8 layers for different sizes, and the largest size is a blurry bear.

The file is used to render a bear in web browser menus.

Multiple layers are only needed when icons contain elements that need to be removed at smaller sizes (like text).  Using the same image multiple times is unnecessary.

Reduce the file to ~24x24 with a single layer.

**Comment by carterm** [comment]
You can find the live file here...
https://template.webstandards.ca.gov/favicon.ico

**Comment by extinah** [comment]
@sharon-rabang Please created a favicon. Thanks!

**Comment by sharon-rabang** [comment]
@carterm Attached is a new png for testing: v6-favicon-24x24.png
Let us know when it's ready for UX review, and if we'll need to make more adjustments. Thanks!
![v6-favicon-24x24](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/99768807/0f4a8f0b-83fb-4f6f-bd64-6fc2631b7623)

**Comment by sharon-rabang** [comment]
@carterm Here's 32x32: 
![v6-favicon-32x32](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/99768807/c9b08eb9-bdaa-46da-ba68-35080e882ef9)

**Comment by carterm** [comment]
Thank you @sharon-rabang.

Here is an update with the new file size.
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1393

**Comment by carterm** [comment]
![Screen Shot 2023-05-15 at 3 41 03 PM](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/6798999/58536487-970b-4a1b-829b-6281ed8cf1f7)
