### ISSUE TITLE
Provide low res image src for homepage images

### ISSUE THREAD

**Issue by carterm** [Office-of-Digital-Services/California-State-Web-Template-Website#1386]
The homepage contains multiple hi-fidelity images that should provide alternate smaller fidelity images for better mobile usability.

This can be accomplished by wrapping large `img` images with a `<picture>` tag that can provide a small mobile optimized version.

```HTML
<picture>
  <source media="(max-width: 799px)" srcset="/images/caaba-example-low.jpg" />
  <img
    class="img-fluid"
    src="/images/caaba-example.jpg"
    width="950"
    style="aspect-ratio: 950 / 698"
    alt="Homepage screenshot of California's Abortion Access Portal website." />
</picture>
```

`caaba-example.jpg` is currently 125Kb, a large download for slow mobile connections.  
https://template.webstandards.ca.gov/images/caaba-example.jpg

**Comment by extinah** [comment]
@sharon-rabang  You created these. Can you work with Carter to get the optimal images for mobile?

@carterm Do you have a good example Sharon can follow?

**Comment by carterm** [comment]
@sharon-rabang is going to take some fresh screenshots based on our discussion.  I will resize them for the appropriate devices.

**Comment by sharon-rabang** [comment]
@carterm Here are the fresh screenshots for testing. 
These images were cropped to their specified file sizes and retouched a bit, so they don't display any stray graphics. Let us know when they're ready for UX review, thanks!
![v6-broadband-523x384](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/99768807/cd76330c-15aa-4b98-8716-8552f538a7f1)
![v6-broadband-358x263](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/99768807/54b3d237-5469-4134-a158-da95232f524e)
![v6-abortion-access-523x384](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/99768807/029552df-28a1-4b7e-af60-613cd9f4cce1)
![v6-abortion-access-358x263](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/99768807/5992740e-3987-4167-bed7-91d1ebd30cd9)

**Comment by carterm** [comment]
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1395

**Comment by carterm** [comment]
Updated release with new screenshots...
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1407
