### ISSUE TITLE
Add grayscale colors from Design System to the color section

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1392]
Add grayscale section from design system to the colors page
<img width="1129" alt="Screenshot 2023-05-15 at 3 11 43 PM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/31669748/8cad52a1-2adf-43ad-afc0-87f31fc52d26">

**Comment by kkoryaka** [comment]
This is now in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/visual-design/color.html

**Comment by extinah** [comment]
@kkoryaka Can you add this intro text under the heading? Otherwise, looks great. Approved. Thank you.
### Grayscale
We've added a grayscale palette that works well with all color themes. This allows you to have more design flexibility.

**Comment by kkoryaka** [comment]
@extinah this is now in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/visual-design/color.html

**Comment by extinah** [comment]
Looks good thank you.
