### ISSUE TITLE
Fix site logo dimensions and make it fluid

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1403]
Remove hardcoded widths from logo image. make its width fluid so a website would be adjustable to any logo width

**Comment by kkoryaka** [comment]
<img width="596" alt="Screenshot 2023-05-18 at 12 06 39 PM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/31669748/21348640-1202-4c9f-898e-efe26dc7b5d1">

**Comment by carterm** [comment]
make sure to specify aspect ratio so it doesn't fail content shifting.

**Comment by kkoryaka** [comment]
@Danny-Guzman we have updated the dimensions styles in Template. Please test it in CAWeb (this might save couple of lines of the custom css for you).
