### ISSUE TITLE
Update Download and setup page to reflect latest decoupled setup

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1475]
Updated Download and setup page content to reflect the HTML repo as the main source for the website

https://template.webstandards.ca.gov/download-and-setup.html

**Comment by kkoryaka** [comment]
@hamiltonryan I have created updated download and setup page in figma please update  and edit https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?type=design&node-id=4272%3A35761&mode=design&t=4Ijb54qKAykGJpEG-1

**Comment by hamiltonryan** [comment]
@kkoryaka Overall it looks great, just some minor fixes. The only question I had was around the "Template Guidance" section. Are we leaving the Using Eleventy page out for now?

**Comment by kkoryaka** [comment]
@hamiltonryan yes, I would recommend to leave it out because now we are focusing on HTML, and our "core" template is no longer tied to  eleventy since we have decoupled it

**Comment by hamiltonryan** [comment]
@kkoryaka Sounds good, in that case it should be good to go. I'll move it over.

**Comment by hamiltonryan** [comment]
@extinah @artuoma @kkoryaka 
Ready for leads review

**Comment by extinah** [comment]
@hamiltonryan this looks good. Thanks!

**Comment by kkoryaka** [comment]
@hamiltonryan please review in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/download-and-setup.html
