### ISSUE TITLE
Update implementation steps to reflect HTML repo as the main source

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1479]
Update implementation steps page https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/get-started/implementation-steps.html and make sure that all the steps taking into account the HTML repo as the main code source

**Comment by kkoryaka** [comment]
@hamiltonryan I have created updated page in figma please review https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?type=design&node-id=4279%3A35857&mode=design&t=4Ijb54qKAykGJpEG-1

**Comment by hamiltonryan** [comment]
@kkoryaka Some minor fixes in the content, but it is all good to go now.

**Comment by extinah** [comment]
@hamiltonryan 
Looks really good to me. A couple of things:

Can this be updated in the google doc? Makes it hard to leave comments.

I see heuristic review in there. This isn't really the time to do it mid implementation (better before or after). But it's ok there for now.
