### ISSUE TITLE
Update using eleventy page

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1480]
update Eleventy page https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/get-started/eleventy.html to reflect latest changes and introducing development repo useful documentation and instructions

Rename "using eleventy" page to "State Web Template development" or "Development environment"

Add link to the updated page page in side navigation under getting started. 

![1](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/31669748/180ab893-4f0f-4f95-aea0-a04ea6256fe9)

**Comment by extinah** [comment]
@kkoryaka Is this still needed?

**Comment by carterm** [comment]
I believe we decided that we don't need to refer to the Dev repo in the template since most users don't ever need to go there.
