### ISSUE TITLE
Dropdown menu pattern href shouldn't be required

### ISSUE THREAD

**Issue by carterm** [Office-of-Digital-Services/California-State-Web-Template-Website#1481]
In the dropdown menu pattern, the `href` for the `first-level-link` is not used and should be replaced with something that doesn't expect the user to use it.

Also, the source code sample text doesn't match the visual example (Sample 1, Sample 2 etc).

https://template.webstandards.ca.gov/structure/site-navigation.html#Dropdown-menu

**Comment by extinah** [comment]
Completed on dev site (by Kon).
