### ISSUE TITLE
Update What's new in V6 page

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1500]
- Update CODE section inside of https://template.webstandards.ca.gov/whats-new.html page to reflect the new decoupled website and development environments

- update releases link to point to this HTML repo releases page https://github.com/Office-of-Digital-Services/California-State-Web-Template-HTML/releases
<img width="928" alt="Screenshot 2023-07-13 at 4 09 33 PM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/31669748/f613d73e-7e83-4619-a1ad-bbcf38815bb6">

**Comment by extinah** [comment]
On the What's new page: 
- Added a bullet to the Code section (4th bullet) that references the decoupled site
- Link updated to the HTML site new releases

Completed. Closing issue.
