### ISSUE TITLE
Starter site: Homepage

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1535]
Ready to develop.
(Greg has already done this).

Figma: https://www.figma.com/file/vCgPY3JxjHO6e838AYGyjo/Starter-Website?type=design&node-id=253%3A18110&mode=design&t=ENGd3STmKB9wfqnD-1

**Comment by extinah** [comment]
@Greg-Watanabe can you add the link to this?

**Comment by Greg-Watanabe** [comment]
There's no staging site, but you can download and view the files directly in your browser

**Comment by extinah** [comment]
- [ ] Unlink these two grid links (or link back to homepage)

![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/90bfb2b9-72e3-4538-863e-65fc78b21a71)

Links these items (defined below the screenshot)
![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/8aec8dc5-5168-47a9-86a5-93c34d3d214a)

- Press release 1: /news/press-release-title1.html
- Press release 2: /news/press-release-title2.html
- News article 1: /news/article-title1.html
- View all: /news/index.html

**Comment by kkoryaka** [comment]
@extinah the newest zip has all these changes.

**Comment by extinah** [comment]
@kkoryaka

**Comment by kkoryaka** [comment]
@extinah check the latest zip

**Comment by extinah** [comment]
Looks good to go. Thanks. Closing.
