### ISSUE TITLE
Starter site: About us

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1538]
Figma: https://www.figma.com/file/vCgPY3JxjHO6e838AYGyjo/Starter-Website?type=design&node-id=262%3A9380&mode=design&t=ENGd3STmKB9wfqnD-1

Ready for dev.

**Comment by extinah** [comment]
@kkoryaka assigning to you to assign out to team

**Comment by kkoryaka** [comment]
@extinah check the newest zip

**Comment by extinah** [comment]
Missing the "learn more about us" section. 
https://www.figma.com/file/vCgPY3JxjHO6e838AYGyjo/Starter-Website?type=design&node-id=262%3A9380&mode=design&t=F88zhAYkxl0IE1D6-1

![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/6101e739-612e-47e4-baf1-d2b904ce15ae)

**Comment by kkoryaka** [comment]
@extinah check the latest zip

**Comment by extinah** [comment]
Looks great. Closing.
