### ISSUE TITLE
Starter website: Top task 1

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1542]
https://www.figma.com/file/vCgPY3JxjHO6e838AYGyjo/Starter-Website?type=design&node-id=116%3A6066&mode=design&t=ENGd3STmKB9wfqnD-1

Greg developed the initial pages.

Christina to work on finalizing.

**Comment by extinah** [comment]
Ready for dev. Needs 4 content/placeholder pages. 

Please provide links Greg. Thanks!

**Comment by Greg-Watanabe** [comment]
pr 59
