### ISSUE TITLE
Starter site:  Contact us

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1543]
https://www.figma.com/file/vCgPY3JxjHO6e838AYGyjo/Starter-Website?type=design&node-id=262%3A8270&mode=design&t=ENGd3STmKB9wfqnD-1

Should've already been developed. @Greg-Watanabe need the staging links. Thanks

**Comment by Greg-Watanabe** [comment]
There's no staging site, but you can download and view the files directly in your browser

**Comment by kkoryaka** [comment]
@extinah check the newest zip

**Comment by extinah** [comment]
Please check  figma - social media section didn't get added in.
https://www.figma.com/file/1qpfecLnEEOQ6c0QmQErF0/State-Template-UI-Kit?type=design&node-id=502%3A12757&mode=design&t=iSkDdENtWVKci1fh-1

![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/5c5e6682-8b18-4de2-bc76-498c044fa55d)

**Comment by Greg-Watanabe** [comment]
added social media icons, PR #75

**Comment by kkoryaka** [comment]
@lakey8085CDT we have one-col layout that is narrower because there is no side nav 
`{%- extends "./base.njk" -%} {%- block content -%}

<div id="main-content" class="main-content">
  <div class="container p-t-md">
    <main class="main-primary" id="main">
      <nav aria-label="You are here" class="breadcrumbs">
        <ol>
          <li>
            <a href="/index.html" title="Home page">Home</a>
          </li>
          <li>{{title | title}}</li>
        </ol>
      </nav>
      <div class="row">
        <div class="col-md-10 p-b-lg mx-auto">{{ content | safe }}</div>
      </div>
    </main>
  </div>
</div>
{%- endblock -%}

<img width="395" alt="Screenshot 2023-09-11 at 4 16 33 PM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/31669748/f2ccd35e-9c6c-4ec8-b834-cc61b78ea3ee">
`

**Comment by kkoryaka** [comment]
@extinah check the latest zip

**Comment by extinah** [comment]
@kkoryaka 

Small thing - can you make the text line up with the heading (see lakey's screenshot).

It's either that or we update the side nav for the about pages and add in contact us, then add in the left nav to this page. I'm ok either way. If we go with the second option, I'd have to update the UI kit (small fix)

**Comment by kkoryaka** [comment]
@extinah I chose to align with the heading 
<img width="1234" alt="Screenshot 2023-10-03 at 8 57 21 AM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/31669748/de1f4277-c810-44c9-9f53-23037e8f7ab9">
