### ISSUE TITLE
Starter site: Legal pages (shell)

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1544]
https://www.figma.com/file/vCgPY3JxjHO6e838AYGyjo/Starter-Website?type=design&node-id=262%3A10138&mode=design&t=ENGd3STmKB9wfqnD-1

**Comment by kkoryaka** [comment]
@extinah check the newest zip

**Comment by extinah** [comment]
Accessibility page
Use "email@department.ca.gov" as the email address. Remove the extra space at the end of the link (Webmaster .).

![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/cdd2190d-04fb-4950-beaf-c98ab27a7654)

**Comment by extinah** [comment]
Privacy policy
First screenshot:
- Change the effective date to MM/DD/YYYY
- Update the first sentence to make it generic: The California Name of Department, which runs name.ca.gov, 
- Change all "Department of Technology" to "Name of Department"

Second screenshot
- Update email address to email@department.ca.gov
- Change phone number to (999) 999-9999
- Change address info: Name of Department, 1234 Any Street, Sacramento, CA 95814
- Delete the prior privacy policy

![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/4a6a0015-3576-4040-9a95-a6d62fc29d5e)
![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/2e96b846-3cec-4b7f-9510-58865db53d1a)

**Comment by extinah** [comment]
**### Conditions of use**

- Change State of California's to: Name of Department's
- Change ALL instances of web sit to website
- Change web portal to website
![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/cfcd486f-f7c1-4369-b138-4cd5dbfd189d)

**Comment by extinah** [comment]
**Website certification**

This does not match the figma

Figma (first)

Website screenshot (second)

![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/1d5d38e8-a85b-442b-9927-8b6148afbe87)


![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/33f64d4d-0096-4ecc-9a1e-eff4cd86cdad)

**Comment by kkoryaka** [comment]
@extinah check the latest zip

**Comment by extinah** [comment]
Looks good. Thank you. Closing.
