### ISSUE TITLE
Starter site: Our organization

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1552]
https://www.figma.com/file/vCgPY3JxjHO6e838AYGyjo/Starter-Website?type=design&node-id=440%3A10455&mode=design&t=t7b4otTSPKLchyJa-1

Ready for dev.

**Comment by kkoryaka** [comment]
@extinah check the newest zip

**Comment by extinah** [comment]
Will do thanks @kkoryaka

**Comment by lakey8085CDT** [comment]
@kkoryaka 

All links are working. The only thing I'm noticing is the 'side-nav' may not be nested properly. Under the 'About us' nav, the three list items are part of the About us section and should have an indent to indicate they're part of a whole. Meaning it should be a nested <ul> within the main 'side-nav.' The side-nav CSS would need to have more specificity to account for this. Also have we thought about a global include for the 'side-nav?'

**Comment by lakey8085CDT** [comment]
![side-nav-review](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/142357975/3617cf8d-bc82-4c0e-9eea-f0f58d37ba62)

not sure if this image will post...let's see...it's of the nav...

**Comment by extinah** [comment]
Approved. Thanks!
