### ISSUE TITLE
Starter site: News pages

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1553]
There are a lot of news page.

https://www.figma.com/file/vCgPY3JxjHO6e838AYGyjo/Starter-Website?type=design&node-id=262%3A9742&mode=design&t=t7b4otTSPKLchyJa-1

They are ready for dev BUT i haven't updated the breadcrumbs or side nav yet.

**Comment by extinah** [comment]
NEWSROOM HOMEPAGE
![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/0c2df1f4-34a2-496f-ae80-ca567f8b1092)


In the featured section:
Press Release Title 1 should link to: /news/press-release-title1.html
Press Release Title 2 should link to: /news/press-release-title2.html


Latest news section:
News Article Title 2 should link to: /article-title2.html
News Article title 3 should link to: /article-title3.html
NOTE: This pages don't seem to exist

**Comment by kkoryaka** [comment]
@extinah check the newest zip

**Comment by extinah** [comment]
@kkoryaka 

Folder structure-wise, put the news folder in the about folder.
![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/8290c4a3-2abc-4b2f-9376-0b6eb7c499b6)

**Comment by extinah** [comment]
News Articles page - /news/articles.html

- [ ] Update this link to /news/article-title2.html
![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/77c58a07-ebd7-4c11-9d43-3e6be54bde40)

- [ ] Pagination looks off (on all pages with pagination)
![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/a63809b1-a6cd-4ed8-99bd-0f3c5a99bab5)

**Comment by extinah** [comment]
Subscription services - /news/subscription-services.html

I didn't update the content. Here's the updated design. Sorry about that.

https://www.figma.com/file/1qpfecLnEEOQ6c0QmQErF0/State-Template-UI-Kit?type=design&node-id=658%3A5616&mode=design&t=jZO63aHjuvTjbWBp-1

![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/64d5218a-f517-4b9f-bd83-1449a94c5613)

**Comment by kkoryaka** [comment]
@extinah check the latest zip

**Comment by extinah** [comment]
Looks great. Ready to close.
