### ISSUE TITLE
Create page that shows components' life cycle (history page)

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1554]
Create components history page where user would see component evolution from v5.5 to current. 
Also, show deprecated components and components or  css classes that will be no longer supported.

**Comment by lakey8085CDT** [comment]
Started component audit from v5.5 versus v6 in Excel.

**Comment by lakey8085CDT** [comment]
Cataloging of pages 30% complete.

**Comment by kkoryaka** [comment]
@extinah @lakey8085CDT I have created two version. One is where we list all anchors to  the legacy components
https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/legacy-components.html

Second is using searchable table:
https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/legacy-components-table.html

Please review, make your edits.
