### ISSUE TITLE
Starter site: Header/footer

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1557]

**Comment by extinah** [comment]
Footer needs updating.

**Footer in zip file:**
![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/704b8420-cafb-4bbf-ac11-d3410231faa2)

**Footer in figma:**
![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/406562ae-5cd2-495b-b83e-6324e0de312c)

figma link: https://www.figma.com/file/vCgPY3JxjHO6e838AYGyjo/Starter-Website?type=design&node-id=60%3A4287&mode=design&t=0k2zp2IaDudQ1dth-1

**Comment by kkoryaka** [comment]
@extinah check the newest zip

**Comment by extinah** [comment]
Approved.
