### ISSUE TITLE
Fix logo in the sample demo page

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1563]
<img width="500" alt="Screenshot 2023-08-23 at 2 35 43 PM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/31669748/45c4dafe-22bb-4808-a5f6-118fcdd46501">

https://template.webstandards.ca.gov/patterns/list-of-articles-or-content-sample.html

**Comment by extinah** [comment]
Fixed in starter site.
