### ISSUE TITLE
Create page for starter site / ui kit

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1571]
Within getting started

**Comment by extinah** [comment]
@kkoryaka 
- [ ] Location: Visual design drop-down menu (last item)
- [ ] Create page based on this [mock-up in Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?type=design&node-id=4738%3A993&mode=design&t=JhjF7l4X8gU0MDrs-1)

Here's a screenshot
![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/fce979e9-0110-418a-b0cc-8b9d9225c53f)

**Comment by kkoryaka** [comment]
@extinah ui kip page is now in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/visual-design/ui-kit.html

**Comment by extinah** [comment]
Hi there - here are some fixes


- [ ] 1. Omit the "On this page"
- [ ] 2. Put the first section "Get the UI kit" in a card
- [ ] 3. Delete this text "You can also download these icons) from the bottom of the get started section.
- [ ] 4. Code error at the bottom (ellipses)


1 and 2: ![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/d8bdbd88-af26-4990-ad05-8c48043eaae7)
3: 
![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/5b8a5b98-5942-49ce-bf1c-26fc567c103c)

4: ![image](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/33840424/d1139294-9374-4cd6-838e-80aa1b51106c)

**Comment by kkoryaka** [comment]
@extinah this is now updated in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/visual-design/ui-kit.html

**Comment by extinah** [comment]
This looks GREAT. Ready for production. Thanks so much. I might have @artkho and @rkojik review this and the kit one last time. I'll include you on the communication.
