### ISSUE TITLE
Content update to website: Icons

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1577]
Add in a line and link to where people can download icons. Add this after the Do /Don't content.

You can also download these icons. 

1. Go the [California State Web Template Website Git Repo](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/tree/master).
2. Select Code > Download ZIP.
3. In the file, go to src folder > images folder > icons folder
All the icons are in the icons folder.

**Comment by kkoryaka** [comment]
@extinah this is now in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/visual-design/icons.html

**Comment by extinah** [comment]
@kkoryaka Looks good. Ready for production. Thank you!
