### ISSUE TITLE
Review content UI Kit: Colors

### ISSUE THREAD

**Issue by lakey8085CDT** [Office-of-Digital-Services/California-State-Web-Template-Website#1585]
Konstantine is making changes and I'll review upon notification.

**Comment by lakey8085CDT** [comment]
Link for reference. https://template.webstandards.ca.gov/visual-design/color.html

**Comment by lakey8085CDT** [comment]
@kkoryaka, No accessibility issues. Provided component and content review. I've attached a Word doc with my suggestions. Feel free to contact me with any questions. 
[colors.docx](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/files/12785724/colors.docx)

**Comment by kkoryaka** [comment]
@lakey8085CDT your edits are not in dev. Please review https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/visual-design/color.html
