### ISSUE TITLE
Add CDN and NPM pages links under Download and setup side navigation

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1603]
<img width="1356" alt="Screenshot 2023-10-06 at 2 12 13 PM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/31669748/4c456f2b-7769-46c2-87f5-705c2daaa1e5">

**Comment by kkoryaka** [comment]
@extinah this is now in dev https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/1603

**Comment by extinah** [comment]
Looks good thank you.
