### ISSUE TITLE
make static page  NPM 

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#1614]
Create a new NPM package page under get started (add side nav sinks to that page)

**Comment by kkoryaka** [comment]
@lakey8085CDT i have create new NPM package page in dev. Please review and edit the content if nessesary.
https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/get-started/npm.html

**Comment by lakey8085CDT** [comment]
@kkoryaka, provided accessibility code (Axe dev tool) and UX content review. I've attached a Word doc of my review.

[ https://stateca-my.sharepoint.com/:w:/r/personal/michael_lakey_state_ca_gov/Documents/Desktop/StateTemplate-UI-Kit/content-reviews/NPM-package-review.docx?d=wdf8f776b75e84fbb9396be3c0d105f17&csf=1&web=1&e=udOcae](url)
