### ISSUE TITLE
Homepage content edits

### ISSUE THREAD

**Issue by nguyenalicea** [Office-of-Digital-Services/California-State-Web-Template-Website#1636]
Review suggested content edits in the [internal Google doc](https://docs.google.com/document/d/15soATRZaSWVv5Wl2wzILjay-yVNHbf9Gozl5GwWzJfc/edit)

Workflow: Leads to review, suggest edits. Approval by management (K/G).

**Comment by extinah** [comment]
Made my suggested edits.

**Comment by hamiltonryan** [comment]
I made comments and suggestions too.
