### ISSUE TITLE
About page content edits

### ISSUE THREAD

**Issue by nguyenalicea** [Office-of-Digital-Services/California-State-Web-Template-Website#1637]
Review suggested content edits in the [internal Google doc](https://docs.google.com/document/d/1kOPYf6tPsI4UiVrfs08le4VieifLBabGIshsEbe_K7I/edit)

Workflow: Leads to review, suggest edits. Approval by management (K/G).

**Comment by extinah** [comment]
Made my suggested edits. The changes brought the sentence up to a grade 13. My edits reduced it to grade 7 (we aim for 8th or less).

**Comment by nguyenalicea** [comment]
Thank you, Christina!

**Comment by hamiltonryan** [comment]
I made comments and suggestions.

**Comment by nguyenalicea** [comment]
Thank you, Ryan!
