### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by hdhillon88** [Office-of-Digital-Services/California-State-Web-Template-Website#1639]
Once you tab into the page content you cant tab back into the mobile menu it skips it with keyboard

**Comment by kkoryaka** [comment]
@hdhillon88 that for the creating the issue for this. it should be fixed with [this](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Development/pull/96) PR which will go out next release.

**Comment by kkoryaka** [comment]
@hdhillon88 we just released [v6.3.1 release](https://github.com/Office-of-Digital-Services/California-State-Web-Template-HTML/releases) that should have addressed this issue.
