### ISSUE TITLE
Double arrows on links to external websites

### ISSUE THREAD

**Issue by tallchineseguy** [Office-of-Digital-Services/California-State-Web-Template-Website#1640]
Need help transitioning to latest version of Template in MVC. When we integrate the latest version, we get double arrows next to any link pointing to an external website. Not sure how to fix that on our end.
![double link arrows](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/146849506/b143f515-cb8d-4fc9-8d6a-a437c5e79cba)

**Comment by kkoryaka** [comment]
Delete hardcoded icons. Those icons are now generated automatically for all external links.
