### ISSUE TITLE
Review "Content Patterns" updated content

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#218]
Review and provide suggested edits for the Page Templates page updated content: (in beta staging)
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/page-templates.html

**Comment by ashleydraper** [comment]
@artuoma @extinah The **[patterns landing page](https://docs.google.com/document/d/1dSaxoIHsuJMXOrFMiVnEQgIrJfAyWmkcPDikllgrH78/edit#)** is ready for review. And you can view it in context in **[Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=45%3A7548)**.

**Comment by extinah** [comment]
@ashleydraper This looks great. Nicely done. No changes - approved. 
@artuoma Poke!

**Comment by kkoryaka** [comment]
@ashleydraper please review https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns.html

**Comment by yesenia-gtz** [comment]
@kkoryaka I noticed the staging layout is not matching the figma layout. Is this still a work in progress? [Figma link here](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A1061)

Side by side below
![Screen Shot 2022-10-14 at 3 41 11 PM](https://user-images.githubusercontent.com/98193284/195954122-9a5ec629-2faa-4753-aab6-a151a9559860.png)

CC:@artuoma

**Comment by kkoryaka** [comment]
@yesenia-gtz you probably clicked to soon before it deployed

**Comment by yesenia-gtz** [comment]
@kkoryaka thanks for the heads up! Just did a hard refresh and I am seeing a few content differences, but looks like content on staging matched [google staging doc](https://docs.google.com/document/d/1dSaxoIHsuJMXOrFMiVnEQgIrJfAyWmkcPDikllgrH78/edit#)

![Screen Shot 2022-10-14 at 5 43 30 PM](https://user-images.githubusercontent.com/98193284/195961271-6accc7b6-64f4-4986-9f6c-fa1f897a4826.png)

ALL GOOD here , thank you

@ashleydraper you are up :)

**Comment by ashleydraper** [comment]
![image](https://user-images.githubusercontent.com/62437425/196787086-9f73c979-3fd0-4171-b871-3f920c746ecc.png)

**Comment by kkoryaka** [comment]
@ashleydraper this one is updated

**Comment by ashleydraper** [comment]
Looks great. Ready to close.
