### ISSUE TITLE
Update side navigation (template site)

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#223]
Update State Web Template side navigation style to resemble Design System side navigation

![Screen Shot 2022-03-25 at 9 09 48 AM](https://user-images.githubusercontent.com/31669748/160158678-5dd88048-abee-4a9e-b45c-e787d83b01a9.png)

Update side navigation styles and architecture based on figma examples: 
![Screen Shot 2022-06-10 at 11 18 32 AM](https://user-images.githubusercontent.com/31669748/173126954-fd6b8e71-6354-40d0-ae27-cb278378874e.png)

![Screen Shot 2022-06-10 at 11 19 56 AM](https://user-images.githubusercontent.com/31669748/173127100-8a478ebf-35c1-4b45-b6df-cdedc6507ef3.png)

**Comment by kkoryaka** [comment]
Added page navigation sample page in beta staging https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/page-navigation.html

**Comment by kkoryaka** [comment]
@Courtney-Chittock Updated side nav styles and added sticky property to it. Please review

**Comment by Courtney-Chittock** [comment]
@kkoryaka please see feedback in items 18-25 on the Google sheet [Developer Feedback tab](https://docs.google.com/spreadsheets/d/11j0r3flPCG5wvpa5flClG8x5-e0ZxROl-HQoaTkSsNM/edit#gid=156389168).

**Comment by kkoryaka** [comment]
@Courtney-Chittock it looks like that overflow bug is now fixed thanks to @xjensen. Please review.

**Comment by Courtney-Chittock** [comment]
@kkoryaka this is brilliant! Thank you @xjensen. That was a concerning bug.

Not sure if this is a new development, or if it just happened at some point along the way, but the scroll bar has come untethered from the main content area at the bottom. Please see [this video](https://stateca.sharepoint.com/:v:/r/sites/statewideinnovation/Shared%20Documents/Design%20Assets/Courtney/Web%20Standards/Beta%20Site%20Redesign/review-images/[side-nav-scroll-bar2.mp4](https://stateca.sharepoint.com/:v:/r/sites/statewideinnovation/Shared%20Documents/Design%20Assets/Courtney/Web%20Standards/Beta%20Site%20Redesign/review-images/side-nav-scroll-bar2.mp4?csf=1&web=1&e=liUmth)?csf=1&web=1&e=liUmth) for a demo of the behavior.

**Comment by kkoryaka** [comment]
@Courtney-Chittock  link doesn't work. Just give me the pages links where it happens and I will take care of it

**Comment by Courtney-Chittock** [comment]
@kkoryaka oops, I fixed the link. This is on any page with a multi-level side nav (Structure, Components, Patterns). Thanks!

**Comment by kkoryaka** [comment]
I see, @Courtney-Chittock we have to live with those issues because of our page structure and side navigation placement in it there will be some scrolling gaps. Side navigation height calculation happens on page load when sticky position is not in effect yet. To get to that sticky position user needs to scroll through the header, and breadcrumb area. That breadcrumb area creates some gap at the beginning but then that gap disappears once user scrolls to the bottom. In design system we will try to make side nav independent of other page structure elements.

**Comment by yesenia-gtz** [comment]
@Courtney-Chittock needs review

**Comment by kkoryaka** [comment]
@sharon-rabang @extinah @ashleydraper if you see any issues with side navigation (content, naming, or styles) please don't hesitate to bring it up here

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! 
- Patterns side nav update:
- - Hero banner page name: Will let you know if we'll need to update this name when it gets combined with 'Feature card'.
- - Figure with Captions: Please make 'captions' lower case for sentence case consistency.
- All Patterns page headings: Will review and mark up for sentence case consistency.
- Card grid layout: Thanks for setting this page up! Will add the link to [#479](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/479) Blurbs improvements.

**Comment by extinah** [comment]
Related to 587
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/587

**Comment by sharon-rabang** [comment]
- Based on @hamiltonryan's research, explorations, and today's working meetings, we have a proposed design solution for the side nav and how it handles page anchor links. 
- Will discuss at tomorrow's 11/08/22 design shareout meeting for review and feedback.
![image](https://user-images.githubusercontent.com/99768807/200432452-7e7a1bf9-2f88-4a24-9082-3a4de10a096e.png)

**Comment by sharon-rabang** [comment]
Here's the previous exploration from Sharon and Christina's research last week:
![image](https://user-images.githubusercontent.com/99768807/200434072-734ed5bc-55dd-49e7-81e9-315c55362329.png)

**Comment by sharon-rabang** [comment]
11.08.22 Design shareout meeting notes:
- The proposed design can be applied to this state template site and enhanced in the Design System
- Include guidelines for the proposed design on this state template site's **Structural elements: Side navigation** page
- One of the enhancements for the Design System: Decouple the anchor links from the side nav
- Will have another meeting to continue this discussion

**Comment by sharon-rabang** [comment]
11.08.22 Design Team feedback:
- The en dashes design direction are a better fix at this time
- Gray bar design direction:
-- Users would have to restructure their pages
-- Users would need to learn how it works as they navigate our pages
-- Tim can explore this solution to see what he finds

**Comment by yesenia-gtz** [comment]
**Adding feedback from beta survey for team awareness:**

> The "current location" in the sidebar doesn't update as I scrolled down the page. Have seen this done elsewhere, and it seemed really useful (when combined with the always-visible sidebar). See [Google's page about their Cloud Translation](https://cloud.google.com/translate/) service for an example.

![No current location indicator](https://user-images.githubusercontent.com/98193284/202508186-6eaf795f-2b0a-44af-982a-79f69f05887d.png)

**Comment by sharon-rabang** [comment]
11/17-11/18: UX Team shareout of proposed "Side nav" and "On this page" designs
- Reviewed and approved: 
-- Both proposed designs
-- Prototypes for [#827](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/827) Usability testing and as a live example for the [#587] Side nav component multi-level list
--- Will create new GitHub issue to develop this in another environment
- Content updates about design and usage will be made for
-- [#587](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/587) "Side nav component"
-- [#831 ](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/831)"On this page" component

**Comment by sharon-rabang** [comment]
@hamiltonryan Updating all Figma pages with the "Side nav" design and "On this page" design
@kkoryaka Desktop version ready for dev

**Comment by sharon-rabang** [comment]
Related to [#853](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/853) Side nav (template site): Mobile view design

**Comment by yesenia-gtz** [comment]
Figma: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=72%3A4943&t=fV0B4Fskbr7iPjEQ-0

@rkojik can you review design, content is still pending

**Comment by extinah** [comment]
Approval meeting decisions:
- Approved to start developing this component and applying to the site. (@kkoryaka)
- DO NOT START on the component page yet. We are still finalizing the content for the multi list example (and possibly a gif).

**Comment by kkoryaka** [comment]
@sharon-rabang I have updated the side navigation throughout the site. Please review

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Our UX review and feedback are in progress.

**Comment by sharon-rabang** [comment]
@kkoryaka The side nav looks great! Here are some design fixes to make:
- Landing pages:  Include the light gray bar with the vertical yellow bar to indicate the active page
![image](https://user-images.githubusercontent.com/99768807/206574906-2e93b3a2-b7d1-460a-8fd7-e131212594d5.png)
- About page: Remove the side nav
![image](https://user-images.githubusercontent.com/99768807/206574955-80d999e9-7dab-4ec0-8cfc-41d33b8f23f6.png)
- Utility CSS classes page: Update side nav to match this Figma screenshot. (The side nav should not display the H2s on the Utility CSS classes page.)
![image](https://user-images.githubusercontent.com/99768807/206575218-1a6045e4-687e-44b9-b9d0-11dbbfcaa271.png)
- Visual design pages: 
-- Top level nav, “Visual design” drop down: Make active pages display in bold font (Like the [Design System](https://designsystem.webstandards.ca.gov/))
![image](https://user-images.githubusercontent.com/99768807/206578033-65323cff-c70c-432a-844f-73ed8969e3b6.png)
-- Colors page: Update side nav to match this Figma screenshot that lists the Color themes
-- Icons and Typography pages: 
--- Add “Visual design” in Public Sans, Bold on top
--- Change “Visual design” font color to Gray-600 #72717C
--- Left-align Colors, Icons, and Typography with “Visual design”
![image](https://user-images.githubusercontent.com/99768807/206577829-44c0b8dc-56f6-4562-b02b-23bad2ac48b4.png)

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks for the quick meeting about fixing the side navs on the Visual design pages for this release.
12.09.22 Meeting notes:
- The Visual design pages do not need “Visual design” in Public Sans, Bold on top of the side nav, without a Visual design landing page in this release.
- Create a Visual design landing page in the next release: [#916 Visual design landing page](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/916)
- The side navs on the Figma [Visual design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A1057&t=EP7PTQGcVYldMTFG-1) pages have been updated:
![image](https://user-images.githubusercontent.com/99768807/206767988-4d30b1e0-b279-404b-92b5-2e78d41177b2.png)
![image](https://user-images.githubusercontent.com/99768807/206768015-b7098225-251d-48c3-aed0-067cc8ee3062.png)
![image](https://user-images.githubusercontent.com/99768807/206768105-6109b84b-f796-47b0-b1de-437ee560707d.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated except the main navigation item. For that you. need create separate ticket since it's not related to side navigation

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks! Will create a separate ticket for the top level navigation issue.
