### ISSUE TITLE
v5.6.2 CSS has absolute /fonts/foo.ext URL's for some fonts

### ISSUE THREAD

**Issue by eric-miller-cdfw** [Office-of-Digital-Services/California-State-Web-Template-Website#231]
In the version 5.6.2 state template release, if folders are not located at the root of the website, several fonts fail to load because they are referenced in the CSS files using the absolute path /fonts/foo.ext instead of the relative path ../fonts/foo.ext.

**Comment by eric-miller-cdfw** [comment]
#234 - Pull request to fix the font path issue.

**Comment by yesenia-gtz** [comment]
This is resolved in Beta release.
