### ISSUE TITLE
Update main navigation based on latest content architecture revision

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#279]
Update main navigation based on latest figma wireframe: 
https://www.figma.com/file/MqZcuRodjzKf03BTnQw2KS/Beta-Redesign-Sandbox

Make it single level, but keep old flex menu in the examples.
 
![Screen Shot 2022-05-06 at 11 40 38 AM](https://user-images.githubusercontent.com/31669748/167198848-4156359a-0b36-4101-89eb-bfcc9abb02a0.png)

**Comment by kkoryaka** [comment]
@Courtney-Chittock site navigation is now updated accordion to the figma. Please review in staging: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/

**Comment by Courtney-Chittock** [comment]
@kkoryaka the breadcrumbs on "Template updates" and "Patterns" do not match the updated page titles. Also the H1 on "Patterns" does not match.

**Comment by yesenia-gtz** [comment]
opening up again, thanks for the catch @Courtney-Chittock !

**Comment by kkoryaka** [comment]
@Courtney-Chittock I fixed breadcrumbs and h1. Please review.

**Comment by Courtney-Chittock** [comment]
@kkoryaka I did a refresh but am not seeing a fix on the staging site.

**Comment by yesenia-gtz** [comment]
@extinah can you review this for IA accuracy? See Courtney's note above 

https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/

**Comment by kkoryaka** [comment]
@ashleydraper please take a look at the order and assign it to devs when you are done.

**Comment by ashleydraper** [comment]
@kkoryaka @timothyshambra I think I'll be able to review this better once the homepage is developed. Where are we on that?

**Comment by kkoryaka** [comment]
@yesenia-gtz please review the main nav

**Comment by yesenia-gtz** [comment]
@kkoryaka reviewed and looks goof to me. is this ready to close out?

**Comment by kkoryaka** [comment]
Sure. @yesenia-gtz please do.
