### ISSUE TITLE
Create new Visual Design landing page that will combine content from Typography, Color Schemes, and Icons pages

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#280]
Combine content from typography, color schemes and icons pages into one Visual Design page. For icons section make some intro text and the link to separate icons page. 

Add "On this page" page navigation with anchors to Typography, Color Schemes and Icons sections

**Comment by kkoryaka** [comment]
@ashleydraper @Courtney-Chittock I have created new visual design landing page in staging. Please review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design.html

**Comment by Courtney-Chittock** [comment]
Initial [Figma mockup](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=165%3A6596) is completed and reviewed by larger project team. Assigning to Ashley for content before moving to development.

**Comment by Courtney-Chittock** [comment]
Here is the link to the [Visual design content](https://docs.google.com/document/d/1uWiFyaWes1CAttKaMhyIyi54SMPswfGc2z7N3r2F7hM/edit). I completed my review.

**Comment by Courtney-Chittock** [comment]
@artuoma @extinah it's all you. I suggest a workshop for this page so we can massage and finalize text more quickly.

**Comment by sharon-rabang** [comment]
09.28.22: OK to separate three Visual Design sections onto different pages; use simple dropdown menu listed alphabetically.

**Comment by ashleydraper** [comment]
@sharon-rabang Is this ready for dev, or will you need to mockup the 3 pages first?

**Comment by sharon-rabang** [comment]
@ashleydraper I set up the 3 separate pages in Figma, but we need to discuss if the Visual design content or description is still needed and where it should go.

**Comment by ashleydraper** [comment]
There are now 3 separate google docs for these pages.

- [Colors](https://docs.google.com/document/d/1E3LB0hMUZF-DTVx8AsPmvVvGzU7cDeffrJeeDi9pJps/edit#)
- [Icons](https://docs.google.com/document/d/1LbgcENsfG_AgQ2sNEjJCtHTl4JxCoBe6hrsyXIAayIQ/edit#heading=h.5st7skvtgqwk)
- [Typography](https://docs.google.com/document/d/11oaHBWMaPXzwPCxEUAB65aSLps3nmyLzzE4tvmimSU0/edit#heading=h.ys22q3my1tv0)

**Comment by ashleydraper** [comment]
There are some outstanding content questions on the colors and icons pages. Scheduling a call (10/5) to clear these up, then ready for dev.

**Comment by sharon-rabang** [comment]
[#225 cagov color scheme](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/225): This issue is related to the new Colors page. Will document the Colors' work in progress in #225, too.

**Comment by ashleydraper** [comment]
Tasks

- [ ] Dev to create redirects for all old files with "scheme" in the link to update to "theme" ((/src/scss/colortheme/oceanside.scss), research if this is possible)
- [ ] Content edits for color themes
- [ ] Link for contract ratio evaluation

**Comment by sharon-rabang** [comment]
10.12.22: Visual design: [Website Template Color Palette](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=72%3A9374) colors have been applied to all prototype pages in Figma.

Same comments from [#512 Update color scheme pages according to Figma prototype](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/512):
@Greg-Watanabe These prototype pages are ready for dev in Figma:

[Colors](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A4466)
[Color themes - Delta](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A4250)

Please update the the theme page's header and footer colors to match the website's colors (example: Statewide header = Primary color, Search bar = Gray 600, etc.).

Please let us know if we can help with any questions. Thanks!

**Comment by ashleydraper** [comment]
@sharon-rabang If this issue is ready for dev, remember to assign it to the developer and move it to their column.

**Comment by ashleydraper** [comment]
@Greg-Watanabe @kkoryaka Here are the google staging docs for content:

- [Colors](https://docs.google.com/document/d/1E3LB0hMUZF-DTVx8AsPmvVvGzU7cDeffrJeeDi9pJps/edit#)

- [Icons](https://docs.google.com/document/d/1LbgcENsfG_AgQ2sNEjJCtHTl4JxCoBe6hrsyXIAayIQ/edit#heading=h.5st7skvtgqwk)

- [Typography](https://docs.google.com/document/d/11oaHBWMaPXzwPCxEUAB65aSLps3nmyLzzE4tvmimSU0/edit#heading=h.ys22q3my1tv0)

**Comment by sharon-rabang** [comment]
10.14.22: Met and agreed to keep the header colors light and use a gray search bar. @sharon-rabang will update all of the headers and screenshots of the headers in Figma.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe FYI - The heading banner colors have been updated in Figma and are ready for dev. Sharing update here since it relates to the Color themes page.

Please go to the Figma page for reference: V6 State Web Template official - [V6 design components](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A3187)
Let me know if I missed anything, thanks!

**Comment by sharon-rabang** [comment]
Figma: [Settings banner colors](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=345%3A8786)

**Comment by sharon-rabang** [comment]
@Greg-Watanabe The Typography page is ready for dev. 

[Typography page](https://docs.google.com/document/d/11oaHBWMaPXzwPCxEUAB65aSLps3nmyLzzE4tvmimSU0/edit#) in google doc
[Typography page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=57%3A4871) in Figma

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/typography.html

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good, thanks! The only change to make:
- Change the color of the Public San in Google Fonts button outline and label to Primary #046B99.

**Comment by Greg-Watanabe** [comment]
@sharon-rabang
This is done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/typography.html

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good to go, thanks!
