### ISSUE TITLE
Update structure landing page to include structural components samples and code

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#306]
- Redesign structure page to include illustration for each structural component and add short description to each (see wireframe below)
- Create separate pages for each structural component:
    - Utility header
    - Settings
    - Site header
    - Mobile Controls
    - Site Navigation (this landing page already exists)
    - Search
    - Global Footer

- Work with @Courtney-Chittock  on design and content for all these pages.

LANDING PAGE WIREFRAME:
![Screen Shot 2022-05-26 at 10 04 15 AM](https://user-images.githubusercontent.com/31669748/170538586-aa3bf26e-422f-41c8-aa62-a95c70122a8d.png)

**Comment by Courtney-Chittock** [comment]
@kkoryaka please hold for design mockup from me as discussed in yesterday's meeting.

**Comment by kkoryaka** [comment]
@ashleydraper it's ready for content

**Comment by Courtney-Chittock** [comment]
@ashleydraper here is the link to the Figma board: https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=511%3A3236

**Comment by ashleydraper** [comment]
[Structure google staging](https://docs.google.com/document/d/1Mnw_Do_Ra8ozhCN-89DVraihOqTBJvjom6p1Zgmb_VI/edit) doc

**Comment by ashleydraper** [comment]
Splitting out the structural components and flowing for approvals.

@artuoma @extinah Please review the **[utility header](https://docs.google.com/document/d/1XNd6uPBNR704coeuNh16lNNUllmJ6ZTgyE9q4_Ky2ig/edit#heading=h.wmymts22289n)**.

**Comment by ashleydraper** [comment]
- [ ] Utility header
- [ ] Settings
- [ ] Site header
- [ ] Site navigation
- [ ] Side navigation
- [ ] Global footer

**Comment by ashleydraper** [comment]
@artuoma @extinah Please review the [site navigation](https://docs.google.com/document/d/1do8n7bgzpuSlPqtcQRgnijS92El8--T5zcbyiqXDuIE/edit#).

**Comment by extinah** [comment]
I've read and approve utility header (minor edits) and site navigation.
@artuoma

**Comment by ashleydraper** [comment]
@artuoma @extinah  Please review the **[footer](https://docs.google.com/document/d/1Gg-8bZmmCIv-GV7MjqlO9Lx1a93hKamlnsFlUXTKJeI/edit#)**.

**Comment by ashleydraper** [comment]
@artuoma @extinah Please review the **[settings component](https://docs.google.com/document/d/1cTGfoXdqUiGAt5V9Q_-rZaRVtmayN3nCoX1i2Wn1cO4/edit#)**.

**Comment by ashleydraper** [comment]
@kkoryaka  Adding you to this issue to begin mocking up the landing page. Here is the [**Structure landing page**](https://docs.google.com/document/d/1Mnw_Do_Ra8ozhCN-89DVraihOqTBJvjom6p1Zgmb_VI/edit) google staging doc.

**Comment by artuoma** [comment]
@ashleydraper done with all except Search which has been trashed?

**Comment by ashleydraper** [comment]
@artuoma That link is now updated, but I still have to merge the structural aspect to it.

**Comment by extinah** [comment]
> @artuoma @extinah Please review the **[settings component](https://docs.google.com/document/d/1cTGfoXdqUiGAt5V9Q_-rZaRVtmayN3nCoX1i2Wn1cO4/edit#)**.

Settings link doesn't work.

Footer is reviewed and approved.

Is there anything else left to review? :)

**Comment by ashleydraper** [comment]
Art reviewed the [**settings component**](https://docs.google.com/document/d/1siZ5c2YNAI-JsvBB3bSkSXQ5DOuVef19JJDTSVmtd20/edit#heading=h.rx4gk3lhdug1) and all the others in this bucket. We're done with structure content.

**Comment by ashleydraper** [comment]
@sharon-rabang All content has been reviewed, approved, and pasted in Figma. We now need some redesign on the visual examples. Let me know when you'd like to tackle this as I see there is some copy in the examples.

**Comment by sharon-rabang** [comment]
@ashleydraper How about Monday? I'm focusing on the side nav design tomorrow.

**Comment by ashleydraper** [comment]
Sounds like a plan!

**Comment by yesenia-gtz** [comment]
FYI Side navigation / Structural components #587 will not be available to beta release, goal to include updated design by production release in December

**Comment by sharon-rabang** [comment]
@ashleydraper All visual examples have been updated and are in place. Now we can just review them for their content and anything I missed.

**Comment by sharon-rabang** [comment]
@sharon-rabang @ashleydraper completed review of the Structure landing page and all the other structural elements pages.
Sharon will revise some of the visual examples in Figma.

**Comment by sharon-rabang** [comment]
@kkoryaka @ashleydraper The Structure landing page is ready for dev. Please use the [**google doc**](https://docs.google.com/document/d/1Mnw_Do_Ra8ozhCN-89DVraihOqTBJvjom6p1Zgmb_VI/edit) language as written and the **[Figma prototype](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A3950)** for reference.

**Comment by kkoryaka** [comment]
@sharon-rabang structure page should be now now up

**Comment by sharon-rabang** [comment]
@kkoryaka Looking good. Here are some design fixes to make:
- Side nav, Structural elements: Fix spelling for "Structural"
- Tabs for Example, Code, and Nunjucks: Does this not need Nunjucks? If not, we'll update the google doc and Figma
- Structural components heading: Fix spelling and change heading to "Structural elements"

**Comment by kkoryaka** [comment]
@sharon-rabang no nunjucka are needed for this page. I have updated those spelling errors

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good and ready, thanks! The Nunjucks tab has been removed from Figma.
