### ISSUE TITLE
Component content audit [blockquote]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#325]
Draft in progress for the **[blockquote component](https://docs.google.com/document/d/1a4MKyUL_jrWf_YAIa9zC0HJORtH3bXDgb7AKz_KTOp8/edit#heading=h.z68m2zuis6an)**.

**Comment by ashleydraper** [comment]
@Courtney-Chittock Sending this one your way to design the sample variants. We can discuss any code implications during our standup.

Cc: @kkoryaka

**Comment by kkoryaka** [comment]
@ashleydraper @Courtney-Chittock this one is ready for review

**Comment by ashleydraper** [comment]
[Staging link](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/blockquotes.html)

**Comment by kkoryaka** [comment]
@ashleydraper make sure you do hard refresh (which will update css styles). Also,, this page examples are based on figma design. So, I will keep without graphic that you crossed: https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=778%3A4351

**Comment by ashleydraper** [comment]
@kkoryaka I see, thank you for the advice to do a hard refresh. Let's chat about this one.

**Comment by kkoryaka** [comment]
@sharon-rabang @ashleydraper please add blockquote image variation to it.

**Comment by sharon-rabang** [comment]
Will close this past issue and continue the current work in progress in [#680](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/680).
