### ISSUE TITLE
Component content audit [button]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#327]
Draft in progress for the **[button component](https://docs.google.com/document/d/1fM8IxV0FZEcsxALCUsZydqSz1U5SZre6Jpf04pfpdT8/edit#heading=h.xv7rpjtvd3w5)**.

**Comment by ashleydraper** [comment]
This [button component](https://docs.google.com/document/d/1fM8IxV0FZEcsxALCUsZydqSz1U5SZre6Jpf04pfpdT8/edit#heading=h.xv7rpjtvd3w5)draft is complete and ready for review.

**Please keep edits in track changes**

Cc: @Courtney-Chittock @artuoma @yesenia-gtz

**Comment by ashleydraper** [comment]
@kkoryaka  This one is ready for dev.

**Comment by kkoryaka** [comment]
@ashleydraper please review

**Comment by ashleydraper** [comment]
Completed my review. Component looks great. Issue ready to close.

**Comment by artuoma** [comment]
@ashleydraper  review done

**Comment by ashleydraper** [comment]
@kkoryaka Please re-paste **all** the **[content](https://docs.google.com/document/d/1fM8IxV0FZEcsxALCUsZydqSz1U5SZre6Jpf04pfpdT8/edit#)**, I see that edits were made after this component was published. Also, please fix the typo.

![image](https://user-images.githubusercontent.com/62437425/195180808-93c991f0-c165-42f9-9551-57076c39ccc3.png)

**Comment by ashleydraper** [comment]
@timothyshambra I don't see this edit in dev...

**Comment by sharon-rabang** [comment]
@timothyshambra Looks good to go, thanks!
