### ISSUE TITLE
Pattern content audit [banner]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#332]
Merge the large hero banner component with the hero info pattern.

**Comment by ashleydraper** [comment]
**Current content in production** 

- [Large hero banner] (https://template.webstandards.ca.gov/sample/large-header-banner.html)
- [Hero info](https://template.webstandards.ca.gov/sample/hero-info.html)

**Staged content**

- [Large hero banner](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/large-header-banner.html)
- [Hero info]9https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/hero-info.html)

**Comment by extinah** [comment]
Review completed. Looks good :)

**Comment by artuoma** [comment]
My initial review and feedback is in the doc.

**Comment by ashleydraper** [comment]
Awesome! Thanks a bunch!

**Comment by kkoryaka** [comment]
@ashleydraper please review https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/large-header-banner.html

**Comment by ashleydraper** [comment]
@kkoryaka Couple thoughts-
![image](https://user-images.githubusercontent.com/62437425/189765205-04e1f6ea-ba0c-4d23-9599-7b1e41d20260.png)

![image](https://user-images.githubusercontent.com/62437425/189765539-2df89692-1227-4396-9c8c-1e74579ccf7b.png)

**Comment by kkoryaka** [comment]
@ashleydraper content is now updated. https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/hero-banner.html 
 And responding to your note I can say that banner height is calculated based on device viewport. In reality banner needs to be placed directly under the header and should occupy the rest of the page (like it is on the [homepage](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/)). Our sample container, however,  is not under the header and is placed into narrow column.  That is why it is not looking the way is supposed to  but the right code is in there.

**Comment by ashleydraper** [comment]
Excellent! Thanks @kkoryaka this component looks great, we can advance to the next milestone. 

I will note that the left side nave should just read "Patterns" and I also notice there is not yet a copy code button. Wondering if we're still adding that.

![image](https://user-images.githubusercontent.com/62437425/193328602-803708dd-229b-4943-9334-e01464e9266d.png)

**Comment by ashleydraper** [comment]
Reopening this issue. Per discussion on 10/5, Hero Banner will absorb hero info and feature banner. Hero info is similar enough in name and function that it does not need a separate call out. Feature banner will be added to the Hero banner pattern as a variant.

The google staging doc for the **[Hero banner pattern](https://docs.google.com/document/d/1NMEih8i7Si_m8jbXj1IyrJE9Gtie0I6LxM5a2xiQ5rs/edit)** is ready for review.

**Comment by artuoma** [comment]
@ashleydraper Added my comments!

**Comment by ashleydraper** [comment]
Decision made to hold off on this pattern for the state template. This work will be leveraged for the Design System.

**Comment by ashleydraper** [comment]
Pasting from Teams thread.

UPDATE on Banner:

I just got clarification on "Hero banner", I was hung up on the "hero" as it is a type of banner, I asked for it to be called "Banner" vs hero banner for v6. This aligns with the patterns we are proposing for Design System. [Updated content here ](https://docs.google.com/document/d/1NMEih8i7Si_m8jbXj1IyrJE9Gtie0I6LxM5a2xiQ5rs/edit#)(Thank you Draper, Ashley@CIO)

**Comment by yesenia-gtz** [comment]
Adding label for V6 production. OK to have available by December release.

**Comment by ashleydraper** [comment]
Updated issue name to "Banner."

Please review and edit in the **[google staging doc](https://docs.google.com/document/d/1NMEih8i7Si_m8jbXj1IyrJE9Gtie0I6LxM5a2xiQ5rs/edit)**.

**Comment by extinah** [comment]
This looks great. Reviewed and approved - no changes! :)

**Comment by yesenia-gtz** [comment]
@kkoryaka ready for dev

**Comment by artuoma** [comment]
Review completed - minor edits @ashleydraper

**Comment by yesenia-gtz** [comment]
@ashleydraper ready for you, see Art's edits in doc

**Comment by ashleydraper** [comment]
@sharon-rabang Content is approved, this pattern is ready for design.

**Comment by sharon-rabang** [comment]
@kkoryaka The banner page is ready for dev. 
- [Banner page](https://docs.google.com/document/d/1NMEih8i7Si_m8jbXj1IyrJE9Gtie0I6LxM5a2xiQ5rs/edit)in google doc
- [Banner page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=564%3A9403) in Figma

**Comment by kkoryaka** [comment]
@sharon-rabang this page should be ready. Please review

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some changes to make:
- Full span banner example: Reduce the height of banner from the bottom to center the content (see the Figma page for reference).
- Feature banner example: Reduce the size of the banner to visually illustrate how much shorter it is compared to the full span banner example above (see the Figma page for reference).
- Usage, "When and how to use it" section: In the "Webpage structure" link, use a capital "W" for sentence case consistency.

**Comment by sharon-rabang** [comment]
@kkoryaka Another content update to make:
- Accessibility section - Add a period at the end of every bullet item.

**Comment by kkoryaka** [comment]
@sharon-rabang please review. BTW, @ashleydraper and @extinah  asked me to remove all periods rom the bulleted sections the other day. including the accessibility section. You need to verify that with @ashleydraper 
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/banner.html
