### ISSUE TITLE
New Feature: Icon menu and pagination

### ISSUE THREAD

**Issue by Courtney-Chittock** [Office-of-Digital-Services/California-State-Web-Template-Website#340]
Add a mini menu and pagination feature so users can find available icons in the template.
[Feature mockup](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=268%3A2757)

Main audience: web designers and developers
Secondary audience: content owners
Location: In the Icons section of the redesigned Visual Design page. [See Figma mockup](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=165%3A6596).

Developers: 
- Talk to PM and Kon before beginning this assignment. 
- Please provide test links for QA and usability testing.
- Talk to Courtney with any questions about design or functionality.

![image](https://user-images.githubusercontent.com/99773875/173130172-2d749e57-4ac4-45ce-bb46-7b11dbc17fd1.png)
![image](https://user-images.githubusercontent.com/99773875/173130287-f8f2e1ef-ed61-4770-8d59-a95bb8a9fa89.png)

**Comment by kkoryaka** [comment]
@carterm i believe this is icons pagination issue

**Comment by carterm** [comment]
Looking at implementing pagination, which would make the letter grouping obsolete.

**Comment by kkoryaka** [comment]
@carterm  suggested that  pagination is going to be in next release (after 20th)
@artuoma has decided that for 20th release we will have search, letters, but no pagination

**Comment by yesenia-gtz** [comment]
@kkoryaka I thought this was in progress?  Why move to ice box? Do we need to hold off for production release in dec?

cc @artuoma

**Comment by yesenia-gtz** [comment]
[kkoryaka](https://github.com/kkoryaka) commented [7 days ago](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/340#issuecomment-1271972026)
@carterm suggested that pagination is going to be in next release (after 20th)
@artuoma has decided that for 20th release

@artuoma per the comment above: Please be sure to loop me into product decisions. We should meet the design recommendations to **include pagination below icon section for production release**. This was discussed and clarified in our team call on 9/23.

<img width="567" alt="Screen Shot 2022-10-14 at 8 05 33 AM" src="https://user-images.githubusercontent.com/98193284/195879910-3689cdc7-e47c-4e91-814b-81de0e3ccb18.png">

@sharon-rabang @extinah can you please link the updated dev specs/documentation for this recommendation for dev review?

**Comment by sharon-rabang** [comment]
@yesenia-gtz @kkoryaka @carterm Here is the the updated dev specs/documentation for this recommendation for dev review in [Figma: Dev specs/documentation](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=177%3A7569)

Here is the update Icons page in Figma: [Icons page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=75%3A5977)

Please develop the Icons page according to this design.

**Comment by yesenia-gtz** [comment]
@artuoma  who should be working on this? I see both Konstantin and Carter assigned. Please advise.

**Comment by artuoma** [comment]
Assigned to @korifan

**Comment by yesenia-gtz** [comment]
Assigning to @carterm per discussion with @artuoma and @kkoryaka 

We should meet the design recommendations to include pagination below icon section for December production release. This was discussed and clarified in our team call on 9/23.

**See notes in https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/340#issuecomment-1279133116**

**Comment by kkoryaka** [comment]
@carterm if  add that relevance logic that you mentioned on our dev's meeting that would be awesome. 
1. by whole name first, 
2. by whole tag word second, 
3. by matching string at the beginning of name/tag
4. by matching string anywhere in the name/tag

**Comment by sharon-rabang** [comment]
Watanabe, Greg@CIO @extinah and I are still working on the pagination design you're inquiring about. We'll let you know when our proposed pagination design and behaviors are ready for your feedback.

In the meantime, here are some content changes to make to the icon's page to simplify it further:
[Icons - Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=75%3A5977&t=CBCBzdXCI3cljNPk-1)
[Icons- Google Doc](https://docs.google.com/document/d/1LbgcENsfG_AgQ2sNEjJCtHTl4JxCoBe6hrsyXIAayIQ/edit#)

Let us know when the content changes are ready for review. Thanks!

**Comment by sharon-rabang** [comment]
12.02.22 Number of icons to display - Meeting notes
- Proposed a greater number of icons to display per page when using pagination, especially for users that are browsing the design options.
- @Greg-Watanabe 60 icons per page has been approved for dev: [Figma prototype with 60 icons/page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1715%3A24312&t=EP7PTQGcVYldMTFG-1)

**Comment by sharon-rabang** [comment]
12.07.22 Review Icons page functionality meeting notes.

Decisions:
- Default view is "A"
- Remove blue A-Z letters on "All" tab
- Include 60 icons per page with pagination above and below
-- Sharon and Ryan: Will look at how to design and display the top pagination in Figma.
- Keep "View all" below pagination on"All"
- Update sentence: Use the search to find a specific icon. You can also browse icons below.

**Comment by sharon-rabang** [comment]
**12.07.22 Meeting notes for "Review: Updated Icons page menu and pagination solutions"**
- Ryan and I updated the Icons page prototypes, based on the scenarios discussed and the decisions made during this morning's meeting. 
- Figma prototypes for review and feedback on feasibility:
-- [Alpha menu default](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1927%3A20490&t=EP7PTQGcVYldMTFG-1)
-- [View all](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1927%3A19464&t=EP7PTQGcVYldMTFG-1)
-- [Search results](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1927%3A20795&t=EP7PTQGcVYldMTFG-1)
-- [Full list](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1937%3A17290&t=EP7PTQGcVYldMTFG-1)

**Decisions:**
- Pagination design: 
-- For this release, the pagination at the top of the page will be the same as the bottom of the page.
-- The filtered version in Figma will be an enhancement in the next release.
-- Filtered pagination live demo and code, for reference: https://carbondesignsystem.com/components/pagination/usage/
- Full list version: 
-- This version is an addition to the decisions we made earlier.
-- Since this layout includes A-Z headings, this version will be part of the next release.

**Comment by Greg-Watanabe** [comment]
@sharon-rabang @hamiltonryan 
This is done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/icons.html

**Comment by hamiltonryan** [comment]
The search is looking great @Greg-Watanabe, thanks for bearing with all the changes!

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Design fix: We noticed that the active page number (inside the square gray outline) isn't set to Public Sans, Bold. Please update the font style and let us know when it's ready for UX review. Thanks!
[Figma Icons - View all](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1927%3A19464&t=tkxe5z7E279iVRxt-1)
![image](https://user-images.githubusercontent.com/99768807/207943718-307c0551-6bf8-4f89-9249-5f896915f197.png)

**Comment by Greg-Watanabe** [comment]
This is fixed
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/icons.html

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good to go, thanks!
