### ISSUE TITLE
New Feature: Icon search

### ISSUE THREAD

**Issue by Courtney-Chittock** [Office-of-Digital-Services/California-State-Web-Template-Website#341]
Add targeted icon search feature so users can find available components in the template.
[Feature mockup](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=268%3A2889)

Main audience: web designers and developers
Secondary audience: content owners
Location: In the Icons section of the redesigned Visual Design page. [See Figma mockup](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=165%3A6596).

Developers:
- Talk to PM and Kon before beginning this assignment.
- Please provide test links for QA and usability testing.
- Talk to Courtney with any questions about design or functionality.
- Talk to the PM for help creating the databases.
- This feature will eventually be used for a targeted component search in future iterations.

![image](https://user-images.githubusercontent.com/99773875/173131456-fbec5622-4ff9-4889-a593-52bd0d6cdf92.png)
![image](https://user-images.githubusercontent.com/99773875/173131510-1f27d9f2-1b72-459b-850d-8c59a9b32717.png)
![image](https://user-images.githubusercontent.com/99773875/173131581-9e5e71d6-9365-4167-8c3c-d8b602b105be.png)

**Comment by kkoryaka** [comment]
@Courtney-Chittock please review functionality and assign it back to @Greg-Watanabe for design improvements

**Comment by Courtney-Chittock** [comment]
Per meeting 7/15, Courtney will work on an icon spreadsheet so we can correct spelling errors and add keywords, and @Greg-Watanabe and @timothyshambra will work to align visual design to project Figma boards ([page mockup](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=165%3A6596) and [feature mockup](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=268%3A2889)).

**Comment by kkoryaka** [comment]
@carterm I have resigned it to you.

**Comment by Courtney-Chittock** [comment]
Adding @sharon-rabang to this issue. I will debrief her and give her pending design needs during our handoff meeting.

**Comment by sharon-rabang** [comment]
Met with @carterm to discuss the Icons page prototype in Figma to prep for its development. Will provide him with updates on any content changes, design revisions, and progress with the key words list.

**Comment by ashleydraper** [comment]
@sharon-rabang to update Figma with search text field box and display all icons

**Comment by sharon-rabang** [comment]
@carterm The Figma [Icons page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=75%3A5977) is ready for dev. Let me know if I can help with any questions. Thanks!

**Comment by kkoryaka** [comment]
@sharon-rabang please review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/icons.html

**Comment by yesenia-gtz** [comment]
@artuoma @kkoryaka @sharon-rabang @extinah please see my comment on https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/340#issuecomment-1279133116 

We should meet the design recommendations to include pagination below icon section for December production release. This was discussed and clarified in our team call on 9/23.

**Comment by yesenia-gtz** [comment]
@sharon-rabang  review https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/icons.html with the understanding that we will need to add in the pagination for December production release. Figma file will need to be updated to reflect the design recommendation proposed by Courtney 9/23.

**Comment by sharon-rabang** [comment]
@yesenia-gtz @kkoryaka @carterm Here is the the updated dev specs/documentation for this recommendation for dev review in [Figma: Dev specs/documentation](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=177%3A7569)

Here is the update Icons page in Figma: [Icons page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=75%3A5977)

Please develop the Icons page according to this design.

So far, the current Icons page in development needs these fixes:
- "How to use icons" section: Place the Info alert banner under the alpha menu. It is there as "just in time" information to help the user complete their task.
- "Do's and Don'ts" section: Add the gray lines under "Do" and "Don't"
- "Search icons" section: Use the same search bar design for website design consistency. We've provided an example to display what the user can click on (an "x") to clear the search bar.

**Comment by yesenia-gtz** [comment]
@artuoma @kkoryaka the staging site does not match the figma design, not sure what is happening with this. Seems like a lot of design is not being included in the build, why is this? example below.
![Screen Shot 2022-10-14 at 5 32 47 PM](https://user-images.githubusercontent.com/98193284/195960966-af9a8ca8-7951-4956-9b60-bac382c81d87.png)
 Please ensure development is completed  to design spec before asking for design to review staging.

**Comment by sharon-rabang** [comment]
@kkoryaka @sharon-rabang Worked on the Search icons section to: 
- Update the search bar design
- Place the the info alert box under the Search icons description, where it won't conflict with the search functions.
- @sharon-rabang Updated the [Figma: Dev specs/documentation](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=177%3A7569) and [Icons page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=75%3A5977)

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated in staging. please review it again

**Comment by sharon-rabang** [comment]
@kkoryaka Looking good, thanks! Here are some fixes to make under the Search icons section:
- Search bar: 
-- Change the input text label to "Browse icons" (In searching mode you are looking for a specific result, while in browsing mode you are looking for general ideas or multiple answers.)
-- Reduce the height of the "x" container to align it with the rest of the input text label's outline container.
- Alpha menu: 
-- Add 1px Gray-100 divider lines between the letters (See Figma [Icons page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=75%3A5977) and https://template.webstandards.ca.gov/sample/icon-fonts.html)
-- Selected/active letters: Add a gray background container to the active letter in Gray-900 bold text. 
In its current state, make the "All" text Gray-900 with a background gray container (Fill: Gray-50, Stroke: Gray-200, 1px) (See [Figma: Dev specs/documentation](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=177%3A7569))
- Number of icons: Change to 508 icons (Delete "found.")

**Comment by kkoryaka** [comment]
@cartem please add showing results container and logic
![Screen Shot 2022-10-18 at 2 19 46 PM](https://user-images.githubusercontent.com/31669748/196547081-5feae7bd-ec8b-4a68-958c-65fc04df99fe.png)

**Comment by kkoryaka** [comment]
@sharon-rabang please review it once more. https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/icons.html

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good, thanks!

**Comment by kkoryaka** [comment]
@yesenia-gtz this one is good to go and ready to be closed.
