### ISSUE TITLE
Component content audit [card]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#351]
Merge blurb variants and feature card into one card pattern.

- [Card google staging doc](https://docs.google.com/document/d/1mGaXH57kXyLGFcXOnCt8cxa91zeHimBlxC9rq8NIfcA/edit#)
- [Blurb pattern](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/blurbs.html) in dev 
- [Feature card](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/feature-card.html) in dev

**Comment by ashleydraper** [comment]
During the discussion on 6/20/2022, the team decided to label "card" as a component and not pattern within the state template. 
We will display this component in its simplest form (i.e. card container with short description), and remove compounding elements that would suggest a pattern.

This component is now with @artuoma and @extinah for review. Feedback has been requested by COB 6/24/2022.

**Comment by ashleydraper** [comment]
Received edits from Art and Christina. Once the recommendations are worked into the draft, will resend for approval.

**Comment by ashleydraper** [comment]
@kkoryaka All yours for dev.

**Comment by kkoryaka** [comment]
@ashleydraper please review https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/cards.html

**Comment by ashleydraper** [comment]
Completed my review.

![image](https://user-images.githubusercontent.com/62437425/192042182-39fbbee2-2d70-4823-bdb8-b5f3eaef34aa.png)

**Comment by kkoryaka** [comment]
@ashleydraper please review it again: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/cards.html

**Comment by ashleydraper** [comment]
Looks good. As a general note, please remove "Available" from the side navigation.

![image](https://user-images.githubusercontent.com/62437425/193330267-88dfca1f-540c-4ddd-8f8f-d82d4db37aa2.png)

**Comment by Courtney-Chittock** [comment]
Please follow the Figma board for side menu content. This is a drilldown page. The side menu should not change from the parent page.

**Comment by kkoryaka** [comment]
@ashleydraper for the components and patters page  let's focus on the content area and if there any issue with side nav arises let's collaborate on it directly it in the side nav issue [#223](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/223)

**Comment by ashleydraper** [comment]
@kkoryaka The card component should be moved back with patterns.

**Comment by yesenia-gtz** [comment]
@kkoryaka @ashleydraper @artuoma @extinah 

**Re Card timeline:**
I’ve looked over the Content on the card page in production. I don’t see anything jarring in content that would need to be addressed.  The content structure is consistent with what’s in the pattern section already. **No new content or content updates are needed for Beta release on 11/4, move over page with content as is for beta release**.

**Comment by kkoryaka** [comment]
@ashleydraper card is now part of the patterns. Please review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/card.html

**Comment by ashleydraper** [comment]
Looks good. Ready to close.
