### ISSUE TITLE
Sass variables for Bootstrap v4 breakpoints are incorrect

### ISSUE THREAD

**Issue by clhenrick** [Office-of-Digital-Services/California-State-Web-Template-Website#379]
The [Sass/SCSS variables for Bootstrap 4's breakpoints](https://github.com/Office-of-Digital-Innovation/California-State-Web-Template/blob/master/source/scss/variables.scss#L386-L391) are different that what are [specified in the Bootstrap v4.x docs](https://getbootstrap.com/docs/4.6/layout/grid/#grid-options). 

The Sass variables in this codebase appear to reference some values in the docs for breakpoints' **max container width**, _not the viewport width_,  which is what the breakpoint values actually are. Some appear to be custom (`$breakpoint-lg`) and to not match the docs at all. I confirmed this by using Bootstrap's Grid and watching when layout shifts occur at different viewport sizes according to the CSS classes for columns (e.g. `col-lg-6`, `col-md-4`, etc.). 

Currently the breakpoint values are specified as follows:

```scss
// Bootstrap4 breakpoints
$breakpoint-xm: 540px;
$breakpoint-sm: 720px;
$breakpoint-md: 960px;
$breakpoint-lg: 1140px;
$breakpoint-xl: 1280px;
```

But they should probably be something more like this for Bootstrap v4:

```scss
$breakpoint-sm: 576px; // "xs" < 576px, "sm" >= 576px
$breakpoint-md: 768px;
$breakpoint-lg: 992px;
$breakpoint-xl: 1200px;
```

It looks like there's a [Sass Mixin](https://github.com/Office-of-Digital-Innovation/California-State-Web-Template/blob/master/source/scss/cagov/mixins.scss#L234-L259) that uses these breakpoint variables, so I imagine changing them would have an undesirable affect on other UI components or layouts. However, it might be worth at least updating the code comment and including separate variables for the actual breakpoint values.

**Comment by kkoryaka** [comment]
Good catch @clhenrick. It will be updated in our beta release soon (we will keep our custom xl width value in there though). Also, these should not be bootstrap 4 but rather bootstrap 5 breakpoints. Thank you for your input.

**Comment by yesenia-gtz** [comment]
This has been resolved.
