### ISSUE TITLE
Component content audit [form style]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#408]
Drafting content in the [form component](https://docs.google.com/document/d/1JTKuRKCaaUDJb2SyGHtjpBcGpySt7yJG6pAOKD4GeEA/edit#heading=h.xv7rpjtvd3w5) staging doc.

**Comment by extinah** [comment]
This one is a big topic. Can we meet to discuss strategy on this one (or did y'all already do that?)

**Comment by ashleydraper** [comment]
@extinah We have not, but we should be flowing the path of least resistance on these. If we can smallify this big topic, that would make life a lot easier. Can we use what we have for an MVP and document notes for improvement after launch?

**Comment by extinah** [comment]
Decision: Let's keep on one page for the MVP and break out in the design system.

**Comment by kkoryaka** [comment]
@sharon-rabang this is ready for review, i made some adjustments and added couple of more essential elements that were missing. https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/form-elements.html

**Comment by sharon-rabang** [comment]
@kkoryaka The page in dev with your proposed changes and the [Form elements](https://docs.google.com/document/d/1JTKuRKCaaUDJb2SyGHtjpBcGpySt7yJG6pAOKD4GeEA/edit#heading=h.kf35mw7u91bx) Google doc have been reviewed. 

Feedback: It's a given that labels are part of form elements, so let's keep the completed content in the Google doc 'as is' for dev in this release. Your proposed changes and the missing elements are captured in Figma for consideration in the next design system.

The Figma [Form elements](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=137%3A5469) page is ready for dev, with these minor fixes to the dev examples (see green notes in Figma):
- Label, example: Use Figma's new screenshot 
- Text field, example: Use Figma's new screenshot 
- Check box, example: After each check box, use the Public Sans, Regular font
- Drop down menu, example:  Delete the colon after “Choose a car”

Thanks!

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated. I have added arrows. Please review. https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/form-elements.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks for updating the Label and Text field examples with the arrows, and for placing them in the Example/Source tabs. 
Feedback: The blue callouts and arrows need to be darker, and the arrows need to be without gaps for website design consistency. Please develop the [Forms elements](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=137%3A5469) page according to this Figma design.

**Comment by kkoryaka** [comment]
@sharon-rabang I made the updates. Please review it one more time.

**Comment by sharon-rabang** [comment]
@kkoryaka The updated blue arrows look great! 

After reviewing other examples yesterday, we needed to update the Text field example for consistency and clarity in Figma: [Forms elements](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=137%3A5469) page
![image](https://user-images.githubusercontent.com/99768807/196721835-8220fb8d-1887-47d6-a727-36169cb10f01.png)

Please let me know if I can help with any questions, thanks!

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka I don't see your Text field example updates. I refreshed many times.

**Comment by kkoryaka** [comment]
@sharon-rabang I have added those two gray-50 blocks that i could not notice the first time

**Comment by sharon-rabang** [comment]
@kkoryaka Looking good! Please make one design fix: Add white space between the 2 different examples, as shown here:
![image](https://user-images.githubusercontent.com/99768807/196829317-578d3e0b-1348-4b41-b9fc-533691478f22.png)

**Comment by kkoryaka** [comment]
@sharon-rabang sorry about that.  (it seems like my productivity goes below zero by the end of the day :) . i have added that space.

**Comment by extinah** [comment]
@kkoryaka @ashleydraper 
cc: @artuoma @yesenia-gtz @sharon-rabang 

On Friday, we need to discuss the process moving forward for changes. Kon has good feedback but we need a better way to provide those (e.g. suggestions in google doc). We just need to be on the same page to allow folks feedback and to know when the edit should happen (or if it should happen).

**Comment by sharon-rabang** [comment]
@yesenia-gtz Thanks for going over our content review process moving forward, at today's V6 weekly meeting. 

Please take a look at the Form elements content between these three pages for Internal/Lead review and approval. The approved content will help us ensure consistency between all three.
 
- [Form elements - staging doc](https://docs.google.com/document/d/1JTKuRKCaaUDJb2SyGHtjpBcGpySt7yJG6pAOKD4GeEA/edit#heading=h.xv7rpjtvd3w5) 
- [Form elements - development](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/form-elements.html)
- [Form elements - Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=137%3A5469) page

**Comment by yesenia-gtz** [comment]
@extinah [ Content doc has been updated](https://docs.google.com/document/d/1JTKuRKCaaUDJb2SyGHtjpBcGpySt7yJG6pAOKD4GeEA/edit#) to align with [Staging ](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/form-elements.html)items. There were content edits made which will require another pass by development before we launch. Can you review the suggested edits before handing to Sharon to update figma?

@sharon-rabang we will need to align the figma layout to the update content linked above. When ready please work with christina to allocate layout update to design team if needed.

**Comment by extinah** [comment]
@yesenia-gtz  I have some suggested changes. Please review - we can chat if needed.

Note: The usage section is not in dev at all. would need to call that out when this goes to dev.

**Comment by yesenia-gtz** [comment]
@kkoryaka Content doc has been updated to include edits made in staging development. Please assign accordingly to the engineering team.

Development Tasks:
- [ ] Update staging to reflect [the most up-to date content order](https://docs.google.com/document/d/1JTKuRKCaaUDJb2SyGHtjpBcGpySt7yJG6pAOKD4GeEA/edit#heading=h.u5167dhcwer6)
- [ ] Add in Usage section to development
- [ ] Align development to design to is in [figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=137%3A5469).

cc: @sharon-rabang @extinah

**Comment by kkoryaka** [comment]
@sharon-rabang please review https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/form-elements.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! 

Here are some changes to make:
- Form elements section, bullets: Remove extra "e" from Checkbox
- Checkbox, example: Update with the basic one in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=592%3A10126)
- Radio button, example: Update with the basic one in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=592%3A10126)
- Drop down menu:
-- Subheading: I added this to the google doc and [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=592%3A10126)
-- Example: Update with the basic one in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=592%3A10126)
- File input example: 
--- Upload your file: Remove colon
--- Choose file: Use lowercase "f" for sentence case consistency

**Comment by kkoryaka** [comment]
@sharon-rabang In input file I can't change "Choose File" to lover case because it's native browser's HTML text. It's there by default

**Comment by sharon-rabang** [comment]
@kkoryaka Okay, thanks for letting me know that it's there by default!

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated, please review

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!

**Comment by extinah** [comment]
@kkoryaka  please update the radio button options to: option 1, option 2, option 3? 
Right now they say option 1, option 1, option 1

Thanks

**Comment by yesenia-gtz** [comment]
@kkoryaka moved back into Ready for Development.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
