### ISSUE TITLE
Component content audit [tab]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#413]

**Comment by ashleydraper** [comment]
@artuoma 
The [**tabs** component](https://docs.google.com/document/d/1M2eFfCIbwch1p6F4jWzNrwwuZOjaZX8J-dA5GlLGyJc/edit#heading=h.kf35mw7u91bx) is ready for review.

**Comment by extinah** [comment]
Minor edits. Looks good.
@artuoma

**Comment by kkoryaka** [comment]
@ashleydraper this one is now updated: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/tabs.html

**Comment by ashleydraper** [comment]
@kkoryaka  How about just these:

Basic
![image](https://user-images.githubusercontent.com/62437425/195192102-7dec7ad0-08a6-4b49-af47-79b762296a18.png)

Shaded
![image](https://user-images.githubusercontent.com/62437425/195191907-56acfac3-755f-42d6-bec0-a1a5f7e6fe69.png)

**Comment by ashleydraper** [comment]
![image](https://user-images.githubusercontent.com/62437425/195196668-623c4523-7627-4ab2-b3d4-743c4b31b1d3.png)

**Comment by kkoryaka** [comment]
@ashleydraper this one is fixed please review once more

**Comment by ashleydraper** [comment]
Looks good. Ready to close.

**Comment by extinah** [comment]
@ashleydraper 
The google doc doesn't have periods.
We don't have content standards yet, but best practice is no periods at the end of bullets.
Let me know what you think.

**Comment by ashleydraper** [comment]
Great point. I tend to use them when they read like a complete thought (sentence) and are not a single word list. We could use some standardization here, but my recommendation is to add periods like the screen shot mock up.
