### ISSUE TITLE
Update pages URLs to correspond with site's structure

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#453]
Update pages' URLs to correspond with site's structure and hierarchy: 
For instance, if a blockquote sample  page has components parent landing page the url should be 
siteroot/components/blockquote.html

To change a page url in eleventy please change the permalink in the front matter. That will create corresponding folder in the site output. (No need to change the folders structure in the /pages/ folder)
![Screen Shot 2022-08-09 at 11 26 05 AM](https://user-images.githubusercontent.com/31669748/183734022-b61b45e1-8b31-4dcd-9da9-e680b57c32e4.png)

Once permalinks are updated all pages URLs have to be updated in /data/ folder JSON files. 
![Screen Shot 2022-08-09 at 11 34 22 AM](https://user-images.githubusercontent.com/31669748/183735612-2efa4f06-20ee-4893-98b8-c8e74772b4bb.png)
 
![Screen Shot 2022-08-09 at 11 40 57 AM](https://user-images.githubusercontent.com/31669748/183736528-e06b21d8-8f9b-4e98-a14a-58af28c3ed59.png)

Finally, find and update all the reference links inside of the page content.
![Screen Shot 2022-08-09 at 11 40 02 AM](https://user-images.githubusercontent.com/31669748/183736565-d4912d37-1795-4898-9821-e3fbdac85510.png)

**Comment by kkoryaka** [comment]
@Courtney-Chittock will you provide the sitemap of all live pages with updated URLs?

**Comment by ashleydraper** [comment]
@kkoryaka Here is the updated [component tracker spreadsheet](https://docs.google.com/spreadsheets/d/11j0r3flPCG5wvpa5flClG8x5-e0ZxROl-HQoaTkSsNM/edit#gid=669951285). Use the **proposed URL** column to update page URLs.

**Comment by ashleydraper** [comment]
Ashley and Konstantin to sidebar on this

**Comment by kkoryaka** [comment]
@ashleydraper URLs are now updated. please review.

**Comment by ashleydraper** [comment]
Looks great. Ready to close.
