### ISSUE TITLE
Add color scheme specific color to the utility header background to differentiate between the color schemes

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#466]
Ass color-s1 (subtle primary color) to  utility header background just enough to feel the difference between different color schemes

![Screen Shot 2022-09-09 at 12 35 30 PM](https://user-images.githubusercontent.com/31669748/189430041-85e594ae-8268-4238-bdc9-dea70019dcbe.png)

![Screen Shot 2022-09-09 at 12 37 16 PM](https://user-images.githubusercontent.com/31669748/189430328-101deba3-a24e-4b3f-bbaa-32bbacd15794.png)

**Comment by yesenia-gtz** [comment]
@sharon-rabang is this complete and OK to close out?

**Comment by sharon-rabang** [comment]
@yesenia-gtz This is still in progress and part of [#512](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/512), [#280](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/280). 

As discussed at today's stand-up, I will work with @kkoryaka to work on feedback from @artuoma.

**Comment by sharon-rabang** [comment]
10.14.22: Met and agreed to keep the header colors light and use a gray search bar. @sharon-rabang will update all of the headers and screenshots of the headers in Figma.

**Comment by sharon-rabang** [comment]
@kkoryaka The heading settings banner colors have been updated and are ready for dev.

Please go to the Figma page for reference: V6 State Web Template official - [V6 design components](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A3187)
Let me know if I missed anything, thanks!

**Comment by sharon-rabang** [comment]
Figma: [Settings banner colors](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=345%3A8786)

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good! All the statewide utility header options displayed the correct s-1 on the [Color themes](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/color/?delta) page. 
There's one design fix to make: Change CA.gov logo colors to be consistent with the Design System (Ca = yellow, .gov = blue)

**Comment by kkoryaka** [comment]
@sharon-rabang  the logo should be updated there too.

**Comment by sharon-rabang** [comment]
@kkoryaka Logo looks good and ready, thanks!
