### ISSUE TITLE
Card pattern variants

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#467]
Add more complex features to the [card component](https://github.com/Office-of-Digital-Innovation/California-State-Web-Template/issues/351) that justify movement to the pattern category.

**Comment by extinah** [comment]
May determine to do in 6.1.2 release or only in DS. TBD.

**Comment by kkoryaka** [comment]
@timothyshambra please add variations from card grid to this pattern so card has all same variations.

**Comment by kkoryaka** [comment]
@timothyshambra  Cristina also asked to update figma with those variations.

**Comment by kkoryaka** [comment]
@timothyshambra have pushed this one? I thought I saw your PR and approved it but for some reason it's not in dev

**Comment by kkoryaka** [comment]
@extinah this is now in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/patterns/card.html

**Comment by extinah** [comment]
@hamiltonryan Please review. Thanks!

**Comment by hamiltonryan** [comment]
@extinah @kkoryaka 
This has been reviewed and looks good to go.  

Ready to move and close. Thank you!
