### ISSUE TITLE
Pattern content audit [link grid]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#470]

**Comment by ashleydraper** [comment]
Moving the [**link grid**](https://docs.google.com/document/d/1pQN5tNBUJZK8V3R1Uc-jX5-TkDNFk7ID8abskr3-h8w/edit#) content forward for review.

@sharon-rabang Flagging for your attention. The example will need some redesign.

**Comment by extinah** [comment]
Looks great - approved. Thanks!
@ashleydraper

**Comment by kkoryaka** [comment]
@artuoma will review it and tag @ashleydraper

**Comment by yesenia-gtz** [comment]
@artuoma assigning you to this, once you are done reviewing assign to Ashley

**Comment by sharon-rabang** [comment]
> Moving the [**link grid**](https://docs.google.com/document/d/1pQN5tNBUJZK8V3R1Uc-jX5-TkDNFk7ID8abskr3-h8w/edit#) content forward for review.
> 
> @sharon-rabang Flagging for your attention. The example will need some redesign.

@ashleydraper The example has been redesigned in Figma. The redesign is based on the other Pattern examples for consistency.

**Comment by extinah** [comment]
@ashleydraper  This says it's ready for my review - I already reviewed an approved. Did someone have a specific question?

**Comment by ashleydraper** [comment]
@timothyshambra This one ready for dev. Find the design mock up in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=46%3A4771).

**Comment by sharon-rabang** [comment]
@timothyshambra Thanks! Here are some fixes to make: 
- Update the first 2 paragraphs with the content from the [Link grid](https://docs.google.com/document/d/1pQN5tNBUJZK8V3R1Uc-jX5-TkDNFk7ID8abskr3-h8w/edit#) google doc.
- Update the example with the image used on the [Link grid](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=46%3A4771) page in the Figma.

**Comment by sharon-rabang** [comment]
@timothyshambra Looks good to go, thanks!
