### ISSUE TITLE
Figure with Captions design improvements

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#474]
improve Figure with Captions pattern spacing, typography, colors and overall design. Make it work with overall design system look and feel.

Current link: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/figure.html

**Comment by kkoryaka** [comment]
Angelina waned to make quick changes and improve typography. But we not going show it this release. We can add it back into our next production release.

**Comment by yesenia-gtz** [comment]
@Angsv what is the estimate lift for this? if other priorities that take over this, can we hold for the Production release if time allows?

cc @artuoma

**Comment by Angsv** [comment]
@yesenia-gtz I'll get this into figma tomorrow by noon-ish

**Comment by yesenia-gtz** [comment]
Moving to current sprint, thank you!

**Comment by Angsv** [comment]
Figure with Captions has been added to the Figma patterns - ready for review/final approval
