### ISSUE TITLE
News Lists design improvements

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#475]
improve News Lists pattern spacing, typography, colors and overall design. Make it work with overall design system look and feel.

Current link: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/news-list.html

**Comment by kkoryaka** [comment]
This item needs to be in v6 production @ashleydraper

**Comment by extinah** [comment]
@ashleydraper  @sharon-rabang  revisiting this.

**Comment by sharon-rabang** [comment]
Related to [#476](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/476)

**Comment by ashleydraper** [comment]
@sharon-rabang Can we meet about this when you return?

**Comment by sharon-rabang** [comment]
@ashleydraper FYI - @extinah has some design guidance to share for this. Will let you know when there's a draft for us to go over.

**Comment by sharon-rabang** [comment]
@ashleydraper @extinah - We're currently focused on completing issues for 6.1. This one will need to remain in backlog for the 6.1.1 release (end of Feb).

**Comment by extinah** [comment]
Initial draft content
https://docs.google.com/document/d/1u8jrMFxo0bGM5FfyCvrCOIBMZbt1c91H5ck5gbZhVF0/edit#

@sharon-rabang feedback appreciated :)

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @extinah @kkoryaka 
These related Pattern pages and each of their templates are ready for Leads review.
Please let us know if you have questions or if they're ready for dev. Thanks!

Here are the Figma prototypes and Google docs:
**Figma**
- [Patterns](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3339%3A31097&t=EhAkPulHfeAooRYe-1)
  - Add "Page templates" subsection to:
    - All the Pattern pages' side nav as links
    - The bottom of the Patterns landing page with an H2, its description, and cards
 - [#1251](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/1251): [Newsroom](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3344%3A32115&t=EhAkPulHfeAooRYe-1)
 - [#475](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/475): [List of articles or content](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3339%3A31859&t=EhAkPulHfeAooRYe-1)
- [#476](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/476): [Article](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3339%3A31664&t=EhAkPulHfeAooRYe-1)
	
**Google docs**
- [Newsroom](https://docs.google.com/document/d/1aPWK7zosSLLlAALkJ5zOiqyVBGYRwLqkisCkD8WLHAw/edit)
- [List of articles or content](https://docs.google.com/document/d/1u8jrMFxo0bGM5FfyCvrCOIBMZbt1c91H5ck5gbZhVF0/edit#heading=h.7i9rg0jspn25)
- [Article](https://docs.google.com/document/d/1L9rSVMU7o_oM9WA57RCH3eZaz890s_zmCBl1G4ibkq8/edit)

**Comment by sharon-rabang** [comment]
**03/03/23 UX/Dev meeting notes**

Feasible template Live examples":
- Generic header footer
- Open example in a new tab
- Not a part of the template download (just provide source code)
- Option: CAWeb - Possibly make these page template available (make it easy for users)

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @extinah @kkoryaka @carterm Hi! This is a friendly reminder for Leads review of this content. 
Please let us know if it looks ready for dev. Thanks!

**Comment by kkoryaka** [comment]
@sharon-rabang this is now in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/patterns/list-of-articles-or-content.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some fixes to make:

**Sample**
- Image example: Please replace with these attached .png files for better quality display
![List of articles or content-Template](https://user-images.githubusercontent.com/99768807/226433537-57051083-9d6f-4b15-b9d5-2591588dc26c.png)

- Button:
  - Change from "Live example" to "Live example in new tab" for accessibility,
  - Change outline and text colors from gray to Primary #046B99 for consistency
  - Add arrow for consistency
![image](https://user-images.githubusercontent.com/99768807/226433716-8f48f645-edb2-481b-adbb-61d38ae33bd7.png)

**Under Usage, Tip:** 
- Change from "Pro tip" to "Tip" to simplify tone
- Change from text highlight to Public Sans Bold only to be consistent with the change to the Executive profile Usage note

**Comment by kkoryaka** [comment]
@sharon-rabang this is now fixed https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/patterns/list-of-articles-or-content.html

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
