### ISSUE TITLE
News article: Design improvements

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#476]
improve News Detail pattern spacing, typography, and overall design. Make it work with overall design system look and feel
Current link: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/news-detail.html

**Comment by ashleydraper** [comment]
We actually don't have a news detail component. See the [component matrix](https://docs.google.com/spreadsheets/d/11j0r3flPCG5wvpa5flClG8x5-e0ZxROl-HQoaTkSsNM/edit#gid=669951285). Recommend closing this issue.

**Comment by ashleydraper** [comment]
After discussion on 10/5, we will re-add this pattern and rename to **News Article**. This pattern is low priority, but will require content and a visual redesign. 

Visit schema.org for content inspo

**Comment by yesenia-gtz** [comment]
@ashleydraper @sharon-rabang Moving this Prod release milestone if time allows

**Comment by sharon-rabang** [comment]
Related [#475](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/475)

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @extinah @kkoryaka 
These related Pattern pages and each of their templates are ready for Leads review.
Please let us know if you have questions or if they're ready for dev. Thanks!

Here are the Figma prototypes and Google docs:
**Figma**
- [Patterns](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3339%3A31097&t=EhAkPulHfeAooRYe-1)
  - Add "Page templates" subsection to:
    - All the Pattern pages' side nav as links
    - The bottom of the Patterns landing page with an H2, its description, and cards
 - [#1251](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/1251): [Newsroom](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3344%3A32115&t=EhAkPulHfeAooRYe-1)
 - [#475](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/475): [List of articles or content](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3339%3A31859&t=EhAkPulHfeAooRYe-1)
- [#476](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/476): [Article](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3339%3A31664&t=EhAkPulHfeAooRYe-1)
	
**Google docs**
- [Newsroom](https://docs.google.com/document/d/1aPWK7zosSLLlAALkJ5zOiqyVBGYRwLqkisCkD8WLHAw/edit)
- [List of articles or content](https://docs.google.com/document/d/1u8jrMFxo0bGM5FfyCvrCOIBMZbt1c91H5ck5gbZhVF0/edit#heading=h.7i9rg0jspn25)
- [Article](https://docs.google.com/document/d/1L9rSVMU7o_oM9WA57RCH3eZaz890s_zmCBl1G4ibkq8/edit)

**Comment by sharon-rabang** [comment]
**03/03/23 UX/Dev meeting notes**

Feasible page template "Live examples":
- Generic header footer
- Open example in a new tab
- Not a part of the template download (just provide source code)
- Option: CAWeb - Possibly make these page template available (make it easy for users)

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @extinah @kkoryaka @carterm Hi! This is a friendly reminder for Leads review of this content. 
Please let us know if it looks ready for dev. Thanks!

**Comment by kkoryaka** [comment]
@sharon-rabang this is now in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/patterns/article.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some fixes to make:

**Sample**
- Live example (in new tab): Please flip the social media "link icon" to display like it does in Figma and the image example
- Image example: Please replace with these attached .png files for better quality display
![Article-Template](https://user-images.githubusercontent.com/99768807/226435572-fe23c65a-c39f-4792-a540-1bd9494e055f.png)
- Button:
  - Change from "Live example" to "Live example in new tab" for accessibility,
  - Change outline and text colors from gray to Primary #046B99 for consistency
  - Add arrow for consistency
![image](https://user-images.githubusercontent.com/99768807/226435531-f2824bda-2bfd-47c7-86f4-bb1dbfd1e4a0.png)

**Under Usage, Tip:** 
- Change from "Pro tip" to "Tip" to simplify tone
- Change from text highlight to Public Sans Bold only to be consistent with the change to the Executive profile Usage note and List of articles page

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good, thanks! Please replace the sample image with this revised version (the link icon is now consistent with the icons library):
![Article-Template](https://user-images.githubusercontent.com/99768807/226465578-fac6feac-dc46-46e2-ad97-2e1cef2a7443.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this is now fixed https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/patterns/article.html

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
