### ISSUE TITLE
Executive profile design improvements

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#477]
improve Profile Banners  pattern spacing, typography, colors and overall design. Make it work with overall design system look and feel.

Current link: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/profile-banners.html
Template link: https://template.webstandards.ca.gov/sample/profile-banners.html

Edited to add:

- [x] rework design - angelina
- [x] write content - ashley

**Comment by yesenia-gtz** [comment]
@kkoryaka @sharon-rabang moving this one to be completed by Prod release milestone

**Comment by sharon-rabang** [comment]
@Angsv As you redesign the profiles examples, here are some notes from our 10/05/22 Patterns UX workshop, for reference:
- Redesign with design elements and type that compliment our look and feel
- Do research to find best examples to display
- Rename as "Profiles"?

@yesenia-gtz Can you or someone else create content for this page, to be consistent with the other pattern pages?

**Comment by extinah** [comment]
@Angsv checking in now that QA is done. :)

**Comment by extinah** [comment]
Per today's meeting, discussed that the "how to use this" content may recommend putting this closer to (or even in) the footer to not distract from top user tasks. Also talked about making it more subtle.
This will be a pattern possibly called Executive profile.

**Comment by extinah** [comment]
@Angsv @ashleydraper this is back in the queue to work on.

**Comment by ashleydraper** [comment]
@extinah  Finally moving this one forward! Here is the [google doc](https://docs.google.com/document/d/16_a2icPyLRjqBK3S3nQ-WbNK8Yu1fNJcuS73wizZnYc/edit#heading=h.wmymts22289n) for your review.
Vertical design
![image](https://user-images.githubusercontent.com/62437425/217982359-df7a450b-9442-446b-85d4-d25aa530da38.png)

Horizontal design
![image](https://user-images.githubusercontent.com/62437425/217982416-92327ef8-d8a1-47fb-b00d-a371f10eb9d0.png)

**Comment by kkoryaka** [comment]
@sharon-rabang who will work on figma design for it? Because fefore i assign it to a dev we need to have figma design of this component.

**Comment by sharon-rabang** [comment]
@kkoryaka: @hamiltonryan will work on the Figma design.

**Comment by extinah** [comment]
@Angsv 
Please add this to the state template workspace under patterns (as a page with the content). 
Also, please provide 2 samples on how this would look on a department website (ideally 2 sites that look different)
Trying to get this to be reviewed by the UX team today and hopefully for approval on Monday.

**Comment by extinah** [comment]
Hi @Angsv,
Per our chat, you had included a first draft of the executive profile - thank you. Here's the link to the prototype.
https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1410%3A14030&t=jPbdtzsNBRnp1fdE-1

Upon initial review:

- [ ] Please label the different types (vertical/horizontal)
- [ ] Style the example using oceanside (since that's what our template is in)
- [ ] The scale is off in the example. Use a size that work on a department homepage
- [ ] Provide a sample of the executive profile on some websites (template site and a site that uses the design system)
- [ ] We discussed different light vs dark background. Provide those two as separate sections and what colors you recommend from the palette (primary, standout, etc)
- [ ] Related to light/dark background, draft implementation notes.
- [ ] Consider showing a screenshot that shows what this looks like in context of a page (could pair with usage content).

When that's done, you can move this component through the process. the next step is to change the status to Ready for UX review. You can assign to me, Sharon, and Ryan (keep yourself assigned). You may need to set up a meeting for the review to walk us through it. Feel free to set up any adhoc design feedback chats (we often do). Thanks.

**Comment by Angsv** [comment]
Hi @extinah 

These profile examples are designed to be transparent, which is why they do not use oceanside as a default color and why there doesn't need to be a light or dark version. 

We already had a walkthrough/workshop meeting last week with Ashley, where the example and content were reviewed and agreed on. 

For clarification: Do you want me to redo the content and visual example that was agreed on last week?

**Comment by Angsv** [comment]
@extinah 

Rescaled the profile samples.
Separated out the vertical and horizonal profiles (added labels). 

I will work on creating a mock page for your review.

**Comment by extinah** [comment]
@Angsv Thank you! I'll try to get to the content today - I've been behind on all of my state template tasks.

**Comment by extinah** [comment]
@Angsv: Updated draft content done. Ready for your review, too. I highlighted the updates.
https://docs.google.com/document/d/16_a2icPyLRjqBK3S3nQ-WbNK8Yu1fNJcuS73wizZnYc/edit#heading=h.wmymts22289n

I also put 2 of the exec profiles using the state template homepage to facilitate reviews.

**Comment by Angsv** [comment]
@extinah 

Per last review session on 03/03/2023 I have:

-moved content from google doc to figma file 

-created profiles samples
--horizontal
---opaque light
---opaque dark
---transparent 
----100%
----80&
----50%
----20%
--vertical
---opaque light
---opaque dark
---transparent 
----100%
----80&
----50%
----20%

-created homepage visuals for UX Design review
--desktop homepage
---horizonal profiles 
--vertical profiles
--mobile 
---horizonal profiles 
--vertical profiles

Next steps:
As per @artuoma I will be contacting devs to "hash it out"

**Comment by Angsv** [comment]
Spoke with @timothyshambra and @jon-grant-state-ca-gov and made some more adjustments per their feedback (see proposed block in Figma https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3397%3A31767&t=DWq1x1GNPKPcwCOx-0) 

-Removed the transparency gradation 
-Kept 100% transparent and opaque
-Kept light and dark versions
-Kept horizontal and vertical profiles


@extinah @artuoma @sharon-rabang 

Points to consider:
Horizontal profile: 
-If font is kept similar to how it is in figma - having 3 profiles next to each other on a home page may become too cramped.
--potential solutions:
---use vertical profiles instead
---stack the horizontal profiles

Mobile
-which one should be used: horizontal or vertical?

**Comment by extinah** [comment]
Approved at our leads meeting today at 2 pm.
@kkoryaka ready to be assigned. Whoever codes this can set up a meeting with us for clarity.

**Figma**: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3466%3A36834&t=Bjfp6DXhOki6YhDj-1
**Google doc**: https://docs.google.com/document/d/16_a2icPyLRjqBK3S3nQ-WbNK8Yu1fNJcuS73wizZnYc/edit

**Design spec**s:

- Height of 1px line: 8px above and below the profile text (roughly 123.5px total) 
- Line should extend to match the height of all the text
- Padding (left/right) of line: 16px either side 
- Container with default secondary background color: 
- Max width: 420px
- Should this be done automatically or manually?
- Photo: 
- 100px x 100px
- Only use a portrait of an individual (See Usage)
- Content: Input the template’s information
- Mobile view: Stack profiles

**Comment by kkoryaka** [comment]
@sharon-rabang this is now in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/executive-profile.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some fixes to make:

**On this page list:** 
- Default: Fix spelling by adding a 't' at the end
- Layout: Delete - this is an H3

**Default heading:** Fix spelling by adding a 't' at the end

**Under Usage, Note:** Change from text highlight to Public Sans Bold only (it looks like a mistake in this instance).

I corrected the Google doc's headings to match Figma. Please do the same in dev for these:

- **Layout heading:** Change from H2 to H3
- Under Layout, **Default**:
  - Heading: Change from H3 to H4
  - Image: Please replace with attached .png file for better quality display
- Under Layout, **Transparent: Dark background**:
  - Heading: Change from H3 to H4
  - Image: Please replace with attached .png file for better quality display
![Homepage-Executive profile 1](https://user-images.githubusercontent.com/99768807/226048816-125a928b-de44-486e-a6e9-a1d5866d46fe.png)
![Homepage-Executive profile 2](https://user-images.githubusercontent.com/99768807/226049495-57c520b8-8ead-44b1-b820-dbd4fccd27f8.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this page is now fixed https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/executive-profile.html

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
