### ISSUE TITLE
Card grid design improvements

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#479]
Review blurb pattern design and suggest design improvements so it works better with Design System look and feel
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/blurbs.html#no-margin

**Comment by ashleydraper** [comment]
Per discussion on 10/5, blurb will be renamed as **Card grid**. Card grid will have 4 variants:

- Basic card grid
- News grid
- Card grid with icon
- Card grid with image

Here is the google staging document for the new **[card grid pattern](https://docs.google.com/document/d/1RfZNdp00ByVkpdp3yBJS8ihVtcfrXV4h9EP6uppc80I/edit#heading=h.vks7bf7ezumu)**.

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks for setting up the **Card grid** page https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/card-grid.html 

@Angsv Let me know when you're ready to discuss the design improvements we can make.

**Comment by sharon-rabang** [comment]
Design:
- @Angsv completed card grid design examples
- @sharon-rabang will retouch the sets of images to display with an even tone

**Comment by extinah** [comment]
@ashleydraper  Done reviewing content and prototype. Looks good. Minor comments of both the doc and prototype.

@artuoma  Poke!

**Comment by ashleydraper** [comment]
@kkoryaka Happy to move this to dev. Here are the content and design docs:
- [Card grid in Google docs](https://docs.google.com/document/d/1RfZNdp00ByVkpdp3yBJS8ihVtcfrXV4h9EP6uppc80I/edit)
- [Figma wireframe](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=45%3A7548)

**Comment by kkoryaka** [comment]
@ashleydraper @sharon-rabang this is now updated: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/card-grid.html

**Comment by sharon-rabang** [comment]
@kkoryaka @ashleydraper Design looks good! Can we make 2 minor fixes?
Basic card example: 
- @kkoryaka Can we make the card titles Oceanside Primary #046B99?
- @ashleydraper In the second card's content, can we change the last sentence to "Font style can be customized."? Customizing the font 'size' may lead to inconsistencies.

**Comment by ashleydraper** [comment]
@sharon-rabang  You bet. I'll check it out and propose new content.

**Comment by ashleydraper** [comment]
@kkoryaka Here's is the new content, I will also drop in the google doc

### Card title

Use the content found at the button link to inspire your card title.

### Title
Cards use the [heading](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/typography.html) text style for titles. Keep them short, concise, and consistent.

**Comment by kkoryaka** [comment]
@sharon-rabang @ashleydraper this is now updated https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/card-grid.html

**Comment by sharon-rabang** [comment]
@kkoryaka @ashleydraper Thanks! I will find an image for the card sample and let you know when it's ready in Figma.

**Comment by sharon-rabang** [comment]
@kkoryaka @ashleydraper The card example's image is ready for dev in Figma: [Patterns: Card](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=365%3A8311)
The link to this royalty-free image is at the bottom of the Patterns Figma page, if needed.

**Comment by ashleydraper** [comment]
This looks excellent. Great work team. Ready to close.
