### ISSUE TITLE
Update color scheme pages according to figma prototype

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#512]
Update color scheme pages layout based on [figma prototype](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=123%3A6139)

https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-delta.html
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-eureka.html
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-mono.html
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-oceanside.html
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-orangecounty.html
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-pasorobles.html
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-sacramento.html
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-santabarbara.html
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-santacruz.html
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-shasta.html
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-sierra.html
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/colorscheme-trinity.html

**Comment by kkoryaka** [comment]
@Greg-Watanabe UX team requested to change all the mentions of word "scheme" and change it to "theme". in this [commit](https://github.com/Office-of-Digital-Services/California-State-Web-Template/pull/537) I did that. So, now file names and paths changed

**Comment by kkoryaka** [comment]
@Greg-Watanabe  after you are done assign it to @sharon-rabang and @ashleydraper for content update

**Comment by sharon-rabang** [comment]
@Greg-Watanabe These prototype pages are ready for dev in Figma:
- [Colors](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A4466)
- [Color themes - Delta](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A4250)
Please let us know if we can help with any questions. Thanks!

**Comment by sharon-rabang** [comment]
@Greg-Watanabe FYI, the same Color page and color theme page comments are in [#280 Create Visual Design landing page that will combine content from Type, Colors, and Icons pages](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/280).

**Comment by yesenia-gtz** [comment]
@Greg-Watanabe To be completed by Beta release 11/4

**Comment by sharon-rabang** [comment]
10.14.22: Met and agreed to keep the header colors light and use a gray search bar. @sharon-rabang will update all of the headers and screenshots of the headers in Figma.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe FYI - The heading banner colors have been updated and are ready for dev.

Please go to the Figma page for reference: V6 State Web Template official - [V6 design components](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A3187)
Let me know if I missed anything, thanks!

**Comment by Greg-Watanabe** [comment]
I see two pages of headings on that figma, which one am I supposed to use?

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Figma: [Settings banner colors](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=345%3A8786)

**Comment by Greg-Watanabe** [comment]
I don't see the site-settings background colors in the themes. Are they derived from one of the existing colors or do I need to add them as entirely new colors?

**Comment by sharon-rabang** [comment]
@Greg-Watanabe I worked with @kkoryaka to create new colors to add.

**Comment by Greg-Watanabe** [comment]
This is done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/color.html
@sharon-rabang

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks! Here are some design fixes to make:
- Colors page: 
-- Add a color theme section: Fix the first bullet with "Change the primary and secondary theme color variables in the SASS file (/src/scss/colortheme/oceanside.scss).
- Color themes page:
-- Swatches: I revised the design on the Figma [Color themes](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A4250) page to make the round color swatches visually center over the left-aligned text specs better. Can this section be set up in a card-like way (like in Figma) to  keep each swatch with its specs, especially for mobile view?
- Samples section, light and dark backgrounds:
-- 'Link grid' heading; Change to sentence case
-- Update the link grid examples with the revised one in Figma

**Comment by Greg-Watanabe** [comment]
@sharon-rabang  
This is done. 
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/color.html

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks! Here are some more design fixes to make: 
- Colors page:
-- Add a color theme section: Delete the extra sentence from the first bullet: "Instructions can be found in the readme file."
-- Add another line of white space between the Color themes content and the cards as shown in Figma.
- Color themes page:
-- Swatches, Samples section - dark backgrounds: Update the link grid example with the revised one in Figma (with white type and outlines)

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/color.html

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good to go, thanks!
