### ISSUE TITLE
Content design for Get Started landing page

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#517]
Make sure that correct content is  applied  to the Get Started landing page

Current page in beta staging:
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/getting-started.html

Word document:
https://docs.google.com/document/d/1UyvomMQRZ5PfFrH-mbmr6ZsVLR-nkQCkPJofrUcaocQ/edit#heading=h.5z0l3zdnl9il

**Comment by kkoryaka** [comment]
@ashleydraper please check if this is the right content for this page because figma design proposal looks kind of different: https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=18%3A3630

**Comment by extinah** [comment]
Be sure to include links to the packages in github (download links)

**Comment by extinah** [comment]
Step list only preview the eleventy framework

**Comment by extinah** [comment]
Konstantin and Art reviewed and provided feedback. New page needs to be created in figma. @sharon-rabang  @hamiltonryan  can one of you work on it? i'm finalizing the get started page now.

Download and setup
https://docs.google.com/document/d/1A--CplY-8qepW4dG_jG0Bdg-eiDgqZ5RQgt7lD8jVPo/edit?usp=sharing

**Comment by sharon-rabang** [comment]
@extinah @hamiltonryan I can help work on this.

**Comment by extinah** [comment]
@artuoma  @kkoryaka  Ready for your review:
https://docs.google.com/document/d/18lrNAan6a05MHQWIb3K_Kp-fHVPA_E0feOWmocav4ts/edit#

Will also send to you in teams.

**Comment by extinah** [comment]
@sharon-rabang  - updated content. Thanks. 
https://docs.google.com/document/d/18lrNAan6a05MHQWIb3K_Kp-fHVPA_E0feOWmocav4ts/edit#

**Comment by extinah** [comment]
@kkoryaka 
Content is ready. Working on the images for the cards, but otherwise design is also ready.
content: https://docs.google.com/document/d/18lrNAan6a05MHQWIb3K_Kp-fHVPA_E0feOWmocav4ts/edit#
figma: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=553%3A10414

**Comment by sharon-rabang** [comment]
@kkoryaka Images for the cards are ready for dev.

**Comment by kkoryaka** [comment]
@sharon-rabang  please review https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/get-started.html

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
