### ISSUE TITLE
404 error page

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#518]
Create 404 error page

**Comment by sharon-rabang** [comment]
@ashleydraper The Figma page has been created: [404 error page](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=1304%3A6923l) Please add the popular links when they're available. thanks!

**Comment by ashleydraper** [comment]
Sharing the **[404 error page](https://docs.google.com/document/d/14XT0Ox8lQ1Xv1ImGWWDmBikudbaAGsnPhWlElNtkxJU/edit)** google doc. @sharon-rabang

**Comment by ashleydraper** [comment]
The [**404 error page**](https://docs.google.com/document/d/14XT0Ox8lQ1Xv1ImGWWDmBikudbaAGsnPhWlElNtkxJU/edit) is ready for review.

**Comment by extinah** [comment]
My review is done. Minor edits.
Ready for @artuoma

**Comment by Angsv** [comment]
[404 error page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=150%3A5281) is ready for review. I've attached the SVG file to this comment, if you need the original Illustrator file or another format, let me know.
![polygon_bear_hard_hat](https://user-images.githubusercontent.com/95935944/195731448-e675b98f-2b2d-4a86-b9d2-82b0a4fd92c9.svg)

**Comment by ashleydraper** [comment]
Looks great @Angsv! Thank you!

@kkoryaka This is ready for dev. Here are the content and design links you'll need:
- [Figma wireframe](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=150%3A5281)
- [Google staging doc](https://docs.google.com/document/d/14XT0Ox8lQ1Xv1ImGWWDmBikudbaAGsnPhWlElNtkxJU/edit)

**Comment by yesenia-gtz** [comment]
To be completed by Beta release 11/4

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/404.html

**Comment by sharon-rabang** [comment]
@kkoryaka The text sizes look better, thanks! 
One last thing - is the sitemap link supposed to continue to be on this page, if it's not going to webpage?

**Comment by kkoryaka** [comment]
@sharon-rabang unless we want to make public facing sitemap page. But sitemaps are meant for search engines.

**Comment by sharon-rabang** [comment]
@kkoryaka We will create a public facing sitemap page with [#649](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/649).
 Will update this 404 page's sitemap link, and also add it to the footer, when the sitemap page is ready.

**Comment by kkoryaka** [comment]
@sharon-rabang I have updated sitemap link: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/404.html

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
