### ISSUE TITLE
Site map

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#519]
Create a site map page and link in footer.

**Comment by sharon-rabang** [comment]
@ashleydraper The Figma page has been created: [Sitemap](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=1339%3A6285) Please update the links when they're ready. Thanks!

**Comment by sharon-rabang** [comment]
@kkoryaka The link you provided isn't working for me.

**Comment by kkoryaka** [comment]
@sharon-rabang does it downloading something? You should see this.
![Screen Shot 2022-10-20 at 1 26 50 PM](https://user-images.githubusercontent.com/31669748/197051301-c89e9b1c-fe00-42f2-ac94-8919f5653fda.png)

**Comment by sharon-rabang** [comment]
@kkoryaka It does - thanks for the screenshot. Is this information meant to update this page in Figma and then become a link in the footer after the 'Accessibility' link? [Sitemap](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A7039)

**Comment by kkoryaka** [comment]
@sharon-rabang  No need to update it in figma. We already have those URLs in our spreadsheet. i will close it out
