### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#520]
Create favicon and test in different browsers.

**Comment by artuoma** [comment]
@artuoma sounds good to me - moving to UX

**Comment by sharon-rabang** [comment]
Assigned to @hamiltonryan

**Comment by extinah** [comment]
@yesenia-gtz  this can be moved to the dec release

**Comment by yesenia-gtz** [comment]
Milestone updated for Production release Dec 16

**Comment by yesenia-gtz** [comment]
@hamiltonryan  updated assignment to you, I didn't realize you weren't added to project board, apologies for that.

**Comment by hamiltonryan** [comment]
No problem, thankfully I could still see and and work on the items, I was going to ask you after your training today, so that worked out well

**Comment by hamiltonryan** [comment]
@kkoryaka The favicon is ready to go. Do you want that in a PNG or SVG, and where would the best place to post that for you be?

**Comment by hamiltonryan** [comment]
https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=312%3A8207

**Comment by yesenia-gtz** [comment]
@kkoryaka assigning to you to delegate to engineering as appropriate.

**Comment by kkoryaka** [comment]
@sharon-rabang i have updated favicon to this one. (make sure you do couple of good hard refreshes to see it)
![favion](https://user-images.githubusercontent.com/31669748/196781169-c672410f-b5ec-4133-965c-c515001723f6.png)

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! I made revisions - please replace with this updated version: [V6 favicon](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=312%3A8207)

**Comment by kkoryaka** [comment]
@sharon-rabang icons is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good, thanks!
