### ISSUE TITLE
Project Specifications

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#522]
Project Spec doc for Web Template website UX presentation/mapping.

Link to doc: [Project Specifications for V6 State Web Template Website](https://coda.io/d/State-Web-Template_dWUrhoQSm6T/Project-Specifications-for-V6-State-Web-Template_suxO-#V6-State-Web-Template-Pages_tuC0R/_rui-KSE6rVhRu1)

**Comment by sharon-rabang** [comment]
Met with Angelina about what this documentation entails and its level of effort at this stage of the project. 
Continuing to document our notes and guidelines for Dev in Figma would be better, based on our resources who can help us prioritize our visual design and content needs. 
Will keep issue open for now, in case we have another resource who can work on this.

**Comment by sharon-rabang** [comment]
@extinah Here are the items we have documented so far:
- Contact us form
- Icons
- Page navigation
- Pagination - Basic
- Side navigation
- Homepage

**Comment by sharon-rabang** [comment]
@artuoma @extinah @kkoryaka These specs were shared at today's stand-up and are ready for lead review. 
Note: Will continue to make updates, as needed.

**Comment by extinah** [comment]
@sharon-rabang I think we can mark this as done and just continue to update as we go along.

**Comment by sharon-rabang** [comment]
@extinah Sounds good, thanks!
