### ISSUE TITLE
Site footer redesign

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#523]
Discuss Site footer redesign for review and approval. Here's the [Figma prototype](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=1288%3A7778)

**Comment by sharon-rabang** [comment]
@ashleydraper Should this start with and go through internal review with Art and Christina?

**Comment by artuoma** [comment]
Looks good - should back to top be on the right so its easier to get to in mobile with a thumb?
![image](https://user-images.githubusercontent.com/20782462/194962620-72c8a402-1c91-44d5-b2fe-5e9130d0ba27.png)

**Comment by sharon-rabang** [comment]
@artuoma Good catch! We deleted 'Back to top' from the footer. Thanks!

**Comment by yesenia-gtz** [comment]
To be completed by Beta release 11/4

**Comment by ashleydraper** [comment]
@kkoryaka Tracking progress in #525, remove "contact us" link from footer.

**Comment by kkoryaka** [comment]
@artuoma this we have to keep, because this footer will be consumed by CAWeb. And in CAWeb options they have social icons in the footer (and it's the only place to put social media Icons in CAWeb because we took them away from the header). That is why I kept this layout. Unless you want me to ignore CAWeb. Remember that in v6 we are trying to preserve the structure and adding DS look and feel to it.

**Comment by kkoryaka** [comment]
@sharon-rabang I have added the site footer also, see my comments above to Artem about footer layout.

**Comment by sharon-rabang** [comment]
@kkoryaka @artuoma Thanks! Here's are some design fixes to make:

1. Change More on V6 to State Web Template
2. Change links to white text
3. Change CA.gov logo colors to be consistent with the Design System (Ca = yellow, .gov = blue)
4. Thanks for explaining the footer limitations. If we must keep within the CaWeb footer limitations, can the Copyright info be right-aligned beneath the GitHub social media icon?
![image](https://user-images.githubusercontent.com/99768807/196728032-fc5d3f00-030f-47ba-9ce4-57e5a35b84e2.png)

**Comment by kkoryaka** [comment]
@sharon-rabang will do items 1, 3 and 4. But as far as #2 go please make sure you do hard refresh because sometimes old css sits in your cache

**Comment by kkoryaka** [comment]
@sharon-rabang this should be updated now. please review.

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good, thanks!

**Comment by sharon-rabang** [comment]
@yesenia-gtz Yes, thanks!
