### ISSUE TITLE
Create About page

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#524]
Create an About page for the state template and track copy edits in [this google document](https://docs.google.com/document/d/1lzx-s0uAgfjEJ09atcSN6_s2XwP4N6VSGpyZ6P70MvQ/edit#heading=h.icjnc3foamvi).

**Comment by ashleydraper** [comment]
@artuoma @extinah Not super satisfied with this draft, but I don't want to hold this any longer. 
Please review the [**About page**](https://docs.google.com/document/d/1lzx-s0uAgfjEJ09atcSN6_s2XwP4N6VSGpyZ6P70MvQ/edit#) as soon as you can and fill in the holes I've highlighted with any insight  you have.

**Comment by kkoryaka** [comment]
@artuoma assigning it to you

**Comment by yesenia-gtz** [comment]
@artuoma have you reviewed https://docs.google.com/document/d/1lzx-s0uAgfjEJ09atcSN6_s2XwP4N6VSGpyZ6P70MvQ/edit? Can this be completed today?

**Comment by artuoma** [comment]
Done with my edits - please review!

**Comment by yesenia-gtz** [comment]
@ashleydraper  About page content updated. @sharon-rabang does this need to be added to figma designs?

**Comment by sharon-rabang** [comment]
@yesenia-gtz Yes, I'll add it to Figma, thanks!

**Comment by sharon-rabang** [comment]
The About page is now in Figma: [About](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=718%3A10947)

**Comment by extinah** [comment]
@sharon-rabang I made minor edits to the history section to tighten it up a little bit.
Reminder to assign to dev when ready. thanks!

**Comment by sharon-rabang** [comment]
@kkoryaka The About page is ready for dev.

- [About ](https://docs.google.com/document/d/1lzx-s0uAgfjEJ09atcSN6_s2XwP4N6VSGpyZ6P70MvQ/edit)- google doc
- [About](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=718%3A10947) - Figma

**Comment by kkoryaka** [comment]
@sharon-rabang this page is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
