### ISSUE TITLE
Create Contact Us page

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#525]
Create a Contact Us page for the state template and track copy edits in [this google doc](https://docs.google.com/document/d/1pGl4gHz1IX8Kn94GQXWUzbHGInjf5f-c08TejsBlquc/edit).

Figma links: [Contact us](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=471%3A8653) | [Contact us error messages](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=471%3A9101)

**Comment by extinah** [comment]
Looks good to me. 
@artuoma

**Comment by kkoryaka** [comment]
@ashleydraper what roles option should we include in the select box?
![Screen Shot 2022-10-11 at 12 42 34 PM](https://user-images.githubusercontent.com/31669748/195184084-8297e96d-a380-4feb-b2c6-8159256a0e12.png)

**Comment by kkoryaka** [comment]
@carterm could you add azure post service to this one?

**Comment by ashleydraper** [comment]
@kkoryaka Let use this list:

- Analytics 
- Content
- Design
- Development
- Product
- Program
- Research
- Other

**Comment by yesenia-gtz** [comment]
@carterm I have invited you to the OET research Airtable account for testing and configuration. Please let me know if you need further access or if you run into issues with your research.

https://airtable.com/appu01tGlmTTMm5uX/tblN7oCcLMOSPvbM6/viwBA9aiJfgaPQzga?blocks=hide

cc @artuoma @kkoryaka @ashleydraper

**Comment by yesenia-gtz** [comment]
@carterm See below for form setup in airtable. I added the field values to the table for you and a link to review Design System feedback form configuration here: https://airtable.com/app4B5KqaCTSHAdCS/tbliV5kSgz7jBnIyT/viwDkwTUo3wZOqYhF?blocks=hide

**State Template contact form responses**

![Screen Shot 2022-10-20 at 8 01 33 AM](https://user-images.githubusercontent.com/98193284/196985502-e687b29b-126c-41f2-942d-5b3b7028c9cd.png)

![Screen Shot 2022-10-20 at 8 00 46 AM](https://user-images.githubusercontent.com/98193284/196985526-4f1b88c8-cdc0-4d2b-b3d4-03ba81cf83dc.png)

**Review Design System feedback form configuration**

![Screen Shot 2022-10-20 at 8 00 28 AM](https://user-images.githubusercontent.com/98193284/196985536-22d2939d-3965-4cb0-995c-8fb56c0d1595.png)


cc @kkoryaka @artuoma  @extinah

**Comment by yesenia-gtz** [comment]
@carterm bummer, it is a link to the screenshot I attached for **Review Design System feedback form configuration**. just wanted to show you what was done in the Automations area of airtable.. you should be able to do that in our database.

**Comment by yesenia-gtz** [comment]
@extinah @sharon-rabang  is there a design for the contact page ? are we using a generic form layout for this?

**Comment by ashleydraper** [comment]
@yesenia-gtz It existed on the last board, I just copied it to our new environment. Here's the [**contact us**](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=431%3A8229) design from Courtney. Sharon may want to redesign.

**Comment by sharon-rabang** [comment]
@yesenia-gtz @ashleydraper @extinah Here is the redesigned form in Figma: [Contact us](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=471%3A8653) | [Contact us error messages](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=471%3A9101)
Please let me know if we'll need to make any changes. Thanks!

**Comment by yesenia-gtz** [comment]
@hamiltonryan @artuoma @kkoryaka @extinah should we include a section for Department in the contact form? Would be great to know who is reaching out to keep track of interested persons.

**Comment by kkoryaka** [comment]
@yesenia-gtz Carter asked to move this item to production release date instead of Nov 4, because a lot of research involved.

**Comment by yesenia-gtz** [comment]
Moved to production release

**Comment by extinah** [comment]
Updated the word doc to include a section for department.... then saw this was moved to production release. Heads up.

https://docs.google.com/document/d/1pGl4gHz1IX8Kn94GQXWUzbHGInjf5f-c08TejsBlquc/edit

**Comment by extinah** [comment]
> @hamiltonryan @artuoma @kkoryaka @extinah should we include a section for Department in the contact form? Would be great to know who is reaching out to keep track of interested persons.

I think we should do this.

**Comment by carterm** [comment]
Meeting with DevSecOps to set up Azure environment to run the Contact Us service.

**Comment by carterm** [comment]
This is the service created to support the data flow.

https://github.com/Office-of-Digital-Services/cagov-form-post-service

**Comment by carterm** [comment]
Working with DevSecOps to set up the environment. It's a first time setting up an Azure Function with the current pipelines.  Working through it, we got the service running, but they will need to recreate some Azure components for the final setup that won't be done until after Thanksgiving.

**Comment by carterm** [comment]
PR for working release...
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/878

**Comment by carterm** [comment]
deployed to staging.

https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/contact-us-form.html

**Comment by yesenia-gtz** [comment]
@carterm OK to move to UX design review?

**Comment by carterm** [comment]
Added cosmetic updates to better match Figma design...
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/879

**Comment by carterm** [comment]
@yesenia-gtz - deploying one more update.  I'll let you know.

**Comment by carterm** [comment]
Ok staging is ready for UX review.

**Comment by yesenia-gtz** [comment]
@extinah ready for ya!

**Comment by carterm** [comment]
Do we have CSS styling for HTML5 "required" fields?  The Figma design has glyphs etc, but that sort of convention *should probably be* included in the global CSS.

```
<style type="text/css">

  input:required:invalid, input:focus:invalid {
    background-image: url(/images/invalid.png);
    background-position: right top;
    background-repeat: no-repeat;
  }
  input:required:valid {
    background-image: url(/images/valid.png);
    background-position: right top;
    background-repeat: no-repeat;
  }

</style>
```

**Comment by carterm** [comment]
Also, our convention has Required "*" in front of the label, and a "This field is required" label warning below, without entry instructions.  In keeping with the convention, I went with what was on our form elements page.

https://beta.template.webstandards.ca.gov/components/form-elements.html

**Comment by carterm** [comment]
"Instructional, error messages, and placeholder text should not provide the same message as the label."

**Comment by extinah** [comment]
We should specs for interactions here. We'll try to get that to you sooner than later.

**Comment by carterm** [comment]
Adding accessibility update...
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/880

**Comment by carterm** [comment]
Validators don't display until first submit attempt.
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/883

**Comment by extinah** [comment]
@carterm  here's some initial QA. NICELY DONE by the way. Yay :)

@sharon-rabang @ashleydraper  can you both help finalize QA next week?

QA
Only these two fields are required (name and email) per the design. I'm suggesting we make "How can we help" required, too. 
1. Your name
2. Email
3. How can we help?

**Error messages if not submitting a required field:**
Name: Enter your name.
Email: Enter your email
How can we help?: Provide information about why you're contacting us.


**Main role**
This needs the drop down carrot to display when not selected. Also the drop down interaction should look more like the design.

Design
![image](https://user-images.githubusercontent.com/33840424/205414687-ce1b2b38-fc0b-4b1c-ad1a-2ef2af10eaa4.png)

In dev:
unselected:
![image](https://user-images.githubusercontent.com/33840424/205414714-c6df3d3d-4060-40e3-aa97-4e33da01c8ca.png)
Selected:
![image](https://user-images.githubusercontent.com/33840424/205414730-a17a2d1c-df4a-4dff-a9cf-12504ffe8835.png)

**Comment by carterm** [comment]
I can certainly change the required fields.

I'm not sure I understand the problem with the "Main role" selection.  It has a dropdown of suggested items, with the ability to type anything instead of selecting other.  Also, the screen reader support correctly describes the field as allowing in-line or list selection. 

The AirTable data design only has one field for "Role", no "Other" catch field.

I could limit the "Main role" selection to the list and then have a secondary field in for a "other" type in, but that appears confusing and redundant in my opinion.

**Comment by carterm** [comment]
Changing field width to less that 100%
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/896

**Comment by sharon-rabang** [comment]
@carterm Thanks for making the field adjustments! To help you follow @extinah's initial QA comments above, here are the related design specs and callouts. Please make these design fixes to match the Figma prototype: [Contact us error messages](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=471%3A9101&t=EP7PTQGcVYldMTFG-1)
![image](https://user-images.githubusercontent.com/99768807/206254376-cc8a24be-9018-4c02-9b45-667c91639280.png)
Let us know if we can help with any questions and when the updates are ready for UX review, thanks!

**Comment by carterm** [comment]
@kkoryaka Any idea on what css classes to change to make this work?

**Comment by carterm** [comment]
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/901

**Comment by carterm** [comment]
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/911

**Comment by carterm** [comment]
Adding captcha support...https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/920

**Comment by extinah** [comment]
@sharon-rabang: The design is a little wrong - only 3 fields are required. The other ones (main role, department) shouldn't have error messages. The only one is maybe for department if they put in something into the field they shouldn't or there's too many characters. We can chat more about the specs later today (I'll call you). 
cc: @carterm

**Comment by extinah** [comment]
Per our team sync this morning:
@ashleydraper will work on the confirmation page text. When drafted, send to Kon, Art, and myself for review. When approved, I'll add it to figma and then let carter/devs know.

I (@extinah) will work on the form details (error messages, field details, etc). Will work with UX team for input, and then @carterm  and @kkoryaka for initial dev feedback. Then a quick review with Kon and @artuoma .

cc: @yesenia-gtz

**Comment by ashleydraper** [comment]
Looking like a meeting is not necessary. Team agreed to use main contact us page to house the form.

**Comment by ashleydraper** [comment]
@carterm Here is the content for the [submitted feedback form}](https://docs.google.com/document/d/1ULqSoV4C8uXOyIp58NfyVZZ0uWuMn1sThxf1VJUmn_4/edit#).

**Comment by ashleydraper** [comment]
We are deleting the current contact page (pictured) and replacing with content in this [contact us doc](https://docs.google.com/document/d/1pGl4gHz1IX8Kn94GQXWUzbHGInjf5f-c08TejsBlquc/edit#). See edits in the document.

![image](https://user-images.githubusercontent.com/62437425/207736747-3f94d66f-2079-4ffa-85df-f7416f9cacb0.png)

**Comment by carterm** [comment]
- Adding min/max length to fields.  https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1020
- Adding server validation for fields https://github.com/Office-of-Digital-Services/cagov-form-post-service/pull/1

**Comment by ashleydraper** [comment]
The [contact us page](https://docs.google.com/document/d/1pGl4gHz1IX8Kn94GQXWUzbHGInjf5f-c08TejsBlquc/edit#heading=h.awie9g64g5ze) is ready for review. Sending to leads.

**Comment by extinah** [comment]
I made one small comment. Approved by me, thanks.

**Comment by yesenia-gtz** [comment]
@ashleydraper @extinah my review is complete, no additional feedback. Thank you!

**Comment by extinah** [comment]
@rkojik When this next update is completed, can Greg test this page for accessibility (specifically with a screen reader)?

**Comment by extinah** [comment]
We met on form handling, errors, and design today. Once the updates are done, we'll contact the developers on here.

**Comment by ashleydraper** [comment]
Review is complete. @carterm updates are in the [contact us doc](https://docs.google.com/document/d/1pGl4gHz1IX8Kn94GQXWUzbHGInjf5f-c08TejsBlquc/edit).

**Comment by extinah** [comment]
We'll need to do more desk research into the combo box post release for best practices, etc (no time right now). Created this backlog item (and possibly add to forms elements). #1058

**Comment by sharon-rabang** [comment]
> We met on form handling, errors, and design today. Once the updates are done, we'll contact the developers on here.

**Design:**
@kkoryaka @carterm Please start making the suggested design changes by referring to the Figma [Contact us form error messages - Design specs](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2333%3A18702). We'll let you know when they're listed and organized better in the [Project Specifications for V6 State Web Template](https://coda.io/d/State-Web-Template_dWUrhoQSm6T/Project-Specifications-for-V6-State-Web-Template_suxO-#V6-State-Web-Template-Pages_tuC0R/r201). 

Here's the initial list of tasks for UX design fixes:
**Dev design fixes**
1. [Contact us](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/contact-us-form.html) form webpage
- [ ] Asterisks: Move placement
- [ ] Combo box: Use the same caret styling as the dropdown component
2. Forms elements and Forms elements webpage 
- [ ] Asterisks (New GitHub issues coming soon):
  - [ ] Forms element: Move placement
  - [ ] Forms webpage: Update “Text field or text area” examples
- [ ] Dropdown menu (New GitHub issues coming soon):
  - [ ] Forms element: Remove corner radius from text field box for consistency
  - [ ] Forms webpage: Update “Dropdown menu” example

**UX team tasks:**
- [ ] Add Figma [Contact us form error messages - Design specs](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2333%3A18702) to the [Project Specifications for V6 State Web Template](https://coda.io/d/State-Web-Template_dWUrhoQSm6T/Project-Specifications-for-V6-State-Web-Template_suxO-#V6-State-Web-Template-Pages_tuC0R/r201)
- [ ] Update Figma: Forms elements prototype page with the related Contact us form design changes
  - [ ] Add combo box to page content in next release
- [ ] Create new GitHub issues for 
  - [ ] Forms elements updates
  - [ ] Forms elements webpage update

@extinah Please edit or add anything I missed, thanks!

**Comment by extinah** [comment]
We will document any form element changes that come out of this git issue.
https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/1068

**Comment by extinah** [comment]
@carterm 
In addition to the figma doc, added the specs in coda for Contact us. The form field width still needs some fine tuning, but hopefully what we have works out for now. ALSO this is exciting when we work on form elements :)

https://coda.io/d/State-Web-Template_dWUrhoQSm6T/Project-Specifications-for-V6-State-Web-Template_suxO-#V6-State-Web-Template-Pages_tuC0R

cc: @kkoryaka @yesenia-gtz  @sharon-rabang @rkojik @artuoma

**Comment by extinah** [comment]
Created two issues:
- forms elements webpage: https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/1068
- form elements updates (to the actual item): https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/1080

**Comment by kkoryaka** [comment]
@extinah page are now updated https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/contact-us.html
(old contact page is removed)

**Comment by extinah** [comment]
@sharon-rabang also for your review. thanks.

**Comment by extinah** [comment]
Note: We were interested in the cursor being in the form field and if this affects accessibility.

Pia ran it through the screen reader today and there is no issue - it read the conent before the form field.

**Comment by extinah** [comment]
QA edits - review image below to help.

- [ ] Error banner (top of page)
    - [ ] Make the font SemiBold
    - [ ] Vertically center in the container

- [ ] For the email error message, update the email address to: name@email.com
- [ ] Main role: change to drop down for now. add "Other" option. We will try to make the combo box work in 6.1.1
- [ ] How can we help: add in the error message if it is blank. Provide information about why you're contacting us.

**Comment by kkoryaka** [comment]
@sharon-rabang @extinah please reveiw it again

**Comment by extinah** [comment]
This looks good to me. How about you, @sharon-rabang?

**Comment by sharon-rabang** [comment]
@kkoryaka @extinah Looks good to go, thanks!
