### ISSUE TITLE
Header: Settings banner and Search bar/banner designs

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#568]
@kkoryaka The settings banner design and the search bar/banner designs are ready for dev.

Please go to the Figma page for reference: V6 State Web Template official - [V6 components](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A3187)
Let me know if I can help with any questions or concerns. Thanks!

**Comment by kkoryaka** [comment]
@sharon-rabang and @kkoryaka & @artuoma will meet and collaborate on those.

**Comment by sharon-rabang** [comment]
10.14.22: Met and agreed to keep the header colors light and use a gray search bar. @sharon-rabang will update all of the headers and screenshots of the headers in Figma.

**Comment by sharon-rabang** [comment]
@kkoryaka The heading settings banner colors have been updated and are ready for dev.

Please go to the Figma page for reference: V6 State Web Template official - [V6 design components](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A3187)
Let me know if I missed anything, thanks!

**Comment by sharon-rabang** [comment]
Figma: [Settings banner colors](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=345%3A8786)

**Comment by kkoryaka** [comment]
@sharon-rabang I have updated the settings bar and search colors. Please review

**Comment by sharon-rabang** [comment]
@kkoryaka How exciting, thanks! 

Looking good! Here's are some design fixes to make:
**Settings bar design**
- Extra borders: Remove the gray borders/lines above and below the settings banner.
- Buttons: 
-- Text: Change to use sentence case. Example: "High contrast"
-- Spacing: Add more space between the buttons if the spaces aren't at least 12px like in Figma
- "x" icon: Reduce size to the text height of the lower case text in the buttons like in Figma
- Color themes:
-- V6 site: Apply the Oceanside settings banner color #D1ECF4
-- Paso Robles: Apply settings banner color #e3e3e3
-- Sacramento: Apply settings banner color #c5daef

**[Search banner](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=376%3A8559) design**:
- Remove the breadcrumbs
- Search bar: Change to use the same search bar design and color displayed in the Site header for consistency. Here's the design in Figma: [Search banner](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=376%3A8559)

**Comment by kkoryaka** [comment]
@sharon-rabang i have updated the settings bar, and search bar on the serp page: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/serp.html?q=examples

Also, i have updated breadcrumbs look.

**Comment by sharon-rabang** [comment]
@kkoryaka Great, thanks! Here are a couple more design fixes to make:

- Settings bar, last button label: Use lowercase 'f' in "Dyslexic font"
- serp.html Search bar border/outline: Add a 5px corner radius to the top and bottom corners of the left side for consistency.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/serp.html?q=examples

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
