### ISSUE TITLE
Social media share image

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#577]
Create Teams share image

- Specs: 1200px-x-627px
- Name: California State Web Template
- Draft content: (TBD)
- Teams uses the meta tag:
<meta property="og:image" content="[http://www.yourdomain.com/image-name.jpg"](http://www.yourdomain.com/image-name.jpg%22)

**Comment by sharon-rabang** [comment]
Assigned to @hamiltonryan

**Comment by hamiltonryan** [comment]
@Greg-Watanabe The share image is ready to go.  Do you need a PNG or SVG of that, and where would you like me to share that?

**Comment by hamiltonryan** [comment]
https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=312%3A8208

**Comment by Greg-Watanabe** [comment]
This is done.
Note that the meta tag requires the full path to the image, so it will need to be updated when the site is moved to a different domain name.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks! Can you provide us with a screenshot of how it displays in Teams, so we can review the design and content for edits? (When you and I were testing for this for ODP, I was having issues with clearing my cache to see our latest version in Teams.)

**Comment by Greg-Watanabe** [comment]
![image](https://user-images.githubusercontent.com/24966826/197061724-7b46ec03-933f-43d1-88c0-d82ce969024b.png)

Here it is ... Try posting the url of a page you haven't posted before, then it might fetch the new image.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe The image looks great, thanks! As for content, is it set to display "California State Web Template" when we're ready to share the official link?

**Comment by Greg-Watanabe** [comment]
The content comes from the title tag and the description meta tag

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Great, thanks! We can keep this issue open until its time to update the meta tag with the required full path to the image, when the site is moved to a different domain name.

**Comment by kkoryaka** [comment]
@Greg-Watanabe place image into CDN directory instead

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
Image has been moved to the CDN
https://california.azureedge.net/cdt/statetemplate/global/images/social_media_preview_image.png

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good to go, thanks! Will close this issue.
