### ISSUE TITLE
Side navigation (component)

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#587]
To be included in December production release as part of [Update structure landing page to include structural components samples and code](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/306):

- [ ] [Side navigation](https://docs.google.com/document/d/1hN7vXwYNvhaYJ2MsLYPlPPokBBQ_6Gtrs-XZnqaIkOA/edit#)

Focus area:

- UX recommendations
- Design updates
- Content updates

Edited to add:

- [ ] When this page is up, add a link to it from the What's new page, Navigation subheading (currently not linked).

**Comment by yesenia-gtz** [comment]
FYI @artuoma @extinah @ashleydraper @kkoryaka  this item will not be available for beta release, we are aiming for Production release for completion.

**Comment by extinah** [comment]
Further refine the side nav interaction. The on page nav needs more visual hierarchy. It's confusing what is one page nav (anchor links) and what is a page link.

Example:
![image](https://user-images.githubusercontent.com/33840424/196739166-9511fcac-58e3-4fca-8836-bfe5276496c6.png)
![image](https://user-images.githubusercontent.com/33840424/196739265-ce48761d-9972-4557-b841-504268557c94.png)

**Comment by extinah** [comment]
Related to issue 223 https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/223

**Comment by sharon-rabang** [comment]
11/17-11/18: UX Team shareout of proposed "Side nav" and "On this page" designs

Reviewed and approved:
-- Both proposed designs
-- Prototypes for https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/827 Usability testing and as a live example for the [https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/587] Side nav component multi-level list
--- Will create new GitHub issue to develop this in another environment
Content updates about design and usage will be made for
-- https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/587 "Side nav component"
-- https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/831"On this page" component

**Comment by sharon-rabang** [comment]
@extinah Drafting content updates in google doc and Figma

**Comment by sharon-rabang** [comment]
@hamiltonryan Updating all Figma pages with the "Side nav" design and "On this page" design

**Comment by sharon-rabang** [comment]
In "Multi-level list" section of this Side nav component page, use an image for the example until the "live example" has been developed for it in  
[#855](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/855) Develop side navigation example pages.

**Comment by extinah** [comment]
@ashleydraper 
This is ready for a content review (before I send off to Kon/Art). Thanks!
https://docs.google.com/document/d/1hN7vXwYNvhaYJ2MsLYPlPPokBBQ_6Gtrs-XZnqaIkOA/edit?usp=sharing

- [ ] content review

**Comment by extinah** [comment]
@hamiltonryan let's finalize this in figma and move the correct workspace, if needed.

**Comment by extinah** [comment]
@artuoma  @kkoryaka  Content ready for your review/approval
https://docs.google.com/document/d/1hN7vXwYNvhaYJ2MsLYPlPPokBBQ_6Gtrs-XZnqaIkOA/edit?usp=sharing

**Comment by extinah** [comment]
Ready for content and design review and approval from Art and Kon.
@artuoma @kkoryaka

**Comment by yesenia-gtz** [comment]
@rkojik can you help with content review on this one?

**Comment by rkojik** [comment]
Added a couple comments, though none of them are showstoppers. If we have time to address the one about redundant wording, great; if not: approved.

**Comment by extinah** [comment]
Create a gif to replace existing multi-level list. 

Or walk example through with some text/steps (simple)

**Comment by hamiltonryan** [comment]
@artuoma @extinah @kkoryaka @yesenia-gtz @rkojik 

2 versions to consider. 

First is a version with labels per our discussion on Friday
https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1648%3A14570&t=iAZyo8lbYy6Vf3rh-4

Second by popular Koji demand, a GIF (not with a j) version, which is really helpful to see the progression:
https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1785%3A15780&t=iAZyo8lbYy6Vf3rh-4

[Here is the GIF location](https://stateca.sharepoint.com/:i:/r/sites/statewideinnovation/Shared%20Documents/Design%20Assets/V6%20State%20Web%20Template/V6%20imagery/Side%20Navigation/[SampleGif-Cursor2.gif](https://stateca.sharepoint.com/:i:/r/sites/statewideinnovation/Shared%20Documents/Design%20Assets/V6%20State%20Web%20Template/V6%20imagery/Side%20Navigation/SampleGif-Cursor2.gif?csf=1&web=1&e=TChncV)?csf=1&web=1&e=TChncV)

**Comment by yesenia-gtz** [comment]
Thank you @hamiltonryan ! can we go with the GIF for production release as a placeholder while the team works on the live example?

**Comment by yesenia-gtz** [comment]
Approved to move forward with GIF for production release

**Comment by kkoryaka** [comment]
@sharon-rabang please review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/side-navigation.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some changes to make:

- Single-level list, example: Change "Section landing page" to "Page 4"
![image](https://user-images.githubusercontent.com/99768807/206519471-b705ce88-8e98-4d68-98fc-bdcd0c98e720.png)

- Multi-level list example, Level descriptions: 
-- Make these sentences. 
![image](https://user-images.githubusercontent.com/99768807/206519629-8dc55dc0-16af-4b69-9e88-7ec340d0c79f.png)
-- Thanks for improving the hover effect by adding the lighter gray bar in Gray-50 #FAFAFA!
--- Ryan will provide an updated GIF to replace this example when it's ready.

- Multi-level behavior, #1 and #2: Change the duplicate links for "Dance party" link to "Holiday party"
![image](https://user-images.githubusercontent.com/99768807/206520309-bdac756f-3ed2-4775-82dd-e9be140634d0.png)

All live examples: When you click on the links the webpage scrolls back to the top. Please remove the scrolling effect to avoid confusion.

**Comment by kkoryaka** [comment]
@sharon-rabang please review it again

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks for the updates! We discovered the need to make one more change:
- Single-level list: Include the light gray bar with the vertical yellow bar to indicate the active page
![image](https://user-images.githubusercontent.com/99768807/206571587-0ecb6e3d-d01c-4b12-8c4e-98c9a08bbe7b.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good, thanks! Will you be able to add the the Sample GIF for the multi-level side navigation example in this release?
[Sample Gif](https://stateca.sharepoint.com/:f:/r/sites/statewideinnovation/Shared%20Documents/Design%20Assets/V6%20State%20Web%20Template/V6%20imagery/Side%20Navigation?csf=1&web=1&e=dKEffQ)

**Comment by kkoryaka** [comment]
@sharon-rabang next release maybe. As far as i can see that GIF creates more confusion than help.

**Comment by sharon-rabang** [comment]
@kkoryaka The page is good to go, thanks!

Appreciate your feedback on the GIF. Will add your feedback here about keeping the Multi-level list example as is, in case the team sees a better way to display the GIF and related code in the next release.
- GIF is confusing because it seems like page 4 is acting like accordion
- When you replace example with GIF developers will not know what they are copying and what part of the navigation in the source code.
- Leave this the way it is, it is pretty clearly explained and source code are following those three examples.

**Comment by extinah** [comment]
@sharon-rabang Konstantin did mention maybe we can reconsider post launch. I think in addition to the static examples, we could include with multi-level behavior content.
