### ISSUE TITLE
Create feedback survey for beta launch

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#601]
Need a baseline survey to get feedback on Beta launch for research November 4-11

**Comment by extinah** [comment]
Per art and christina's meeting:
Google survey
•	Instructions (one page per survey)
•	Page link:
•	What did you like:
•	What needs improvement:
•	How useful is this for your department website:
•	1 - 5
•	Not useful  -  very useful
•	Comment box

**Comment by extinah** [comment]
Here's the airtable link
https://airtable.com/shro9V6ry2Cf4mpgG
And what it looks like
![image](https://user-images.githubusercontent.com/33840424/197034294-95b731ba-bcaa-4a2c-8cef-5397b2ee6e31.png)

**Comment by kkoryaka** [comment]
@hamiltonryan please work with @extinah on this one

**Comment by kkoryaka** [comment]
Link to this survey will be in alert banner

**Comment by extinah** [comment]
@hamiltonryan  the link and what it looks like is above (I had to move fast for the dwsn yesterday).

Let me know if this looks good and we can send for internal review/approval

**Comment by hamiltonryan** [comment]
I would say it looks good for now. I'll be interested to see how the per page feedback goes, but if it doesn't work we may consider a more general one later. Fingers crossed though, per page feedback would be awesome!

**Comment by yesenia-gtz** [comment]
Closing this one as survey is build out in Airtable. Team is now working on development for banner on site.
