### ISSUE TITLE
Update alert banner to link to survey - beta research

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#602]
Need simple banner to link to google survey for research purposes to get feedback from Nov 7- 11

**Comment by yesenia-gtz** [comment]
@Greg-Watanabe @extinah  please work together to style banner and configure appropriately.

**Comment by kkoryaka** [comment]
@extinah please provide content for this one

**Comment by yesenia-gtz** [comment]
Need to have this ready for Nov 4 beta launch

**Comment by extinah** [comment]
@Greg-Watanabe  @kkoryaka 
Here's the figma link. And the content.

- **Figma**: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=511%3A8649
- **Content**: [BETA] We’d love your feedback to make the template better. You have from November 4 to November 11. 
- **Button link**: https://airtable.com/shro9V6ry2Cf4mpgG

**Comment by extinah** [comment]
@artuoma can you review and approve?
![image](https://user-images.githubusercontent.com/33840424/197288303-6f884d76-498a-401b-bdc3-382f3cf5464d.png)

**Comment by kkoryaka** [comment]
@extinah  looks good to me. @Greg-Watanabe you will have to use utility classes to make it dark, because we don't have dark alert version. You might want to use alert Front Matter feature if this alert will be on the home page only. If it's going to be site wide use the structural includes as shown below
![Screen Shot 2022-10-21 at 4 13 17 PM](https://user-images.githubusercontent.com/31669748/197303812-c2fc1aea-9f9e-4d36-b73e-7923a18b5b3a.png)

**Comment by yesenia-gtz** [comment]
@Greg-Watanabe this is ready for dev

**Comment by Greg-Watanabe** [comment]
@extinah 
Do you want the banner to appear sitewide or only on the homepage. And do you want a "X" button to close the banner? I don't see one in the figma.

**Comment by extinah** [comment]
Hi @Greg-Watanabe 
Sitewide please.

No X - since this is beta, we want it to just stay there. :)

Thanks!

**Comment by Greg-Watanabe** [comment]
@extinah 
This is done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/

**Comment by Greg-Watanabe** [comment]
Reduced the font size as requested by @sharon-rabang 
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Almost there, thanks! 

Here are a few moew design adjustments to make: 
- Increase the alert banners height
- Vertically centered all the elements to visually align like ODP's.

Here's how they compare, for reference:
![image](https://user-images.githubusercontent.com/99768807/198754146-5107c673-3b6b-41ad-bcb1-9f50736661e8.png)
![image](https://user-images.githubusercontent.com/99768807/198754153-085c5397-36c2-4a81-a0ff-b74f57f16535.png)

**Comment by Greg-Watanabe** [comment]
@sharon-rabang @extinah 
This is done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks for making the adjustments! Sorry, this will need to be updated again after we address [#761](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/761) Alerts - rework design.

**Comment by yesenia-gtz** [comment]
Moving into UX in progress until updated design is ready for dev.

**Comment by yesenia-gtz** [comment]
Task for beta release is done. New issue for redesign here https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/761

**Comment by extinah** [comment]
@yesenia-gtz  should we extend this a week officially and add in a contact field?

**Comment by yesenia-gtz** [comment]
@extinah Good call! 

@kkoryaka can you update the banner text to " We'd love your feedback to make the template better. You have from November 4 to November 18. "
![Screen Shot 2022-11-14 at 3 32 20 PM](https://user-images.githubusercontent.com/98193284/201789894-a321be23-72a2-4fc8-b879-34c268185b2b.png)?

@hamiltonryan @artuoma adding a week to get more feedback.

**Comment by kkoryaka** [comment]
@yesenia-gtz removed alert from the staging since we passed the due date. https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/alert.html

**Comment by sharon-rabang** [comment]
@extinah Is this issue completed and ready to close?

**Comment by sharon-rabang** [comment]
@yesenia-gtz Talking with @extinah and want to confirm that this banner should remain up, but without this sentence: "You have from November 4 to November 11." Please let us know if dev should make the change, thanks!

**Comment by yesenia-gtz** [comment]
@sharon-rabang @kkoryaka @extinah Lets keep it up! please remove the sentence referenced above. feedback is always welcome :)

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
