### ISSUE TITLE
Content update to add in framework links to get started page

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#603]
Content update to make it easy to link to the different frameworks on get started page

Example: https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/blob/master/README.md

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/98193284/196549967-963066d5-24ba-47e4-9d88-39a1c02f81eb.png)

**Comment by kkoryaka** [comment]
@artuoma work with @ashleydraper to add this section to get started page

**Comment by kkoryaka** [comment]
@we closing this page since there is another issue for it
