### ISSUE TITLE
"All components" pages in Figma

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#627]
Create ["All components"](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A1060) pages in Figma
- Add content from the google docs
- Design examples based on the Design System's use of general or basic text (Link 1, Link 2, Section 1, Section 2, etc.)

@sharon-rabang @hamiltonryan 

**All Components:**

- [x] Accordion
- [x] Alert
- [ ] #680
- [ ] #681
- [x] Button
- [ ] #691
- [ ] #408 Form elements
- [x] Horizontal separator
- [ ] #694
- [x] Modal
- [x] Number counter
- [ ] #677
- [x] Progress bar
- [x] Social media icons
- [ ] #697
- [x] Tabs
- [ ] CSS style shortcuts
- [ ] Request a component

**Comment by kkoryaka** [comment]
@yesenia-gtz please review the milestone

**Comment by yesenia-gtz** [comment]
Milestone updated. @extinah @sharon-rabang I will schedule review session with Design team to workshop how to best approach to meet production release 12/23

**Comment by hamiltonryan** [comment]
Minor issue on the Components page. The Number Counter card is out of place for some reason, and is now before Parallax in the order.

**Comment by sharon-rabang** [comment]
@hamiltonryan In Figma, I'll fix the Components landing page cards and all of the other page's side nav to ensure they're in alpha order. Thanks!
