### ISSUE TITLE
"Structural elements" pages in Figma

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#628]
Create ["Structural elements"](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A1056) pages in Figma
- Ensure all the content has been placed from the google docs
- Design examples based on the Design System's use of general or basic text (Link 1, Link 2, Section 1, Section 2, etc.)

@sharon-rabang @hamiltonryan 

Structural elements:
- [x] #682
- [x] #683
- [x] #685
- [x] #684
- [x] #686
- [ ] Side navigation (page still a work in progress)
- [x] #687

Related to #306

**Comment by yesenia-gtz** [comment]
Note that all items except Side Navigation to be ready for Beta release, Side navigation will be reviewed and updated on Production relase

**Comment by sharon-rabang** [comment]
@yesenia-gtz Thanks for going over our content review process moving forward, at today's V6 weekly meeting. 

Please take a look at the Site navigation content between these three pages for Internal/Lead review and approval. The approved content will help us ensure consistency between all three.
 
- [Site navigation - staging doc](https://docs.google.com/document/d/1do8n7bgzpuSlPqtcQRgnijS92El8--T5zcbyiqXDuIE/edit#) 
- [Site navigation - development](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/site-navigation.html)
- [Site navigation - Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=471%3A9501) page

@kkoryaka Please review all of the Structural elements page examples for accuracy in Figma: [Structure](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A1056)
Are the [Site navigation - Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=471%3A9501) page examples supposed to be screenshots or interactive?

**Comment by yesenia-gtz** [comment]
@extinah tagging you on this one. There are multiple site navigations items in [staging](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/site-navigation.html) that need to be outlined in the [content doc](https://docs.google.com/document/d/1do8n7bgzpuSlPqtcQRgnijS92El8--T5zcbyiqXDuIE/edit#heading=h.rx4gk3lhdug1) to align with content structure used in other element sections docs. 

**NOTES:**
- [Figma already aligned to content doc](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A1056)
- Staging is missing Usage and Accessibility sections from content doc
- This will need to go back to development once content is consistent in google doc

**Comment by yesenia-gtz** [comment]
@kkoryaka [Site Navigation content doc has been aligned with Figma](https://docs.google.com/document/d/1do8n7bgzpuSlPqtcQRgnijS92El8--T5zcbyiqXDuIE/edit#heading=h.rx4gk3lhdug1). Please [ensure staging](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/site-navigation.html) is aligned with content doc for consistency.

cc: @extinah @sharon-rabang @artuoma

**Comment by sharon-rabang** [comment]
> @kkoryaka [Site Navigation content doc has been aligned with Figma](https://docs.google.com/document/d/1do8n7bgzpuSlPqtcQRgnijS92El8--T5zcbyiqXDuIE/edit#heading=h.rx4gk3lhdug1). Please [ensure staging](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/site-navigation.html) is aligned with content doc for consistency.
> 
> cc: @extinah @sharon-rabang @artuoma

@kkoryaka We can track the Site navigation page on its own in [#686](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/686).

All the other tasks for creating "Structural elements" pages in Figma have been completed.

**Comment by extinah** [comment]
@sharon-rabang  heads up we added mobile controls to structural elements. Probably can be a new card?

**Comment by sharon-rabang** [comment]
@extinah The checklist above has been updated to include [#714](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/714) Mobile controls.
