### ISSUE TITLE
Create user-friendly sitemap (December)

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#649]
Create and link to a user-friendly sitemap when all or almost all of the pages have been created.

**Comment by sharon-rabang** [comment]
Use [#519](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/519) Site map, for reference.

**Comment by sharon-rabang** [comment]
When the page is ready, add a link to the 404 page and the statewide footer.

**Comment by sharon-rabang** [comment]
@extinah @kkoryaka The sitemap is ready for your review in Figma: [Sitemap](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=502%3A9146)

Please let me know if the content needs improvement. Thanks!

Here's the [#519](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/519) sitemap that was used for reference:  https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sitemap.xml

**Comment by extinah** [comment]
@sharon-rabang  @kkoryaka  I'm thinking out loud here - wanted your thoughts.

Maybe instead of two column, we keep as one column.

And then under long lists of items, we have them be two column.

Example: For visual design, the different color schemes would be two column.

Thoughts? I wouldn't make the change in figma unless y'all are good with it.

Otherwise, I think it looks good. Maybe just delete sitemap from here (or link to it if you're going to include it).

**Comment by sharon-rabang** [comment]
@extinah @kkoryaka I have to do a quick layout of your idea in Figma to help me see it better. BRB. :)

**Comment by sharon-rabang** [comment]
@extinah @kkoryaka Here's an example with Visual design in 2 columns in Figma: [Site map - option](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=535%3A10180)

Thoughts?

**Comment by kkoryaka** [comment]
@sharon-rabang looks good

**Comment by kkoryaka** [comment]
@extinah @sharon-rabang https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sitemap.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks!
@extinah I prefer the 2-column layout, as it appears in dev and Figma. 

The page looks good to go and ready to link from the footer and the 404 page. Here's the footer design in Figma: [Statewide footer](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=397%3A16117)

**Comment by extinah** [comment]
Looks good!

**Comment by kkoryaka** [comment]
@sharon-rabang I have added sitemap link to the footer.

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks for adding the footer link. Looks good to go!
