### ISSUE TITLE
Tabs (component)

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#656]
Google doc: https://docs.google.com/document/d/1M2eFfCIbwch1p6F4jWzNrwwuZOjaZX8J-dA5GlLGyJc/edit?usp=sharing
Figma: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=544%3A10193
Dev site: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/tabs.html

Created card so we can use for QA, updates, etc.

**Comment by extinah** [comment]
Hi @kkoryaka. Assign to anyone.

Minor fix - remove all periods from the bulleted items. No periods for these bulleted items.

![image](https://user-images.githubusercontent.com/33840424/197589113-a520380b-9b5e-45ac-ad72-87b3a80d7504.png)
![image](https://user-images.githubusercontent.com/33840424/197589205-c2205cb7-986d-43b2-8029-699e2ed0baa1.png)

Also, bulleted items for all accessibility pieces on the site need to have the periods removed, too.

![image](https://user-images.githubusercontent.com/33840424/197589317-15bd50a4-1a29-4e46-b6fb-33d68a0f4ccb.png)

**Comment by kkoryaka** [comment]
@extinah this is now updated https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/tabs.html

**Comment by extinah** [comment]
Looks great thanks.
