### ISSUE TITLE
CSS classes shortcuts page

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#663]
- Create CSS classes shortcuts page content in a google doc and then design in Figma. 
- Review and develop for December production release.
- Consider moving this page from Components to the **Get started** landing page (content still in progress).

Current draft:
- [CSS style shortcuts](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/css-shortcuts/css-units.html) in staging
- [CSS style shortcuts](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A5923) in Figma

**Comment by extinah** [comment]
@kkoryaka  this is ready for your review
https://docs.google.com/document/d/19DLeDVVfT_HX5H2Ub9en0KqZN74JmsewwSRB3IecfcQ/edit?usp=sharing

**Comment by extinah** [comment]
@kkoryaka @sharon-rabang 
Kon, this is pretty minor. I'll have sharon just use this content. let me know if there's anything glaring.
https://docs.google.com/document/d/19DLeDVVfT_HX5H2Ub9en0KqZN74JmsewwSRB3IecfcQ/edit#heading=h.90tdfrhlbrsg

**Comment by extinah** [comment]
@kkoryaka this is ready for dev - but for prod release. Moved to dev for your awareness. If anyone wants to start working on it, they can. Otherwise, you can move to backlog.

https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=561%3A8641

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/css-shortcuts/css-classes-shortcuts.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here's 1 change to make:
- Since the main "Get started" landing page has cards with graphics, we intentionally designed the 3 of its secondary landing pages' cards to 'not' have graphics. Please remove the graphics from the CSS classes cards and layout with 2 cards in 2 rows like in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=561%3A8641). 

FYI, If time permits we will enhance the "What's new in V6" page design to look like an extension of these secondary landing pages too before the Dec release.

**Comment by kkoryaka** [comment]
@sharon-rabang i have updated the layout. As far as side nav goes I will wait for your updated version in figma.

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! The only change to make is to remove "All components" from the left nav since this page is now part of "Get started".

**Comment by kkoryaka** [comment]
@sharon-rabang I have removed the all components link from there.

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! There's one more change to make: In the left side nav's last card link, please make it "Text accent colors" ('colors' is missing).

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/get-started/css-classes-shortcuts/text-accent-colors.html

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
