### ISSUE TITLE
Move CSS pages to Getting started section and design updates

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#669]
To do:
- [x] Need to move CSS section to get started for Beta launch
- [x] Update get started landing page
- [x] Clean up expanded CSS section post beta release
- [x] Update design in Figma

**Comment by extinah** [comment]
@sharon-rabang  the content is updated and completed and ready for design. And then dev. Thanks!

**Comment by extinah** [comment]
Kon, this is ready for dev - please:
- [ ] move the CSS shortcuts files to get started folder
- [ ] add to get started left nav

**Comment by kkoryaka** [comment]
@extinah I have updated URLs

**Comment by extinah** [comment]
@kkoryaka  this looks good. Thanks.

**Comment by extinah** [comment]
Remaining tasks: move files. consider redoing the IA diagram with all pages.

**Comment by ashleydraper** [comment]
Tracking content in the **[Get Started staging folder](https://drive.google.com/drive/folders/10Tu2ilDYJ4ei2j3whRE6RnS4zYMQcZGR?usp=share_link)**.

**Comment by extinah** [comment]
Created separate issues for each page. Will continue to work on the IA in this issue.

**Comment by ashleydraper** [comment]
These docs need review:
- [CSS classes shortcuts](https://docs.google.com/document/d/19DLeDVVfT_HX5H2Ub9en0KqZN74JmsewwSRB3IecfcQ/edit#heading=h.90tdfrhlbrsg)
- [Utility classes](https://docs.google.com/document/d/1mX673-lvXYLgOMRHRUX1ef9RXbNsBFxyz37oP2XP00k/edit#)

Cc: @extinah @kkoryaka @yesenia-gtz

**Comment by ashleydraper** [comment]
@extinah Here is the **[state template 6.0 IA](https://lucid.app/lucidchart/dd496664-627a-4e71-b330-9a10a596ea79/edit?page=0_0&invitationId=inv_52a2808a-e70d-4155-9193-5cf2aaaa3573#)**

**Comment by extinah** [comment]
Files already moved into correct folder structure. Done.
