### ISSUE TITLE
Create CDN page

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#672]
Be inspired by this:
https://template.webstandards.ca.gov/cdn.html 

Google doc: https://docs.google.com/document/d/1-MUPE-vjY9YlkYetE4pILwnypL4DsRaGYyEAgepLVsg/edit?usp=sharing

**Comment by extinah** [comment]
We don't have this page but we need one. For the production release. Should be simple. Needs to be IA.

**Comment by yesenia-gtz** [comment]
@artuoma review https://template.webstandards.ca.gov/cdn.html for content inspiration.

**Comment by yesenia-gtz** [comment]
@kkoryaka Can you take this on as @artuoma is out today? Or is there someone who can help with the content from engineering?

**Comment by yesenia-gtz** [comment]
@kkoryaka thank you for your help!

**Comment by kkoryaka** [comment]
@extinah could you review my added content, does it look fine to you? https://docs.google.com/document/d/1-MUPE-vjY9YlkYetE4pILwnypL4DsRaGYyEAgepLVsg/edit#heading=h.d1frlf22wf7b

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/cdn.html

**Comment by sharon-rabang** [comment]
@kkoryaka The updates look good, thanks! 
@kkoryaka and @artuoma: We updated the google doc and Figma to reflect the list of Web State Template links at the end of the page in dev. Please confirm that the webpage's list is the most accurate.

**Comment by sharon-rabang** [comment]
@kkoryaka and @artuoma: Thanks for all of the confirmation in Teams! The google doc, Figma, and the webpage are now aligned.

**Comment by extinah** [comment]
@kkoryaka Sorry for the late reply - i'm finally going through all my items since being sick/on vacation. Generally, the content looks good. Thanks for doing that!
