### ISSUE TITLE
Components: Parallax

### ISSUE THREAD

**Issue by hamiltonryan** [Office-of-Digital-Services/California-State-Web-Template-Website#677]
Parallax images and style have been updated in Figma, and is ready for Dev.

**Comment by hamiltonryan** [comment]
@kkoryaka Hey Konstantin, the Parallax component page has been updated in Figma, and is ready for Dev.
https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=575%3A8712

**Comment by kkoryaka** [comment]
Updated parallax. i think this image is not good as an background, because text have not enough contrast. 
![Screen Shot 2022-10-27 at 10 37 47 AM](https://user-images.githubusercontent.com/31669748/198367188-8040ae92-c7b0-4bee-b5ed-7e6e16ea30f9.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this page is updated but check the the legibility on sand image.

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks for making the update! @hamiltonryan is making some adjustments to the images, so we'll let you know when the revisions and design feedback are ready.

**Comment by hamiltonryan** [comment]
@kkoryaka I updated all of the images for this one to work better and lightened that sand one to help with legibility.  

- [Updated Parallax Page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=545%3A10209) - Figma
- [Updated Parallax Images](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=750%3A9245) - Figma page

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks for the updates! 
@hamiltonryan Please let us know if I missed anything, and if you can help provide png files of the polygon shapes from Figma. In dev, the triangles' outlines are too heavy where they meet each other. Let me know if you'd like my help. :)

Here are some design fixes to make to the example:
- Scroll down section: 
-- Blue polygon shapes: Update
-- Scroll down container: Use the transparent shape and a sentence case heading like in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=545%3A10209). In dev, the container is solid with a white outline.
- Parallax height section: 
-- Yellow polygon shapes: Update
-- Heading: Use lower case "h" for sentence case consistency. 
-- Sentence: Start with capital "H".
- Light text color section: 
-- Gray-900 polygon shapes: Update
-- Heading: Use lower case "t" and "c" for sentence case consistency.

**Comment by hamiltonryan** [comment]
I did create clean versions of each of the polygon shapes to get rid of the double inner stroke that was happening. I added them to the [Parallax image folder.](https://stateca.sharepoint.com/:i:/r/sites/statewideinnovation/Shared%20Documents/Design%20Assets/V6%20State%20Web%20Template/V6%20imagery/Parallax/pexels-oliver-sj%C3%B6str%C3%B6m-1122418%20Corrected%202.png?csf=1&web=1&e=mUyN0X) 

The image for the Scroll section is still having problems too, and it looks like the size is being reduced somehow, so if we could make sure that we get that back to the original image size of 1800 x 1200 that should help with it looking so blurry.

**Comment by hamiltonryan** [comment]
@kkoryaka I updated the [Scroll image ](https://stateca.sharepoint.com/:i:/r/sites/statewideinnovation/Shared%20Documents/Design%20Assets/V6%20State%20Web%20Template/V6%20imagery/Parallax/pexels-oliver-sj%C3%B6str%C3%B6m-1122418%20Org.png?csf=1&web=1&e=cSShL6)in the [Parallax folder](https://stateca.sharepoint.com/:f:/r/sites/statewideinnovation/Shared%20Documents/Design%20Assets/V6%20State%20Web%20Template/V6%20imagery/Parallax?csf=1&web=1&e=czwrzv) to the larger original size. It should be good to go now.

**Comment by kkoryaka** [comment]
@sharon-rabang @hamiltonryan this is now updated

**Comment by kkoryaka** [comment]
@sharon-rabang try it now

**Comment by sharon-rabang** [comment]
@kkoryaka Yay! Looks good to go, thanks so much!
