### ISSUE TITLE
Components: Blockquote

### ISSUE THREAD

**Issue by hamiltonryan** [Office-of-Digital-Services/California-State-Web-Template-Website#680]
The "Basic blockquote" section is missing the heading for the first blockquote "With graphic"

**Comment by hamiltonryan** [comment]
@kkoryaka The Blockquote component page updates are ready for Dev.

- [Blockquote Page](https://docs.google.com/document/d/1a4MKyUL_jrWf_YAIa9zC0HJORtH3bXDgb7AKz_KTOp8/edit#heading=h.z68m2zuis6an) - google doc
- [Blockquote Page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=472%3A8379) - Figma

**Comment by sharon-rabang** [comment]
@sharon-rabang Reassigning this one to myself to add another example that includes a profile image.
Will close the related and past issue [#325](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/325).

**Comment by sharon-rabang** [comment]
@kkoryaka The blockquote with image example is ready for dev. The image is available in the [Components examples](https://stateca.sharepoint.com/:f:/r/sites/statewideinnovation/Shared%20Documents/Design%20Assets/V6%20State%20Web%20Template/V6%20imagery/Components%20examples?csf=1&web=1&e=SWcv1e) folder.

**Comment by kkoryaka** [comment]
@sharon-rabang  Added the image, please review

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some changes to make:
- Basic blockquote, example: 
-- Add "With graphic" heading before first image for consistency.
-- Reduce height of outline container to center the images inside.
- Pull quote: Reduce height of outline container to center the images inside.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
