### ISSUE TITLE
Components: Breadcrumb

### ISSUE THREAD

**Issue by hamiltonryan** [Office-of-Digital-Services/California-State-Web-Template-Website#681]
The sample text has been updated in Figma, and is ready for Dev

**Comment by hamiltonryan** [comment]
@kkoryaka The Breadcrumb component page updates are ready for Dev.

- [Blockquote Page](https://docs.google.com/document/d/1he_wH2H_59JmuOXfTJuXDANV5bofqRmFFCl5O6UpqxM/edit#) - google doc
- [Blockquote Page](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=478%3A8502) - Figma

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some changes to make:
- Example:
-- Reduce height of the outline container to vertically center the breadcrumbs.
-- Is it possible to update the example's text with the basic terms used in Figma - "Breadcrumb 1 / Breadcrumb 2 / Breadcrumb 3"?

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
