### ISSUE TITLE
Structure: Utility header

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#682]

**Comment by sharon-rabang** [comment]
@kkoryaka The utility header page is ready for dev.

- [Utility header](https://docs.google.com/document/d/1XNd6uPBNR704coeuNh16lNNUllmJ6ZTgyE9q4_Ky2ig/edit#heading=h.rspxulmdycld) - google doc
- [Utility header](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=14%3A7786) - Figma

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated, please review https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/utility-header.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some changes to make:
- Utility header content: Under "It includes" in the first bullet, fix the external link icon and link to https://www.ca.gov.
- Examples: The images look blurry. Please try replacing them with the attached png files to see if they display better.
-- ![header-desktop](https://user-images.githubusercontent.com/99768807/198327607-80ae1daa-7451-47ad-9279-46c824ebc500.png)
-- ![header-mobile](https://user-images.githubusercontent.com/99768807/198327619-62ac5476-9be9-42b8-8a46-fe676bf65c43.png)

**Comment by kkoryaka** [comment]
@sharon-rabang i used your images please review

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
