### ISSUE TITLE
Structure: Settings

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#683]

**Comment by sharon-rabang** [comment]
@kkoryaka The Settings page is ready for dev.

Settings - [google doc](https://docs.google.com/document/d/1siZ5c2YNAI-JsvBB3bSkSXQ5DOuVef19JJDTSVmtd20/edit#heading=h.rx4gk3lhdug1)
Settings - [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=14%3A7761)

**Comment by kkoryaka** [comment]
@sharon-rabang this is complete, please review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/settings-bar.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some changes to make: 
- Examples: Update the desktop image and replace the mobile image with the attached png files for a sharper display.
![settings-desktop](https://user-images.githubusercontent.com/99768807/198329477-b925b36e-79c1-49a8-9d91-45b3383cb95c.png)
![settings-mobile](https://user-images.githubusercontent.com/99768807/198329488-f264bbb4-4755-41b7-a2b4-0df58373bb1a.png)

**Comment by kkoryaka** [comment]
@sharon-rabang i used your images. please review

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
