### ISSUE TITLE
Structure: Search

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#684]

**Comment by sharon-rabang** [comment]
@kkoryaka The Search page is ready for dev.

- [Search](https://docs.google.com/document/d/1ztmzSn3N-R3kxpTUz3hIEzWbVx47--wLZJAhgCtHPnQ/edit#heading=h.xv7rpjtvd3w5) - google doc
- [Search](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=14%3A7703) - Figma

**Comment by sharon-rabang** [comment]
@kkoryaka For the examples, I'll create and attach png files here to help make sure they display well.

**Comment by sharon-rabang** [comment]
![active-search-desktop](https://user-images.githubusercontent.com/99768807/198338878-c5e6fe12-e23b-42e2-8812-c1d570b92d6e.png)
![active-search-mobile](https://user-images.githubusercontent.com/99768807/198338886-25ee7611-108f-4a60-86af-d6004fcb1594.png)
![inactive-search-desktop](https://user-images.githubusercontent.com/99768807/198338892-9ad15056-7480-426e-98af-8d542d9252b2.png)
![inactive-search-mobile](https://user-images.githubusercontent.com/99768807/198338909-593dc072-14d8-4450-b5cd-a0d90c740e94.png)

**Comment by sharon-rabang** [comment]
@sharon-rabang is updating the Figma page and examples based on revised content.

**Comment by kkoryaka** [comment]
@sharon-rabang this page is now updated (still need to update live examples.)

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some changes to make:

- Content: Like on the [Utility header](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/utility-header.html) page, only use the larger lead text size for the first sentence paragraph. Change the rest of the content in this section to the regular body text size - starting from, "With search, visitors can filter content..." and on.
- Active search, example: Change the icons to match our other icon examples. Use the California icon for Link 1 and the capitol building icon for Link 2.
- Inactive search, example: Change the icons to match our other icon examples. Use the California icon for Link 1 and the capitol building icon for Link 2.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! The examples for Inactive search and Featured search look blurry compared to other examples. 

Here are 2 png files I exported from the native artwork in Figma. Let me know if these turn out looking sharper.
![inactive-search](https://user-images.githubusercontent.com/99768807/199078790-7a23593b-86f3-442b-ac39-693757cc05d7.png)
![featured-search](https://user-images.githubusercontent.com/99768807/199078817-6c762141-59f2-48b1-9795-9c984a92a4b1.png)

**Comment by kkoryaka** [comment]
@sharon-rabang your images are inserted.

**Comment by sharon-rabang** [comment]
@kkoryaka I'm so sorry for sending you the wrong images! They were screenshots so they still appear blurry. Here are the correct ones from the native artwork to insert again:
![inactive-search](https://user-images.githubusercontent.com/99768807/199085931-09cf84f7-2500-4c3c-a53a-c4e11d4e33b6.png)
![featured-search](https://user-images.githubusercontent.com/99768807/199085944-e71eafa6-f73c-4af2-9bd1-a961d7f10f6c.png)

**Comment by kkoryaka** [comment]
@sharon-rabang the images are now updated once more.

**Comment by sharon-rabang** [comment]
@kkoryaka Sorry, please try replacing the images again since they're still blurry and not from Figma. You can tell here because I used the thinner search icon from the search bar and not from the icon library:
![image](https://user-images.githubusercontent.com/99768807/199098577-2dfd3487-fe49-4b74-8eae-15d16b9f5440.png)

**Comment by kkoryaka** [comment]
@sharon-rabang sorry about that, was saving them to the wrong directory. They should be now updated.

**Comment by sharon-rabang** [comment]
@kkoryaka No prob, they look sharp - yay! This is good to go, thanks!
