### ISSUE TITLE
Structure: Site header

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#685]

**Comment by sharon-rabang** [comment]
@kkoryaka The Site header page is ready for dev.

- [Site header](https://docs.google.com/document/d/1ovKFrJs1HhQgKTiOVk6klDdEH8j-CocT93zQ4IFk44o/edit#heading=h.rx4gk3lhdug1) - google doc
- [Site header](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=14%3A7736) - Figma

**Comment by sharon-rabang** [comment]
@kkoryaka For the examples, I'll create and attach png files here to help make sure they display well.

**Comment by sharon-rabang** [comment]
![site-header-desktop](https://user-images.githubusercontent.com/99768807/198337926-d08794f5-31e8-47ab-a38d-9bf3709a69e3.png)
![site-header-mobile](https://user-images.githubusercontent.com/99768807/198337932-e304ea5a-6c52-4bda-b1cf-037079bd70c8.png)

**Comment by extinah** [comment]
Here's the final content:
https://docs.google.com/document/d/1ovKFrJs1HhQgKTiOVk6klDdEH8j-CocT93zQ4IFk44o/edit?usp=sharing

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by extinah** [comment]
@kkoryaka  small edit to content (made the change during review): Change Search box to Search. 

Original: Review [Search box](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/search.html) for more information.

Updated: Review [Search](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/search.html) for more information.

Otherwise, content approved. Thanks

**Comment by sharon-rabang** [comment]
@kkoryaka @extinah Looks good to go after the small content edit above is made. Thanks!

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here's one change to make:
- Content: Like on the [Utility header](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/utility-header.html) page, increase the text size of the first paragraph to highlight the intro and provide visual contrast.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
