### ISSUE TITLE
Structure: Site navigation

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#686]

**Comment by sharon-rabang** [comment]
@kkoryaka The Site navigation page is ready for dev.

- [Site navigation](https://docs.google.com/document/d/1do8n7bgzpuSlPqtcQRgnijS92El8--T5zcbyiqXDuIE/edit#heading=h.kp15ls2io1p5) - google doc
- [Site navigation](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=471%3A9501) - Figma

**Comment by sharon-rabang** [comment]
@kkoryaka For the examples, I'll create and attach png files here to help make sure they display well.

**Comment by sharon-rabang** [comment]
![single-level-menu](https://user-images.githubusercontent.com/99768807/198340102-f3325ef5-ba8b-4fee-8725-5d0decb1d5d6.png)
![dropdown-menu](https://user-images.githubusercontent.com/99768807/198340115-55dcf4f3-45a2-42f2-a1b7-f308761df055.png)
![mega-menu](https://user-images.githubusercontent.com/99768807/198340122-e046f136-fb5e-481f-b84b-171acbd9f6ee.png)
![icon-menu](https://user-images.githubusercontent.com/99768807/198340134-a7d5a24b-4986-4546-b861-fe217343002c.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this page is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some changes to make:
- Content: Like on the [Utility header](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/utility-header.html) page, increase the text size of the first paragraph to highlight the intro and provide visual contrast.
 - Megamenu, example: Update the image with the Gray-700version of icons in the [Structural elements-examples](https://stateca.sharepoint.com/:f:/r/sites/statewideinnovation/Shared%20Documents/Design%20Assets/V6%20State%20Web%20Template/V6%20imagery/Structural%20elements-examples?csf=1&web=1&e=Z46lUa) folder.
 - Icon menu, example: Update the image with the Gray-700 version of icons in the [Structural elements-examples](https://stateca.sharepoint.com/:f:/r/sites/statewideinnovation/Shared%20Documents/Design%20Assets/V6%20State%20Web%20Template/V6%20imagery/Structural%20elements-examples?csf=1&web=1&e=Z46lUa) folder.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
