### ISSUE TITLE
Structure: Footer

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#687]

**Comment by sharon-rabang** [comment]
@kkoryaka The Footer page is ready for dev.

- [Footer](https://docs.google.com/document/d/1Gg-8bZmmCIv-GV7MjqlO9Lx1a93hKamlnsFlUXTKJeI/edit#heading=h.rx4gk3lhdug1) - google doc
- [Footer](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=14%3A7510) - Figma

**Comment by sharon-rabang** [comment]
@kkoryaka For the examples, I'll create and attach png files here to help make sure they display well.
![footer-desktop](https://user-images.githubusercontent.com/99768807/198341645-0404fa4e-40d0-441f-89e7-b2acfacbf6fc.png)
![footer-mobile](https://user-images.githubusercontent.com/99768807/198341659-eeedf260-3760-42ce-913d-5699fd6a11de.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
