### ISSUE TITLE
Components: Countdown timer

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#691]

**Comment by sharon-rabang** [comment]
@kkoryaka The Countdown timer pager is ready for dev.

- [Countdown timer](https://docs.google.com/document/d/1Vas40gy7wU29TzJ5Jxc7_NN-aCMJEIIEupck-gtPak0/edit#) - google doc
- [Countdown timer](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=478%3A9160)  - Figma

Here are some of the changes to make:
- Countdown timer section, bullets: Add "Weeks" and make it the first bullet item.
- Example, image: Update with the image in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=478%3A9160)
- When and how to use it section: Delete "Headings can be a:"

cc: @hamiltonryan

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Here are some changes to make:
- Example: 
-- Headings: Delete "Countdown" to become "Default" and Primary" for consistency across all examples' headings.
-- Countdown timer headings: Change "min" and "sec" to "mins" and "secs" for consistency across the timer's headings.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
