### ISSUE TITLE
Components: Lists

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#694]

**Comment by sharon-rabang** [comment]
@kkoryaka The Lists page is ready for dev.

- [Lists](https://docs.google.com/document/d/1sbr5yVdc36So8aW6fbiNo52zWUhgNZQoSJHukopQlIA/edit) - google doc
- [Lists](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=513%3A8643) - Figma

Here are some of the changes to make:
- Unordered list example: Reduce height of the outline container to vertically center the list.
- Ordered list example: Reduce height of the outline container to vertically center the list.
- Usage, content: Update with the google doc's - [Lists](https://docs.google.com/document/d/1sbr5yVdc36So8aW6fbiNo52zWUhgNZQoSJHukopQlIA/edit) content.

**Comment by kkoryaka** [comment]
@sharon-rabang this is also updated
