### ISSUE TITLE
Components: Table

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#697]

**Comment by sharon-rabang** [comment]
@kkoryaka The Table page is ready for dev.

- [Table](https://docs.google.com/document/d/1wti96QD3bOLNDnVat3PufHeComN2FF7U76S6VWTKG0g/edit#heading=h.xv7rpjtvd3w5) - google doc
- [Table](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=545%3A9460) - Figma

Here are some of the changes to make:
- Basic, Shaded, and Zebra examples: 
- -- Change the user name @fat to @jthornton
- -- Reduce the height of their outline containers to vertically center each table.
- -- After these fixes, I'll take screenshots and update Figma.
- Usage, How not to use it: Update with content in the [Table](https://docs.google.com/document/d/1wti96QD3bOLNDnVat3PufHeComN2FF7U76S6VWTKG0g/edit#heading=h.xv7rpjtvd3w5) google doc.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/table.html

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
