### ISSUE TITLE
Mobile controls

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#714]
Short section already with draft content from Konstantin. Creating a word doc to go along with it.

@sharon-rabang  @hamiltonryan  this also needs a figma design at some point. It's mainly text so might not be a bit deal. Thanks

https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/mobile-controls.html

**Comment by hamiltonryan** [comment]
I'll go ahead make a Figma page for it under structure

**Comment by extinah** [comment]
Content doc:
https://docs.google.com/document/d/1a7bS-RQ-3XITyF53ardfLp0G7iGQPG0JDKsSEYAMrp4/edit?usp=sharing

**Comment by extinah** [comment]
@kkoryaka  please assign as needed. Here's the updated content: 
https://docs.google.com/document/d/1a7bS-RQ-3XITyF53ardfLp0G7iGQPG0JDKsSEYAMrp4/edit?usp=sharing

**Comment by sharon-rabang** [comment]
@kkoryaka The Mobile controls page is ready for dev.

- [Mobile controls](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=766%3A9299) - Figma
![mobile-controls](https://user-images.githubusercontent.com/99768807/198412870-ec9b677e-c643-46c5-909d-af9e8bc5bf53.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this page is now updated. I will update the actual controls later.

**Comment by extinah** [comment]
@kkoryaka  content reviewed and approved. pending design review 
cc @sharon-rabang

**Comment by sharon-rabang** [comment]
@extinah There are two changes I made that need review and approval:
- @kkoryaka and I discussed my decision to use the state template's original mobile controls with a search icon and hamburger icon. It's preferred over the Design Systems with a hamburger icon and the word "Menu" which isn't necessary. If there are no concerns, please update this part of the Usage content: 
By default, the text identifier for the search button is "Search" and text identifier for the navigation button is "Menu."
- I added the standard Accessibility section for consistency across all Structure and Components pages.

![mobile-controls](https://user-images.githubusercontent.com/99768807/198673831-6f39aba1-2674-492e-b227-a65f7d86ced8.png)

**Comment by sharon-rabang** [comment]
@extinah @kkoryaka Based on Koji's helpful feedback about the mobile controls' icons for accessibility, we have updated the Mobile controls example. 
@kkoryaka I will change all of the related images for examples and let you know when you can update their pages.

**Comment by sharon-rabang** [comment]
![image](https://user-images.githubusercontent.com/99768807/198684117-7de6faf4-ae49-46b3-a28d-811b9b145bcb.png)

**Comment by rkojik** [comment]
Looks great! Sorry if that felt like a 'swoop'. Helping or hurting?!?

**Comment by sharon-rabang** [comment]
@rkojik Great, thanks! Appreciate you for always helping!

**Comment by extinah** [comment]
> Looks great! Sorry if that felt like a 'swoop'. Helping or hurting?!?

Helping! And not a swoop - good input to research. Saw that both gov.uk and canada don't even use a hamburger menu. they simply use the word menu and an arrow.

**Comment by rkojik** [comment]
> **Review notes**:
> 
> * For the smallest devices, @kkoryaka will add a media query to stack the Search and Menu, so they don't run into the website title.
> * @sharon-rabang will change all of the related mobile view images for the examples in Figma, then place updated mobile view images in our image folder. Will let Konstantin know when they're available for him to grab anytime.

I might experiment (maybe not now, but later) with hiding the title in an accessible way, instead of stacking the search / menu. Likelihood that a user interacts with those two things rather than the title.

**Comment by sharon-rabang** [comment]
> > **Review notes**:
> > 
> > * For the smallest devices, @kkoryaka will add a media query to stack the Search and Menu, so they don't run into the website title.
> > * @sharon-rabang will change all of the related mobile view images for the examples in Figma, then place updated mobile view images in our image folder. Will let Konstantin know when they're available for him to grab anytime.
> 
> I might experiment (maybe not now, but later) with hiding the title in an accessible way, instead of stacking the search / menu. Likelihood that a user interacts with those two things rather than the title.

@rkojik Will do, thanks! @extinah and I also saw how the Menu stacks (or wraps?) right under the logo and website title here: https://gold.designsystemau.org/

**Comment by kkoryaka** [comment]
@sharon-rabang updated mobile controls statewide. please check.

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
