### ISSUE TITLE
Create communication to DWSN for beta release.

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#723]
Include:

- Link to site
- Info about feedback timeframe
- Their feedback matters
- Key updates
- What's important about this release
- Timeline (production release)

**Comment by extinah** [comment]
@yesenia-gtz Who should do this? Sorry if this is covered already. I was thinking about what would be happening next week.

**Comment by yesenia-gtz** [comment]
@artuoma can you take the lead on facilitating feedback from DWSN?
