### ISSUE TITLE
Service Tiles Missing in v5.6.*

### ISSUE THREAD

**Issue by coop333** [Office-of-Digital-Services/California-State-Web-Template-Website#759]
I work the Bureau of Automotive Repair, Department of Consumer Affairs and we were looking to update to version 5.6. I noticed the elimination of the service tiles and a few other components. Will service tiles be added in at some point? How about the other lost features?

Old path /sample/service-group.html

**Comment by kkoryaka** [comment]
@coop333  Yes, once we've dropped the jQuery some of the components that were based on jQuery plugins we also have dropped. We are about to release the new look and feel State template version that is aligned with [Design System](https://designsystem.webstandards.ca.gov/) which is going to be a new standard for State Template.
