### ISSUE TITLE
Re visit progress-tracker mobile view design

### ISSUE THREAD

**Issue by timothyshambra** [Office-of-Digital-Services/California-State-Web-Template-Website#760]
Horizontal tracker, responsive: The centered content looks okay without the line element because there are dot elements to visually guide you down to the next step.
Vertical tracker, responsive: The left-aligned content does not have the dot elements to visually guide you through the steps. Is it possible to apply the same code used in the Step list? This may allow us to include the dot and line elements along the left side of the content.
-- If this works, please apply it to the homepage's timeline as well.
Step list: The headings look bolder than usual. Please check the font to make sure it's Public Sans bold, and not an extra bold or black style font.
-- Update the content based on the google doc or the page in Figma: [Progress tracker](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=564%3A8933)

**Comment by extinah** [comment]
Go to related card for mobile recommendations: [issue 411](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/411)

**Comment by sharon-rabang** [comment]
11.18.22 Stand-up notes: As a mobile view design solution for the horizontal tracker displayed on desktop, try coding it to display as a vertical tracker (left-aligned) when viewed on mobile.

Here are the homepage examples in Figma:
- [Desktop: Horizontal tracker]((https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A441&t=5FrWSRnN8WnHjo18-1)
- [Mobile: Vertical tracker](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1442%3A13133&t=5FrWSRnN8WnHjo18-1) Use this vertical design for mobile view of the desktop's horizontal tracker design.
