### ISSUE TITLE
What's New page - Content update

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#764]
**Update content on Whats new page for Production release**

Related to https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/216

**Comment by extinah** [comment]
Clean up google doc - true up with figma and dev.

**Comment by extinah** [comment]
@kkoryaka  some minor updates after cleaning up these files. Feel free to assign to another developer. Thanks!

- [ ] Under the Code heading, last bullet. Update content to: Enabled sites to render markdown files in HTML.
- [ ] Under User experience, delete this bullet: Forms to request new components, patterns, and icons.
- [ ] Under User experience, update the last bullet to: Collaboration channels so you can provide feedback and report bugs.

**Comment by kkoryaka** [comment]
@extinah this is now updated

**Comment by yesenia-gtz** [comment]
@extinah OK to close out? https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/whats-new.html

**Comment by extinah** [comment]
Approved. Looks good.
