### ISSUE TITLE
Make all Lead text consistent

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#765]
Typography updates:
- [x] Lead text: Increase all lead text to 24.539 for consistency with the Design System (In dev, there isn't enough contrast between lead text and regular text)
- [ ] Need to address all instances on the site

Side nav: Redesign related to [#233](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/223) and [#587](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/587)

**Comment by sharon-rabang** [comment]
- Met with @ashleydraper to discuss the use of lead text throughout the beta site. Determined that lead text doesn't suit the state template's content, so we will update all the lead text with regular text. 
- @sharon-rabang will:
-- Update Figma to apply regular sized text across all content
-- List the beta site pages that need updates for dev here

**Comment by sharon-rabang** [comment]
@kkoryaka Figma has been update. Here are the pages to update by changing the size of all lead text to regular text:
- [ ] [About](https://beta.template.webstandards.ca.gov/about.html)
- [ ] [Template updates](https://beta.template.webstandards.ca.gov/template-updates.html)
- [ ] [Get started](https://beta.template.webstandards.ca.gov/get-started.html)
  - [ ] [What's new in V6](https://beta.template.webstandards.ca.gov/whats-new.html)
  - [ ] [Download and setup](https://beta.template.webstandards.ca.gov/download-and-setup.html)
  - [ ] [CSS classes shortcuts](https://beta.template.webstandards.ca.gov/get-started/css-classes-shortcuts/)
- [ ] [Structure](https://beta.template.webstandards.ca.gov/structure.html)
  - [ ] [Utility header](https://beta.template.webstandards.ca.gov/structure/utility-header.html)
  - [ ] [Settings](https://beta.template.webstandards.ca.gov/structure/settings-bar.html)
  - [ ] [Site header](https://beta.template.webstandards.ca.gov/structure/site-header.html)
  - [ ] [Mobile controls](https://beta.template.webstandards.ca.gov/structure/mobile-controls.html)
  - [ ] [Search](https://beta.template.webstandards.ca.gov/structure/search.html)
  - [ ] [Site navigation](https://beta.template.webstandards.ca.gov/structure/site-navigation.html)
  - [ ] [Footer](https://beta.template.webstandards.ca.gov/structure/footer.html)
- [ ] Visual design
  - [ ] [Colors](https://beta.template.webstandards.ca.gov/visual-design/color.html)  
  - [ ] [Color themes](https://beta.template.webstandards.ca.gov/visual-design/color/?delta)
  - [ ] [Icons](https://beta.template.webstandards.ca.gov/visual-design/icons.html)
  - [ ] [Typography](https://beta.template.webstandards.ca.gov/visual-design/typography.html)
- [ ] [Components](https://beta.template.webstandards.ca.gov/components.html)
  - [ ] [Accordion](https://beta.template.webstandards.ca.gov/components/accordions.html)
  - [ ] [Alert ](https://beta.template.webstandards.ca.gov/components/alert.html)
  - [ ] [Blockquote](https://beta.template.webstandards.ca.gov/components/blockquote.html)
  - [ ] [Breadcrumb](https://beta.template.webstandards.ca.gov/components/breadcrumb.html)
  - [ ] [Button](https://beta.template.webstandards.ca.gov/components/buttons.html)
  - [ ] [Countdown timer](https://beta.template.webstandards.ca.gov/components/countdown-timer.html)
  - [ ] [Form elements](https://beta.template.webstandards.ca.gov/components/form-elements.html)
  - [ ] [Horizontal separator](https://beta.template.webstandards.ca.gov/components/horizontal-separator.html)
  - [ ] [Lists](https://beta.template.webstandards.ca.gov/components/lists.html)
  - [ ] [Modal](https://beta.template.webstandards.ca.gov/components/modal.html)
  - [ ] [Number counter](https://beta.template.webstandards.ca.gov/components/number-counter.html)
  - [ ] [Parallax](https://beta.template.webstandards.ca.gov/components/parallax.html)
  - [ ] [Progress bar](https://beta.template.webstandards.ca.gov/components/progress-bar.html)
  - [ ] [Social media icons](https://beta.template.webstandards.ca.gov/components/social-media-icons.html)
  - [ ] [Table](https://beta.template.webstandards.ca.gov/components/table.html)
  - [ ] [Tabs](https://beta.template.webstandards.ca.gov/components/tabs.html)
- [ ] [Patterns](https://beta.template.webstandards.ca.gov/patterns.html)
  - [ ] [Banner](https://beta.template.webstandards.ca.gov/patterns/banner.html)
  - [ ] [Card](https://beta.template.webstandards.ca.gov/patterns/card.html)
  - [ ] [Card grid](https://beta.template.webstandards.ca.gov/patterns/card-grid.html)
  - [ ] [Link grid](https://beta.template.webstandards.ca.gov/patterns/link-grid.html)
  - [ ] [Progress tracker](https://beta.template.webstandards.ca.gov/patterns/progress-tracker.html)

**Comment by sharon-rabang** [comment]
@kkoryaka FYI - @extinah would like to pause and discuss this decision as a team. Please don't make any changes just yet. Thanks!

**Comment by sharon-rabang** [comment]
11/16/22: Team meeting design review and approval notes:
- [ ] Discussed lead text usage and updating its usage info on the Typography page.
- [ ] Agreed to remove all lead text from the site, except for landing pages selected by UX Team.
Action items:
- [ ] Identify and update Figma pages that can use lead text.
- [ ] Update the lead text usage info to be more specific on the Typography page.
- [ ] Update the previous list of pages for dev to change the size of all "old" lead text to regular text.
- [ ] UX Team shareout of lead text page recommendations for review and approval.

@kkoryaka Here are the 5 pages ready for lead text updates:
- Font size: Increase to 24.539 as used in the [Design System](https://designsystem.webstandards.ca.gov/about/)
- Font weight: Change from Public Sans Regular to Public Sans Medium
- Content: Copy the intro content updates made in the Google docs. See their Figma pages for design reference.

- [ ] [Get started](https://beta.template.webstandards.ca.gov/get-started.html)
- [Get started: Google doc](https://docs.google.com/document/d/18lrNAan6a05MHQWIb3K_Kp-fHVPA_E0feOWmocav4ts/edit#)
- [Get started: Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=553%3A10414&t=5FrWSRnN8WnHjo18-1)

- [ ] [About](https://beta.template.webstandards.ca.gov/about.html)
- [About: Google doc](https://docs.google.com/document/d/1lzx-s0uAgfjEJ09atcSN6_s2XwP4N6VSGpyZ6P70MvQ/edit#heading=h.pztyjfebp0tk)
- [About: Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=718%3A10947&t=5FrWSRnN8WnHjo18-1)

- [ ] [Structure](https://beta.template.webstandards.ca.gov/structure.html)
- [Structure: Google doc](https://docs.google.com/document/d/1Mnw_Do_Ra8ozhCN-89DVraihOqTBJvjom6p1Zgmb_VI/edit#)
- [Structure: Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A3950&t=5FrWSRnN8WnHjo18-1)

- [ ] [Components](https://beta.template.webstandards.ca.gov/components.html)
- [Components: Google doc](https://docs.google.com/document/d/1EV1vr5HskpNkl9S-Zsq_55JxkvQONiJrb-GDzxEt6aQ/edit)
- [Components: Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A5622&t=5FrWSRnN8WnHjo18-1)

- [ ] [Patterns](https://beta.template.webstandards.ca.gov/patterns.html)
- [Patterns: Google doc](https://docs.google.com/document/d/1dSaxoIHsuJMXOrFMiVnEQgIrJfAyWmkcPDikllgrH78/edit)
- [Patterns: Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A6623&t=5FrWSRnN8WnHjo18-1)

On this Typography page, the only update to make is in the lead text usage info:
- [ ] [Typography](https://beta.template.webstandards.ca.gov/visual-design/typography.html)
- [Typography: Google doc](https://docs.google.com/document/d/11oaHBWMaPXzwPCxEUAB65aSLps3nmyLzzE4tvmimSU0/edit)
- [Typography: Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=57%3A4871&t=5FrWSRnN8WnHjo18-1)

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated. Please review in beta staging.

**Comment by kkoryaka** [comment]
@sharon-rabang I have made those edits. Please review

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks for making the edits! There's only 1 change that was missed: 
- [Typography](https://beta.template.webstandards.ca.gov/visual-design/typography.html):
 Remove the lead text from the intro sentence "Use typography to present your department's brand and content as clearly as possible." Please use regular sized text 19.082px.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now fixed

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
