### ISSUE TITLE
Social media icons - content/intent

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#770]
During QA, Ryan sent an update for the image to include context (footer) - per the google doc.

Konstanin mentioned this component isn't for the footer, it's for within content.

Research, review, and update as needed. It's currently incorrect (the content)

**Comment by extinah** [comment]
@yesenia-gtz  pinging you for awareness.

**Comment by extinah** [comment]
Also - revisit "share" vs just a link to the social media account.

**Comment by extinah** [comment]
Content updated. 

Last item for dev: move the social media icons to be left justified.
![image](https://user-images.githubusercontent.com/33840424/210662026-5330fd24-a1cb-4a81-b9bb-f2910e3c0c34.png)

@carterm assigned to you as lead. feel free to assign to another dev, as needed.

**Comment by jon-grant-state-ca-gov** [comment]
Updates merged into 6.1.1 branch

**Comment by extinah** [comment]
@jon-grant-state-ca-gov 
Can you provide a staging link?

for documentation, here's the google doc with the updated content (not sure if this is relevant here)
https://docs.google.com/document/d/1WQZ71PA9ZIit5Y48mLNxdgHChrq3qdDN6ZJM57T1VxY/edit#heading=h.xv7rpjtvd3w5

**Comment by extinah** [comment]
https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/social-media-icons.html

Looks good. Approved. Ready to close.
