### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by artuoma** [Office-of-Digital-Services/California-State-Web-Template-Website#818]
Need to optimize for performance including images

**Comment by artuoma** [comment]
https://pagespeed.web.dev/report?url=https%3A%2F%2Fbeta.template.webstandards.ca.gov%2F

![image](https://user-images.githubusercontent.com/20782462/200669695-68f5f0d4-733d-4b7d-a866-bd56e998bbcf.png)


- [ ] Optimize images
- [ ] Optimize code
- [ ] Optimize environment

**Comment by timothyshambra** [comment]
Duplicate: https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/842
