### ISSUE TITLE
Search results page (look and feel)

### ISSUE THREAD

**Issue by artuoma** [Office-of-Digital-Services/California-State-Web-Template-Website#820]
Need to make search results appear more integrated with the state web template and not so obvious it is coming from Google.

**Comment by artuoma** [comment]
![image](https://user-images.githubusercontent.com/20782462/200917298-37855e86-d06f-4797-a702-2261c04bf380.png)

**Comment by extinah** [comment]
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJIAAAFzCAYAAADVFFAdAAAYfUlEQVR4nO2dX2gbZ7rGnz0tB7qwUNBZL5ssIQNZWM6hwtQDKRoTqAiIuGDfFiKLRfbNQis511n5wmrh3FkWhb1xxOIosFeHyBAHQXGhRKKBoXVUFgoNTAibLHEtKHTZwOEsOhczGn0jjWRJfiWN5OcHBksz+v5Ij7/303ie9/1Zo9FogJAz8m+THgCZDSgkIgKFRESgkIgIFBIRgUIiIlBIRAQKiYhAIRERKCQiAoVERKCQiAhvTqbbb/H9jXW8Vp/63W1c2l7G25MZUHde7eOvv/8U//pgF+GP3pn0aALL+IX0dR612/cAzwdjC+v5jWd4/TCFX499UOSsjFlI3+L72/fs1cfz1/0Ofvvw8XiHQkQZr5C+/gKvAbzxvnF6CGuGFOfhW58+xm/ftX//+2dX8cODCH7xBw0//eme/aRnhavDurWEn75Dx7Ef92/h+Z+qeOuDm3j9oLkyXvCejwh+8edtaL8SmPM5Yayb7R//ZgEA/v03od4nqvuSh49x6Q8RvL59C9Yr9aQq/ombCD98jF9+AOBBwTneFNFN/PLhY4T/fBtvPFjHX/frni5e432EHz5G+KN38PfPlPMf7uItVPHTf+/jR8G5zzoT2mw3aVs5YK88v/zbF/gXgLci9iry9tX38eJPn+Kfj+vAclOEEfz8qv37W5ciAKr4vxcAUME/vwPwwfv2XutXBn7+O+CnLyr4cXm51U+kFVp//dFj/PqjOqxbV1FTxkL6Z6xCevs3Gp6jiv/9Wx14NwQgBG3b3hs1Q47K69tXUVOfeP4SwCmrWZMH66g9UJ94htcA3vI51Q6VsMPcNjq/UZJTGe+K9O5N/OJ399zV4bR9krovGpguX9c7w9W3+McDKF8Avh2yw/PNmC9IhqCt3gS++xTPP1M+sK/zntXo7avv4w0Ar6v2OT/u30LtxlV8/3UfXTihDA++wN8Be7914ypqn50ikO/sFevH/QJXoyEY/x7p3RTCD9/H9zfaQ4+6Ai3jv/4M/PX3rXPe+MNBn6tTCNr2AaxbS/jhxj38APhcblB5B7/99CZqt+/hhxv3ANzEWx9U8fqBLazAXSANKD+jHYlIwP+1EREoJCIChUREoJCICBQSEYFCIiJQSEQEComIQCERESgkIgKFRESgkIgIFBIR4c2Tk5NJj4HMALyNhIjA0EZEoJCICBQSEYFCIiJQSEQEComIQCERESgkIgKFRESgkIgIFBIRgUIiIoxZSDXkdB25o/H2SkYPVyQiAoVERAickGp5Hbru/ORrXY/l8jnoeq6VGvC4hHTzdXoapeOxD/1cEygh1ffTSD7NoGyaMM0C4ntJpJvZaI9ySO7FUTBNmGYZ2tOi8soacktZaLsmTNNEeRPILuW8+SfJSAmQkOp49HkFxvVFJ91oGKubBiqfP0IdQO3LIpCIIgwACGElGW+99OgQRcQRnbcfhpbXEEcRh9zUj40ACekFrCqgXfLLWluH9RQwLl/0fWX9uQVENPgfJeMgQEK6CC0CWM/rPsdC0K4AlWcvfF8ZuqQBVQv+R8k4CJCQQli83gplQA13t1qhLnwtDuwdOvueOkoFZY80H/WEsvr+HU+oI6NnzC6SGnJ6EsX2pyMZlPMrCMH+Zpbcc55PFGCmwq1Xu8cMZDY1ZLeAgrlh75uOS0gvZVGBc/xgBytzo54PaTK9dqSjHPSC5gqQTJYAhbbe1PfTynUlJ7Rd0SiigDBFK1JbWFTCIZk8UyQkEmSmJrSRYEMhEREoJCIChUREoJCICBQSEYFCIiJQSEQEComIQCERESgkIsIEhFRHKaU4RSZhmDwuId2v0+Soza1CfBmzkOoopWLIXinANE3npwCs03077YxZSPYN/vFrYeU52y1S/JJ/89PMmIVk3+DfLprQ8o7nltqeZkfPMd17s1uqaZxsPV/fT7fOTZXgsRZ8letqxmzHUtrxrp52PoOOY0e5tnPt81yf3qzRGDev7jdSCwuNBecnVTppO+FJY3thobH9jfPwm+3GwsJ240mj0Wg0Thr3P1aOvbrfSC2kGvdftY4tfHy/4bboeW2j8WRnobGw86Q1hp0nnjG57ap8s22PtXnuN9uNhbY+3Tl4jnn7d/ueUcYvJIWTUsoVlEc4qhjaxaPS60Nt9PjwPAJsNDrE27WPtn462ukyhoUFj6BnkTcnuRqGlndgLtvhJ7aeQ9TcwMXnFlAtIqZnPeca1+vAfMjrMokYMLq27pgqr0vYJjVoriPF9tgBAF5aqEDDWg+3SvjDDIy9LLRdx+0yo4x3j3SU69ynwDE4qr9Hmv7/1s/Ocgg4LuHOnoHMgfP8H6M9OuttqhweW6AAgAsaDFiwul5GqKP0SRaIGCiuz/YlhPEKaT6KeDWLmGdj6zhCmr5+55y7zU2qs7lubVorsF7av9X+0vSx+eM1VTobbx8hn04Rd9xkFneRrRqIvhcC5hYRjVRw+JXPMQD1/S1kkcFmfgeFRBHJUzb008yYQ1sYG2YZWioGXW89a2yWYS6HWuccZJBe0qErxzfmAWAFa4kskus6igDiu3bGEuslAL/wMr+B8mYaMbezOArmCkLHpQHHHUcUW9B1W7bxXdMxX4awki/A0mPQt+A5Vt9PI7YFZA5sp0soVUBcTyJ9uWyvrjMGXSREBP6vjYhAIRERKCQiAoVERKCQiAgUEhGBQiIiUEhEBAqJiEAhEREoJCIChUREoJCICBQSEYEGydOgQbIvaJAcIbW8YnMaRLxTCA2SRAQaJM9ikOxYZVrFn+v7advtspeEnv8f5JayqKCC7FLr/K5jc8JpTqmYGXhj5dgNULNkkDzFH+fx1bWf6zMvbx89jJcBZPyb7bkV7JjNkqEGKluxNqvzIYqRDFabJbLmV5GJNEtohbCSNx0jABxfmZdWBcr2qpNAOGUqK5+BzIfO73MaNPRCOXd+FRnVOTIkvhUxFccLEMda0yRwQevh3wsGNEj2RReD5NBIji0YjFdIXUpjdRoko/4Fa1yDpFOL7biE9NJhl85Ug6Sk/ccxSF4+SxujGtvkoEGyL7oZJDVoUA2Sh51FDfsaW9t7MIXQINkX3QyS9qWL2JZjkExkkIkAVnMm1+LAehL60wzK+UVEI1lkl3RYuyY22scWyaCcmlYZ0SBJhOD/2ogIFBIRgUIiIlBIRAQKiYhAIRERKCQiAoVERKCQiAgUEhGBQiIiUEhEBAqJiEAhERHGfD9SDTk96XvzV3xXuRe7J443rgogsY3M01s4vD6bSdCniYmsSPFdb52R8uYAtTqO7iJbjaNgmjBT/znqocpBg+ToCS2vIY6mU6QPIhrs2+ZtVwlXo8kTCCH54WsePMpBXy8C1SxiehqlY9sUmd6vu3/xuXy6q+mxlvczVjat1SUlJ0EONU9lSO9qObixseZrkJwpxmuj8y+wZxcAVArjdTM2dhxrL8LX3fR4Ukop5klvgT67OF+b0dLtwx6z16zYa2xdjI0dZsrZYiIrUnHdm43EriLUKoxX+7IIY3O1ZWz8MAPDYx7sRjfTYx2PPq8gnmxanGxDYuXzR63VJLHmVjzSrkBxdNg28yanj226jI1STMQg2fqG1sxO0vwQ7eesp0Blr1W6ysZA9BhD2nXs5BXFqt72jTGOwcoCjmJss8FEnbatemdqHTN7RTC6faV/OUw/9qoST/pfYug/D8ooxjYbBGCzHcbGbhyVrS13Exq+Fkdl667X2HimZFchLF43UCy0Nsa1vE92kn5GKz622WDCK5LD/CoykRiySzlo5gbCHcZGw7OHGobQ8g4Kz3Qlp4BjlgQGC2/Djm2u3SA54AQCDg2SRIQAhDYyC1BIRAQKiYhAIRERKCQiAoVERKCQiAgUEhGBQiIiUEhEBAqJiEAhERHePDk5mfQYyAzA//4TERjaiAgUEhGBQiIiUEhEBAqJiEAhEREoJCIChUREoJCICBQSEYFCIiJQSESEMQlJzX7m/cn1m+5vKJSMbtNOwHNQjnVFOlMSUgHsFH/nPW/IaJhoaBs4CSkJLIHbI3VN9HlcQtovJHYs+XYYbQ+Z9f00knsA9pJdVyU1WWkun/PmPfL0r/R3xiSo6XzObldNuKq3JzMNPhMVUn3/DoqII9rMFXSUQ2xLs3NomyYKV7KI5WsA6ih9koXWDI0HGVgDhsTQ8g4KCQCJAsyUTzajoxySe07+brMM7amaJNDOSuv2v6shu6T2X0ERa+7YjL2kK+T6fhrJpxmUnXYzT5MecVT2gDXThJlfQQg15NYtZA6a/XiTegWZsQrprElI3YxrcyvYMc+WeKud2pdFJQGpnazU5egQxUgGq03Bz68iE1FD8lmSoEaVeYSxYe64+TTrzy3BGY6WsWZsGz4JaQgr+TKQirUyrkUyKOebH9BZsfs2rl/0P/rcAqpFJdubM7LrdeBCr3YHTYKqlMcAYESmJyfuhFL/DZGE1MnyvwKgWdNka38RO+/JjEe7AlSevQB8pBm6pAGRqL9we34dHzAJqlsew1ltj3LQq/3PYpJMcI80SBLS9g20/QFpl0JOKKng8CsnWBwd+hbNOXU01+KAG0brKBWUVuajiFezuOvZ4PdzDWyYJKgWrGOfMQScySYjHSAJafggg/SSjuYRJAow5wEgjNVNA7EtJyQmMshEAL/dRfhaHFhPQn/qExbnN1BI6EjqRbvfzTjgrgZhbLT1b2yW7VXmlAuEAyVBdd8PHVkYyOxmYFQPYU1BDm/akbpxlINe0AT3YbNN4K4jTYr6flq5xuOElSsaRdQnXJFc2ooSin4rnH0oJCICQxsRgUIiIlBIRAQKiYhAIRERKCQiAoVERKCQiAgUEhGBQiIiUEhEBBok/ehhRqQ3zh8aJB3q++kudy7625uIFxok/ZhbwY7i5iCnE7g90kQMkkc5xLYqQDWLWKqEuttmHaWUfY9Scd1/Veo63nMGDZIAML+B8qbhczOb7XaJQ7VSKXQd7/ljrDf/F9fb/V2Gj0Gy7DVILh2illq1X18oYTW/gtDcCnbM8Y27G93HGw78zfrS0CA5NL3GC4TP2f6KBsmhOW285wsaJM8yg67jPX/QIOkQei8KYyuLmG6hcKCpr0I0ASTXdVibZax5xt99vOcNukiICIG7jkSmEwqJiEAhEREoJCIChUREoJCICBQSEYFCIiJQSEQEComIQCERESgkIgKFRESgkIgINEgOQ8CrOU4CGiSJCDRIEhECt0eaVAXJ9tXKY+E+ykFP5ZBLOdUjTyRnPBvQINkv1SKQNGGaO1j5j8FfPuvQINk3iuBJBzRIEhFokCQi0CDZbPGy4akg+ejzyhnmdv6Y7Le2+VVkIpVW6fP5DZQ3LSQ7qnDbFRwtt0p3DNkrBSdM2gbJylbMPvalhkzEvzu73GjSN/1M81KE3fcWcD3u2wbxhwZJIkLgriOR6YRCIiJQSEQEComIQCERESgkIgKFRESgkIgIFBIRgUIiIlBIRAQKiYhAIRERKCQiAg2SgW5/eqBBMuhMiauXBskzYd9HzqI2AdwjTcogeVr7ubwyLvf1SmhrjmM/557XCnnN80qtEN92u6//vGvILWVRQQXZpWCvSjRI2iM5pf0Kilhzjxl7yS57uwqyn2soO+dhK+Y5r7J1CO3AhGmWkYFSbbLrvO171Q0YyBwEu8buWIVUXPdutFs399vYBslVr0HSdXbYBsk64BQvlq9C1L19A5kPnUdzGjTfV9vEk47Xbm4Fawmg+KUi90TTxxfCSjLuulZOm/c0QIMkAHuvI9G+Ae1C69HFywbwTDl6+WLrwQUNBiycWoly0KlMCBokRduvwHoJwPnjePGsAigV3irPXgBNab60YB89Zd4B3hep0CAJoHODrrQ/IG4oOy7hzh4Qv6asKYoBs1QoAomoXdRwBipRsoKkfQQb3dofaEUwEMcd6Lrt0jU2y54S70YCuKPrqAB26Gxu+ntVopxbRDSSRXZJh+VXMj4g0CApxXEJ6aVDRH2/Xdl7wsMZLqQcuOtIZDqhkIgIDG1EBK5IRAQKiYhAIRERKCQiAoVERKCQiAgUEhGBQiIiUEhEBAqJiEAhEREoJCIChUREoJCICBQSEYFCIiJQSEQEComIQCERESgkIgKFRESgkIgIIxJSl5yRPrVkJ8qUpNWTZTR5L0e6InlzRrYll5oQU5lHcgoYY2jzJpcKBHMr2DGDnQltWpjcHukoBz2VQy6lQ3fDizckttLMdMnBqOZ99IRN/3Y68ki2hzZPHsn257vlkewyN/e8XFvKnFPmmM8pY/CmtumaX9PvvWzLiTnyVbgxEp40thcWGtvfqM+dNO5/vNBY2HliP/xmu7HgOcc+niqdKMdTjfuvlNcubDeeKO0vfHy/cdJoNBqv7jdSblu92mk0nuwoY3h1v5Fyj3nHfFJKtfpz2ve+rn1+/nO32+kyNk//7XP0e7+ax9rm0eW9dB/79OOOQYiRrkjenJExZKHkBAIANRHp8SMcVg1E33PSvsyvIhNREmgBSp5FOxGWcX3Rydeo5HXsox1fjg49iVE7Uzf3mUfStx11bHGsNVPbzK1gLdFtjnYmtyan55lU3ksn+5ybS8nJDjdKRppoKz5IYqiXFirQsHbW/cqQ7dSfW0Akiounnzp8Oy8tVFBERW/LKZd4AfTsefA8k7W8bodxAIgYMPqfwlBMNmObygUNBg5hHQPhs4hpyHZClzSgakHJ8jgUPdu5oMFAHGu+GXl7rZin5Jl82fb4uIQ7e0pKZScJ2CgJzgXJuUVE1RB0dBdZNUSNup35qCeUdeQA7xffdtSxFXHHvYZjb7z7uaYzeJ5JJzEqgNpfstMd2gajmem2tXzHd80hvpr3bseTR/KP6uva80ganhzg/WMnWdXXdRQBGJsZxN2PsXNsSBRgLofQe0VC7zyT7cytYC2RRdIZQ3y3gPhe0pNxVxom2ho5NeT0O9ACnrn/rAQntM0KxyWklZBjhzYN2gyLCOCKNBI835imoI6IBBQSEYGhjYhAIRERKCQiAoVERKCQiAgUEhGBQiIiUEhEBAqJiEAhEREoJCICDZIjNkh29dHNmDmTBklpeghkls2ZNEiO2CAZTpkwU4PfZzlt0CApapCsIbeURQUVZJfs1zdXoY6+2+nW97Qg6pJzOccGSU+b3v767bvdDDkN0CDZRMogOQxHhyhGMlhtvhfzq8hE1L6DDw2SDlIGyWGoP7eAahExPet53rheB+bP4rIbH8GxI82IQXIYQpc0IBJFOb8y9r6lCM4FyVkxSA7DfBTxahZ3m6HM2XjnGNqGYUYMknOLiEayyC7psHZNRNUe+u4bMDbL/W8LAgBdJESE4IQ2MtVQSEQEComIQCERESgkIgKFRESgkIgIFBIRgUIiIlBIRAQKiYhAIRERKCQiAoVERKBBcsKOjVnxutEgSUSgQZIVJEWgQVK6guRRzltsRu3DqQqQy7fPb/oZo5DqKBWKQCLaug+6WgSSJkxzBytzdZRSSVibZTsU7sZRXPfuXypbFqKmCdMsIF7NIvYJsGmaMA8yMNyb57u3E1reQSEBu5BMh43adslqTjgubwLZJbX6UAVFrNltHmRg7CWHFEIR1mV7bNN0T/Zp0CDZZGwGySGcMVMADZIOkzRIzgLBuY50QYMBC9ZZv4oP2Y5qkCSDExwhzYpB8oIGQ23nq8ORV28MAjRIukgZJL3VG+0KkqOtJxsEaJAkIgQntJGphkIiIlBIRAQKiYhAIRERKCQiAoVERKCQiAgUEhGBQiIiUEhEBAqJiEAhEREoJCICDZIBKWk17X47GiTPEaOcOw2SATFITnulSRokpQ2Szlg7z3PmkM8pfbR8c+pqYf9eUtpR/HWOAbO0n/Z5nwaYuzSjqSd4fitInpRSrfOcsajjas3B+350VJpU2n+yo8zVed+876P3fXLn3qOapTQ0SDaRNEju3XFWsxBW8l5vX2sOIWhXerShVJQMf5iBUT3EI/dLgTIWdX7Hj3BYjWNt2Zn73ArWEn3MXQAaJB2kDJKh5R2UkUZsSYddD9JA5mCIfdgVrVUEsEO4GjS3PUWQLy1UUERFL3rbSoy+nGFw7EgzVEEytLwDc9n+vZbXkfykhMX84mCNPLVQR9gey7EFC1DEZCnzq8N6CuAynLnHsWYOYaM6I8G5IDkjBsn2r9gXLxve1aVflFBW+0sWlUgUi+4fRpf5zS0iGinizn4zlNkb7/T+lIe2wZgNg2Q4VUYmFYPeLAWJOApmGBj0UmxCg+WOJY6Cqda7jUN71uqjNb/OuSNRgOnsmTxzF66fS4NkAKnldSThl3oH9tf/daAwgfDVi+CENjLVUEhEBIY2IgJXJCIChUREoJCICBQSEYFCIiJQSEQEComIQCEREf4ffYTzpExMOBIAAAAASUVORK5CYII=">

**Comment by extinah** [comment]
Need hex codes for theres. also a sample of promotions.
![image](https://user-images.githubusercontent.com/33840424/200917798-8046b1f2-a0ef-4832-a834-583f36ce270d.png)

![image](https://user-images.githubusercontent.com/33840424/200917937-229c4e0d-304e-4580-ab4b-2baf6a94047f.png)

**Comment by hamiltonryan** [comment]
> ![image](https://user-images.githubusercontent.com/20782462/200917298-37855e86-d06f-4797-a702-2261c04bf380.png)

@artuoma 
Just to make sure I'm reading this right, would you like me to ask for the promotional search to be disabled?

**Comment by hamiltonryan** [comment]
@extinah Here are the Hex codes we are using. Is there anywhere specific that would be better for to put these?

Title:                    046B99
URL:                    72717C
Description:        3B3A48

**Comment by extinah** [comment]
Nope, this is good for now (once it's ready for dev, they can grab these). Thank you :) 

If you look at my comment from nov 9, all those items could/should have hex codes (probably the same ones repeated). That's a screenshot of the search console where David G / Linda T enters them in for us.

**Comment by hamiltonryan** [comment]
I'll try to see if I can get the rest. Promotions are disabled though, so we don't have to worry about those. 

The changes to the search page are already live though, what needs to be ready for dev at this point?

**Comment by extinah** [comment]
Ryan - we can chat :)
