### ISSUE TITLE
Fix right arrow caret display in accordion and other places where applicable.

### ISSUE THREAD

**Issue by artuoma** [Office-of-Digital-Services/California-State-Web-Template-Website#821]
Need to make accordion caret right arrow more visible by removing any curvature or rounded corners. Consider using icon font caret. 

Also in Chrome there is a weird line that appears at open/close animation.

**Comment by artuoma** [comment]
![image](https://user-images.githubusercontent.com/20782462/200918501-63beac87-adfe-4281-9507-1b26ad2d408c.png)

**Comment by yesenia-gtz** [comment]
unable to replicate carrot linen issue.

Corrections:

- [ ] make right arrow more visible by removing any curvature or rounded corners.

**Comment by kkoryaka** [comment]
@sharon-rabang please update figma design

**Comment by sharon-rabang** [comment]
@kkoryaka I'm not experiencing the caret line issue like Yesenia, either.

Based on her proposed correction, can we use the same link grid caret for consistency?
![image](https://user-images.githubusercontent.com/99768807/202815952-70976b99-d579-42f4-8495-f7246658614e.png)
Here's the updated example in Figma: [Accordion](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A5869&t=5FrWSRnN8WnHjo18-1)

Let me know if this proposed correction sounds good. Thanks!

**Comment by kkoryaka** [comment]
@sharon-rabang this si now updated: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/accordion.html

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
