### ISSUE TITLE
CSS Classes: Utility classes

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#823]
Work on design and content. 

https://beta.template.webstandards.ca.gov/get-started/css-classes-shortcuts/utility-css-classes.html

**Comment by yesenia-gtz** [comment]
**Beta feedback:**
Review placement of bootstrap classes for easier website migration

Why are bootstrap classes being applied to state template components (similar to in-line styles)?

* Instead, use bootstrap classes in the stylesheet. This is a better way to code.

* This also makes it easier to migrate websites.

Example:

https://beta.template.webstandards.ca.gov/components/parallax.html

**Comment by ashleydraper** [comment]
The **[utility CSS classes](https://docs.google.com/document/d/1mX673-lvXYLgOMRHRUX1ef9RXbNsBFxyz37oP2XP00k/edit#)** page is ready for review.

**Comment by extinah** [comment]
For @kkoryaka  and @artuoma  review
https://docs.google.com/document/d/1mX673-lvXYLgOMRHRUX1ef9RXbNsBFxyz37oP2XP00k/edit#

**Comment by rkojik** [comment]
Solid list and great job working through balancing plain language and technical accuracy. Approved.

**Comment by yesenia-gtz** [comment]
@extinah Leads review complete, ready for dev?

**Comment by extinah** [comment]
Ready for dev.
@kkoryaka  NOTE: We removed the spacing classes and moved them to the spacing shortcuts page.

- **Google doc:** https://docs.google.com/document/d/1mX673-lvXYLgOMRHRUX1ef9RXbNsBFxyz37oP2XP00k/edit#
- **Figma**: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1611%3A14325&t=DZuazBLKcXH8zHvW-4

**Comment by kkoryaka** [comment]
@extinah I propose to keep all the classes. I would like to make this  one on stop shop with all utility classes included, not just part of it.

**Comment by kkoryaka** [comment]
@jon-grant-state-ca-gov please take this one on also. And don't rush to remove the spacing classes. I will talk to @extinah and i will strongly recommend to her to keep all the classes in one place

**Comment by jon-grant-state-ca-gov** [comment]
@sharon-rabang  Content updated from most recent Google docs

**Comment by jon-grant-state-ca-gov** [comment]
@extinah I added the full table at the bottom for now and will see about adding that 'Show More' feature in the meantime

**Comment by extinah** [comment]
Approved. Thanks!
