### ISSUE TITLE
CSS Shortcuts: Gradient backgrounds

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#824]
Add in 1-2 intro sentences. Work on a friendlier design.

https://beta.template.webstandards.ca.gov/get-started/css-classes-shortcuts/gradient-backgrounds.html

- [x] Content (Ashley)
- [x] Design (Ryan)

**Comment by ashleydraper** [comment]
Here is the google staging doc for **[gradient backgrounds](https://docs.google.com/document/d/11m-t25AW9pcBuAfqF1YeU7xAAZ4hdgWCaUBXAsQPLTg/edit#heading=h.4iqtaxlhjf2n)**

**Comment by extinah** [comment]
Ready for review and approval

- **content**: https://docs.google.com/document/d/11m-t25AW9pcBuAfqF1YeU7xAAZ4hdgWCaUBXAsQPLTg/edit
- **figma**: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1454%3A13406&t=DZuazBLKcXH8zHvW-4

**Comment by yesenia-gtz** [comment]
@extinah  @sharon-rabang  @hamiltonryan Content approved, layout needs update for "On this page" to align with updated design decision (remove top line)

**Comment by kkoryaka** [comment]
@extinah looks good

**Comment by kkoryaka** [comment]
@timothyshambra this is now yours

**Comment by extinah** [comment]
@timothyshambra 
Can you make the source tab look like this:
https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1693%3A14995&t=fIBhTLO0IiXatNfN-1
![image](https://user-images.githubusercontent.com/33840424/208156926-2dd8facb-e562-41ad-8481-5532b259e217.png)

**Comment by hamiltonryan** [comment]
Looks great, Thanks @timothyshambra !
