### ISSUE TITLE
CSS Shortcuts: Spacing

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#825]
Content review/clean up/design.

https://beta.template.webstandards.ca.gov/get-started/css-classes-shortcuts/spacing.html

**Comment by yesenia-gtz** [comment]
**Beta feedback:**
Review css shortcuts page for broken links

> https://beta.template.webstandards.ca.gov/css-shortcuts/css-units.html
> I clicked, hoping to see something in my wheelhouse, but got a "this thing is broken" message instead. :sadface:

**Comment by ashleydraper** [comment]
Here is the google staging doc **[spacing classes](https://docs.google.com/document/d/1uK6kFf2wFlePzf5O2vuDv7YbnU15pznczJ7uBTTLZV4/edit#)**

**Comment by extinah** [comment]
@sharon-rabang look to this page for example inspiration
https://www.w3schools.com/css/css_padding.asp

**Comment by ashleydraper** [comment]
Not at all the expert on this content, but happy to huddle on it. The **[google staging doc](https://docs.google.com/document/d/1uK6kFf2wFlePzf5O2vuDv7YbnU15pznczJ7uBTTLZV4/edit#)** is ready for review. There are 3 decisions needed for design.

Cc: @extinah @sharon-rabang

**Comment by extinah** [comment]
@ashleydraper: @hamiltonryan and I can take a look at the content/design based on some of @kkoryaka feedback.  We think some explanation is good but could be condensed.

**Comment by ashleydraper** [comment]
@extinah Have at it

**Comment by extinah** [comment]
@ashleydraper  Here's the updated figma and content doc for your review. Ryan and I spent a lot of time on this one :)

- **Doc**: https://docs.google.com/document/d/1uK6kFf2wFlePzf5O2vuDv7YbnU15pznczJ7uBTTLZV4/edit#heading=h.wiubham1zko
- **Figma**: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1454%3A13270&t=2QpIr3lLXHAmUJ5q-1

**Comment by ashleydraper** [comment]
@extinah  Done with my review! The sample is AWESOME!! Exactly what I had in mind. Ready for dev.

**Comment by extinah** [comment]
@artuoma  @kkoryaka  @rkojik  ready for your review
Doc: https://docs.google.com/document/d/1uK6kFf2wFlePzf5O2vuDv7YbnU15pznczJ7uBTTLZV4/edit#heading=h.wiubham1zko
Figma: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1454%3A13270&t=2QpIr3lLXHAmUJ5q-1

**Comment by yesenia-gtz** [comment]
@ashleydraper @extinah can one of you update the content doc to align with the design updates made in today's discussion? after that is this ready for dev?

**Comment by extinah** [comment]
@yesenia-gtz  Done! :)

**Comment by extinah** [comment]
Approved by all in the meeting. ready for dev. :)

**Comment by kkoryaka** [comment]
@jon-grant-state-ca-gov could you please take care of this one.

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov Thanks! Here are some changes to make:
- Using the spacing class: 
-- Change the "m-a-lg" font from bold to regular (it looks like an H2)
-- 3. Size: Use capital "N" in "0: No spacing"
- Sample
-- Code: Apply red font color #D11A6C to m-a-lg p-x-100 p-y-lg
![image](https://user-images.githubusercontent.com/99768807/206536383-12eb8da0-73fb-48de-bef4-c9a9befff799.png)
-- Margin, padding, content image: Add a space between this image and the next line of text (too close).
- Spacing class shortcuts table: Add after dev discusses this section with @extinah.

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov Thanks for the updates! The only correction to make at this time:
- Sample, code: Change the red color of the last 2 characters to #3B3A48
![image](https://user-images.githubusercontent.com/99768807/206797191-46c907f3-39b8-42c5-b78e-f95839395345.png)

**Comment by jon-grant-state-ca-gov** [comment]
@sharon-rabang Now the color is correct :)

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov Sample code color fix looks good, thanks!

Will keep this issue open for the last item to address:
- Spacing class shortcuts table: Add after dev discusses this section with @extinah.

**Comment by sharon-rabang** [comment]
This issue is related to the Spacing content question in [#823 Utility classes.](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/823).

**Comment by extinah** [comment]
As noted on #823 , we will provide the spacing classes in both places (if @kkoryaka is good with that).

**Comment by extinah** [comment]
UX QA: Approved for now. I'll create another git backlog issue to work on the show more. Thanks.
