### ISSUE TITLE
CSS Shortcuts: Text accents colors

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#826]
Review content/page design.

https://beta.template.webstandards.ca.gov/get-started/css-classes-shortcuts/text-accent-colors.html

**Comment by extinah** [comment]
@kkoryaka  We would like to remove "text-highlight" since it doesn't seem ideal. Can we discuss?

UX review of design: Ryan to work on making the colors into a table (vs source code view) for consideration. 

Content still in progress. @ashleydraper to chat with rest of UX team about content.

**Comment by extinah** [comment]
@kkoryaka  @rkojik  @yesenia-gtz 
Ready for review. Also - not sure if this page is needed if we already have type ramp and color themes.

- **content**: https://docs.google.com/document/d/1eTNrmkxDk8lIiezHy_L33XXlvhUkBXK-dL1wYke47mk/edit
- **design**: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1454%3A13542&t=DZuazBLKcXH8zHvW-4

**Comment by rkojik** [comment]
Only one comment, recommend we link to a contrast checker here somewhere. Looks good though aside from that! Great job.

**Comment by sharon-rabang** [comment]
This is the contrast checker we link to from the [Color themes](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/color.html) page: [Accessible WEB](https://accessibleweb.com/color-contrast-checker/)

**Comment by rkojik** [comment]
Yeah, or we could link to the color themes page. That could work too!

**Comment by sharon-rabang** [comment]
@yesenia-gtz Yes, this page is ready for dev if @kkoryaka has no additional comments. Thanks!

**Comment by kkoryaka** [comment]
@timothyshambra this is now yours

**Comment by extinah** [comment]
Link added and works. Approved. Thanks!
@timothyshambra

**Comment by extinah** [comment]
@yesenia-gtz  Sorry, we need to reopen this. My mistake. I only validated the link for an accessibility checker.

The design (by Ryan) needs to be validated. The design changes didn't happen yet. 

Assigning to @hamiltonryan to compile a list of fixes.
@timothyshambra: the new design wasn't implemented. If you and Ryan wanna chat about moving forward (should he write out all the fixes first, or allow you to code the changes first), that'd be great. The latter seems less time consuming.

**Comment by yesenia-gtz** [comment]
@hamiltonryan @extinah moved to UX in progress

**Comment by hamiltonryan** [comment]
Worked with Tim on new design, which is now complete in Figma. I reviewed it with Sharon and Christina on Friday, and now it is ready for Leads review.

[Figma Link](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2343%3A18130&t=z4fZeZxaMkrUozZd-4)

**Comment by extinah** [comment]
Love how we simplified it. Approved by me. Also adding @rkojik

**Comment by yesenia-gtz** [comment]
@extinah @hamiltonryan looks good to me, Approved

**Comment by hamiltonryan** [comment]
@timothyshambra Looks great, I'm happy we made the change!
