### ISSUE TITLE
"On this page" Page navigation Component

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#831]
- [x] Design
- [x] Content

**Comment by sharon-rabang** [comment]
11/17-11/18: UX Team shareout of proposed "Side nav" and "On this page" designs

Reviewed and approved:
-- Both proposed designs
-- Prototypes for https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/827 Usability testing and as a live example for the [https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/587] Side nav component multi-level list
--- Will create new GitHub issue to develop this in another environment
Content updates about design and usage will be made for
-- https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/587 "Side nav component"
-- https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/831"On this page" component

**Comment by sharon-rabang** [comment]
@hamiltonryan Working on functional specs and usage content

**Comment by sharon-rabang** [comment]
@hamiltonryan Updating all Figma pages with the "Side nav" design and "On this page" design

**Comment by sharon-rabang** [comment]
Related to [#854](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/854) "On this page" (template site): Mobile view design

**Comment by extinah** [comment]
@hamiltonryan for content
https://docs.google.com/document/d/1F-V-Fon-51ndCJ9Xlf8dYw_uHdAbLJRXnFtneKh72Ko/edit?usp=sharing

**Comment by hamiltonryan** [comment]
@extinah @ashleydraper 
Added content to the Word Doc. Could probably use a content review.

**Comment by extinah** [comment]
@hamiltonryan  both ashley and i reviewed. let's chat tomorrow! :) almost done and then it can go to leads review (art, koji, kon).

**Comment by extinah** [comment]
Updated on this page component (removed top line)

**Comment by extinah** [comment]
Content finalized. Ready for review.

- **Content**: https://docs.google.com/document/d/1F-V-Fon-51ndCJ9Xlf8dYw_uHdAbLJRXnFtneKh72Ko/edit#
- **Figma**: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1648%3A14902&t=DZuazBLKcXH8zHvW-4

**Comment by yesenia-gtz** [comment]
Content and layout approved for me. Nothing crazy came up..

@hamiltonryan @kkoryaka @extinah

**Comment by kkoryaka** [comment]
@extinah looks good to me!

**Comment by kkoryaka** [comment]
@sharon-rabang I have added on this page navigation on all pages. Please review.

**Comment by hamiltonryan** [comment]
@kkoryaka 
Here are the specs for this one:

Page Navigation style and logic

Style

On this page

Font color: Gray 900
Font: 18/28
Line height: 28
Links

Font color: primary
Font size: 14/28
Paragraph spacing: 0
Gray lines

Color: #D4D4D7 (gray 200)
Line weight: 1 pixel
Line width: Full column
Distance from links: 14
2 columns

Second column starts at 50% of column width.
Logic
Anchor links will be automatically populated by H2 headings

Do not display if only 1 H2; display if 2 or more H2s
When links number five and under, they appear in one column
When links number six and over they split into 2 columns
When split in two columns, link number is devided in half, with the first half on the right and second half on the left
If the number of divided links results in an odd number, the second half should always be the odd amount

and here is the Figma page for it too:
[Figma page ](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1648%3A14902&t=1loi4OFuPs8xIMyp-4)

@sharon-rabang @yesenia-gtz @artuoma

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! Our UX review helped us identify one change to make:
- Gray underline: Extend to the full width of the page's body content for consistency.
![image](https://user-images.githubusercontent.com/99768807/206821219-886e0c05-0022-4c5c-a5a7-4e9d0908a7ce.png)
We've updated the pages in Figma to reflect this change.

**Comment by sharon-rabang** [comment]
@kkoryaka Here are additional changes to make. 
Fix broken links:
- About page: Looking ahead
- Link Grid: Usage
- Icons: Delete - Do's and don'ts for icon use

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!

**Comment by extinah** [comment]
@kkoryaka @yesenia-gtz 
This needs to be developed. The actual component was created, but the page itself wasn't added (would also need to be added to the component list and QA list)

**Comment by extinah** [comment]
@kkoryaka  Just making sure this component automatically generates (not a manual process). Thanks!

**Comment by yesenia-gtz** [comment]
Content finalized. Ready for review.

Content: https://docs.google.com/document/d/1F-V-Fon-51ndCJ9Xlf8dYw_uHdAbLJRXnFtneKh72Ko/edit#
Figma: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1648%3A14902&t=DZuazBLKcXH8zHvW-4

**Comment by kkoryaka** [comment]
@sharon-rabang I have added on this page component, please review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/page-navigation.html

**Comment by extinah** [comment]
@sharon-rabang content looks good to me. I was wondering if the on this page heading should be pushed back a little (less dark, etc). Just a thought when looking at it in dev.

**Comment by sharon-rabang** [comment]
@extinah Great design catch for better type hierarchy, thanks!
@kkoryaka
- Web page: Content looks good, thanks! 
- Website: Change "On this page" font color from Gray-900 #3B3A48 to Gray-700 #5E5E6A
-- I'll update all instances in Figma
cc: @hamiltonryan

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!

**Comment by extinah** [comment]
@Greg-Watanabe 

update font size for the page navigation links to .85 rem + .1vw


cc: @pglomboy

**Comment by yesenia-gtz** [comment]
@Greg-Watanabe ready for you

**Comment by Greg-Watanabe** [comment]
@extinah @pglomboy @sharon-rabang @hamiltonryan 
Font size update is done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/icons.html

**Comment by sharon-rabang** [comment]
@Greg-Watanabe @extinah @hamiltonryan @pglomboy 
Looks good to me. What do you guys think?

**Comment by pglomboy** [comment]
looks good to me, and aware that the fixes on the search icon button is still in the works. @sharon-rabang @extinah @hamiltonryan @Greg-Watanabe

**Comment by hamiltonryan** [comment]
Looks good to me as well! Thank you @Greg-Watanabe !

@sharon-rabang @extinah @pglomboy

**Comment by yesenia-gtz** [comment]
Closing this out

**Comment by extinah** [comment]
Look great all. Thanks :)
