### ISSUE TITLE
Beta feedback: Refine use of gradients

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#835]
The use of gradients on the artwork around the bear is not as refined polished as it could be - the design rules between having borders (of different line weights) & not do not seem consistent. It gives an unpolished effect - along with many shades of blue. For a design system or template, we would want a show of strength in design clarity and strong consistency.

**Comment by extinah** [comment]
This doesn't seem relevant anymore. We did a lot of work on this between the beta and production release.
@sharon-rabang, please validate if this feedback is relevant anymore. Thanks.

**Comment by sharon-rabang** [comment]
@extinah This issue hasn't been addressed yet.

Homepage hero banner and 'Partner with us' section:
- In Figma: We haven't revisited the pyramid shapes' gradients and outlines
- In production:
  - The hero banner's largest pyramid behind the bear has outlines with distracting moire patterns
  - The 'Partner with us' yellow pyramid's outlines need to be adjusted to look consistent (if we continue to use outlines).

**Comment by sharon-rabang** [comment]
Discussed with @extinah to keep this in 6.1.2.

**Comment by extinah** [comment]
Bear was fixed!
