### ISSUE TITLE
Beta feedback: Ensure state technologists understand strategic communication on Design System

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#838]
Content / communications - "move to the Design System" - is becoming internal jargon that our team is comfortable with, but the many technologists at the state will need to catch up on & may appreciate some clear strategic communication (and hopefully they are asking you questions about this). The chart and other text, labelling is clear.

* No link to design system - assume that is intentional for this project. But worth rethinking: the design system is a system for design - it is a set of principles and approaches, which include supporting technology.

* Remember: The state has, and will continue to have, a VERY HARD TIME bringing in UX, Research, Design, Content, PM talent & these links include content and other guidance - and also for leadership to hopefully adopt user driven service design.

**Comment by ashleydraper** [comment]
Let's tackle this post production

**Comment by extinah** [comment]
@ashleydraper Changing this to in progress, if you have bandwidth. Let me know if you don't. If you can set up a small meeting with you and me (and put @yesenia-gtz as optional) we can chat about some strategies. Thanks!

**Comment by ashleydraper** [comment]
@extinah Do you envision the scope of these changes going beyond the homepage?

**Comment by extinah** [comment]
I think it's where we mention the design system (which isn't many pages). This seems like it includes:

- homepage
- what's new
- about

Hope this helps!

**Comment by ashleydraper** [comment]
@kkoryaka Will you please update the homepage (as pictured) with this link to the design system:https://designsystem.webstandards.ca.gov/? 

![image](https://user-images.githubusercontent.com/62437425/212201321-b8d3b91d-e0e5-461c-a1eb-2abd18bffab3.png)

**Comment by kkoryaka** [comment]
@sharon-rabang the link is now added https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/

**Comment by ashleydraper** [comment]
@sharon-rabang @kkoryaka Looks good to me!

**Comment by sharon-rabang** [comment]
@kkoryaka @ashleydraper Looks good to go, thanks!
