### ISSUE TITLE
Strategy for publishing vision, mission and strategy for Design System on website

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#839]
V6 Beta feedback:

> ROADMAP: A "message from leadership" about this would be something I would want to see - maybe on a page about "Design System status" and progress - and kinds of resources or other not-overwhelming strategy notes for departments. You have the template updates / change-log page - the other important feature in communicating technology is the ROADMAP - which needs to be communicated and prioritized by leadership - it can be general, but enough detail.

**Comment by extinah** [comment]
Content added to homepage. Archiving now.
