### ISSUE TITLE
Download and setup (beta feedback)

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#840]
Beta feedback:
CDN links go to old code currently - that's confusing (5.6.2 - https://template.webstandards.ca.gov/cdn.html) - will you have a page that matches the code version for 6.0.8 Beta?

* This step still oversimplifies the realistic needs of State tech teams

  * "Select a framework

  * Current frameworks include HTML, Eleventy, NET core, MVC, and React. You’ll usually pick the framework you’re currently on.

  * ..."From your code comparison, make the necessary changes and updates to your code."

Edited to include this issue with this card #819  (closing out the other issue - similar improvements)

Create HTML content (like eleventy)
Separate out two new pages (eleventy and HTML)

Kon: Please write out the HTML like the "Using eleventy" section.

https://beta.template.webstandards.ca.gov/download-and-setup.html

**Comment by kkoryaka** [comment]
@Greg-Watanabe  @sharon-rabang please work on the first section https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/download-and-setup.html

**Comment by kkoryaka** [comment]
@Greg-Watanabe please fix the link on set up and download page.

**Comment by kkoryaka** [comment]
@yesenia-gtz we need discussion on this

**Comment by yesenia-gtz** [comment]
@kkoryaka Ill set up the meeting, please note the issue is from beta feedback survey. I think the team can focus on the user flow and understanding the disconnect listed in the feedback.

**Comment by yesenia-gtz** [comment]
Page links will be updated in Production release.

@hamiltonryan 

**Research needs:**
- User interviews on how state teams interact with template
- understand steps for implementation
- Identify various scenarios
- What content guidance is needed to best support teams?
- Understand state team skill levels (might not be a tech savvy person)

**Opportunities:**
- Add instructions to Github Readme, update content to reflect what is on state template website
- use content from readme to update website content where appropriate

**Comment by extinah** [comment]
@hamiltonryan Assigned to you. Please start working on this. Can you set up a meeting for us to discuss? Thanks!

**Comment by extinah** [comment]
@hamiltonryan I don't remember if we talked about a list of people we can interview (or to create an email to the DWSN for folks to join a workshop/interview). If not, here it is.

**Comment by hamiltonryan** [comment]
Discussed with Art and Koji. To start addressing so of the feedback we are getting we can default to the HTML version of the template. Break the "Using Eleventy out into it's own section and look expanding to cover basics of the other frameworks, or linking to their sites for further information.

**Comment by hamiltonryan** [comment]
@kkoryaka @carterm @extinah 
Per our leads review the updated Download and Set up page is ready for Dev.

[Figma Link](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2673%3A19028&t=NrrT1ngTJMVQecis-4)

**Comment by kkoryaka** [comment]
@hamiltonryan this is now in staging: https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/download-and-setup.html

**Comment by extinah** [comment]
@kkoryaka we need to make some slight tweaks based on dev feedback in a related meeting. @hamiltonryan will make the changes (it's just to the template frameworks - those will be cards instead of link grid)

**Comment by kkoryaka** [comment]
@extinah I will be off for next three weeks assign all the items to @carterm and he will assign to the rest of the devs

**Comment by extinah** [comment]
@hamiltonryan  please assign to @carterm (as lead) when you're done making tweaks to the content/design. Thanks.

**Comment by hamiltonryan** [comment]
@extinah. We met this morning to go over the content, and discovered there are areas to improve clarity around implementation. Scheduled a meeting to go over propose changes to the sub pages of download and setup. Once the decisions are made, I will update the figma and move this to leads review, and then over to @carterm for dev allocation.

**Comment by extinah** [comment]
@hamiltonryan I'm moving this to UX in progress (then can be assigned to devs, etc)

**Comment by hamiltonryan** [comment]
@extinah The Download and setup page is ready to go with all the updates. I'll move it to UX review, and schedule a meeting for it.
[Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2793%3A19054&t=VWo9eGsNWAJWe768-4)
[Google Doc](https://docs.google.com/document/d/1A--CplY-8qepW4dG_jG0Bdg-eiDgqZ5RQgt7lD8jVPo/edit#heading=h.nseh8nky297v)

**Comment by extinah** [comment]
@artuoma @rkojik @rkojik Ready for your review and approval.
[Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2793%3A19054&t=VWo9eGsNWAJWe768-4)
[Google Doc](https://docs.google.com/document/d/1A--CplY-8qepW4dG_jG0Bdg-eiDgqZ5RQgt7lD8jVPo/edit#heading=h.nseh8nky297v)

@hamiltonryan this looks great to me. much simpler.

**Comment by kkoryaka** [comment]
@hamiltonryan @extinah  this looks great. You have my approval.

**Comment by artuoma** [comment]
I added a bunch of edit to the Google doc - please review!

**Comment by kkoryaka** [comment]
@extinah this is now updated https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/download-and-setup.html

**Comment by extinah** [comment]
@hamiltonryan  please review. thanks!

**Comment by kkoryaka** [comment]
@hamiltonryan I added that structure that @artuoma  wanted on top but i can't exclude the real source files that are currently in the repo.  We don't have structure that Art want in actual repository at this point. So, I don't want to show what is not there and delete wha is actually in the repo. That would be misleading. We will wait for Carter when he finishes the core project then we will update this structure for good. But for now we have to show this.

**Comment by hamiltonryan** [comment]
@kkoryaka That sounds good. We can go with the backup plan for now and just remove the folder structure from the Download and set up page, and move it to the Using Eleventy page.

**Comment by hamiltonryan** [comment]
Looks good, thanks Tim! Moving to ready to close.
