### ISSUE TITLE
Review Mobile and performance metrics

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#842]
**Beta feedback:**
Mobile performance score is low. Many departments have more mobile users than desktop. 
Feedback from user: 
it’s all about the performance…and if we’re shooting for mobile-first…it needs some work. We are currently at 16M mobile users for the year, EDD is @ 23M…

For a website with very little content or images on it, it’s really heavy. Once we add all our “stuff”, the performance goes down even further. 

I’ve forwarded this to our accessibility experts to review as well.

https://pagespeed.web.dev/report?url=https%3A%2F%2Fbeta.template.webstandards.ca.gov%2F&form_factor=mobile

![Screen Shot 2022-11-17 at 10 21 44 AM](https://user-images.githubusercontent.com/98193284/202526864-1ad8022f-5aab-4e44-b984-a849a96cf6e0.png)

**Comment by kkoryaka** [comment]
@yesenia-gtz related issue #818 is assigned to Tim
