### ISSUE TITLE
Clean up accordion  in-line styles

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#843]
**Beta feedback:** 

[Accordions:](https://beta.template.webstandards.ca.gov/components/accordions.html)

Why is the style in-line (style height 2 pixels, etc)? This is across the whole site. Would like to just copy paste <cagov-accordion> in and that's it. Can't we target just the class or element?

< cagov-accordion>

 < details style="height: 2px;">

**Comment by kkoryaka** [comment]
Related issue #833 that is assigned to Greg

**Comment by kkoryaka** [comment]
@Greg-Watanabe this one is the same as #833

**Comment by Greg-Watanabe** [comment]
This has been fixed
