### ISSUE TITLE
Content clarity for nunjucks, eleventy, etc

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#846]
https://beta.template.webstandards.ca.gov/components/alert.html

“"nunjucks ... eleventy ...?"

sure hope you plan to explain — whether directly or by linking to a resource — what those are.”

Need to clarify what these items are for users.

**Comment by ashleydraper** [comment]
Let's tackle this post production

**Comment by extinah** [comment]
@ashleydraper Moved into in progress, if you have bandwidth. If not, let me know, 

Please do some interviews with our developers to get some insight on this content. You can probably test the content on some folks on Koji's team. Thanks :)

**Comment by ashleydraper** [comment]
@extinah Sounds good. Do we have a targeted deadline for this?

**Comment by extinah** [comment]
@ashleydraper Great. This is for the 6.1.1 release. It should be researched, drafted, reviewed/approved, and developed by 2/1/22 (if this is a heavier lift, it can go in the next release.)

We're proactively starting now :)

**Comment by ashleydraper** [comment]
Got it. Thank you

**Comment by ashleydraper** [comment]
Researching all mentions of nunjucks, eleventy and other technical jargon to create a scope of work. Once content pages are identified, will meet with devs for review of updated content.

**Comment by sharon-rabang** [comment]
@ashleydraper Are there google doc or Figma content updates I need to review or make with dev?

**Comment by ashleydraper** [comment]
@sharon-rabang Whoops, did not mean to assign this one to you!

**Comment by extinah** [comment]
@ashleydraper: can you give us the links for review? Wasn't sure all the places you updates. Thanks.
@hamiltonryan @sharon-rabang since this is in UX review, please take a cursory look at the content updates (once we have the links). This is to improve the content so users understand nunjucks and eleventy.

**Comment by extinah** [comment]
Closing issue. Created 2 separate issues. #1175 and #1176
