### ISSUE TITLE
Mobile navigation review

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#847]
The way the navigation stacks on mobile is awkward. If there were some way to simplify it would help tremendously. Perhaps the scale of the agency name and logo could decrease to make for more space? I know there are many ways to make the mobile experience feel more considered and I think navigation is the first place to start.

![Screenshot 2022-11-16 162301](https://user-images.githubusercontent.com/98193284/202529710-2cdfa3b4-bd6d-4ec5-a570-0197e3fac91a.png)

![Screenshot 2022-11-16 162359](https://user-images.githubusercontent.com/98193284/202529712-bcc4521d-6417-4597-bcff-ead721aa35b1.png)

**Comment by sharon-rabang** [comment]
UX team doing wholistic mobile design explorations with #[847](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/847), #[853](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/853), and #[854](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/854).

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @kkoryaka @extinah 
Here's the latest UX mobile design work for Leads review and approval. 

**02/14/23 Meeting notes**
- Approved UX mobile design changes and recommendations:
- Remove Settings iconMenu drawer modal animation on gray overlay
- Remove branding logo

**Review [02/15/23: UX Mobile Design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3120%3A46750&t=39dTXaYE1vYlbnMD-1) (Figma)**

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @kkoryaka @extinah
We've updated the proposed UX Mobile design with revised branding, and explored how the Color themes would work for other agencies.

Here they are for your review and approval in Figma:
- [Proposed UX Mobile Design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3168%3A32120&t=1RFnwCrZ7ADb7Qkx-1)
- [Color theme explorations](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3168%3A32476&t=1RFnwCrZ7ADb7Qkx-1)

@kkoryaka Under the color theme explorations, we noted one question for you:
If the menu modal's background color is set to "Standout", can we build in a color exception for Oceanside to use it’s Primary hover color?

Let us know if you have any questions or concerns, thanks!

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @kkoryaka @extinah @timothyshambra 

**02/28/23 V6 Mobile Nav Discussion - Meeting notes:**
- Menu with side nav in [Proposed UX Mobile Design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3168%3A32120&t=Wcrd3TOqqb9XgZS7-1): We will explore this proposed design further in the Design System, due to its high level of effort for the state template at this time.
- Side nav accordion in [Approved UX Mobile Design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3310%3A35075&t=Wcrd3TOqqb9XgZS7-1): We will pursue this design direction for the state template instead.

**Comment by kkoryaka** [comment]
Collapsed version
<img width="371" alt="Screenshot 2023-04-25 at 2 01 02 PM" src="https://user-images.githubusercontent.com/31669748/234420467-7fa283bf-11bb-4274-91b3-72c3f84f81b2.png">

**Comment by kkoryaka** [comment]
Expanded version
<img width="377" alt="Screenshot 2023-04-25 at 2 00 44 PM" src="https://user-images.githubusercontent.com/31669748/234420676-0da10684-3ce1-4f80-9613-099d83e4aa2e.png">

**Comment by kkoryaka** [comment]
New expanded menu version
<img width="377" alt="Screenshot 2023-05-09 at 11 05 32 AM" src="https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/assets/31669748/79a1d662-fa49-4ae8-a085-48827f0e40d4">

**Comment by extinah** [comment]
@sharon-rabang @hamiltonryan Can you both meet to divvy up what to QA? Thanks!

**Comment by sharon-rabang** [comment]
@kkoryaka:
@hamiltonryan and I have completed UX QA. Looks good to go, thanks!
