### ISSUE TITLE
Side nav (template site): Mobile view design

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#853]
Create mobile view design based on: 
- [#223](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/223) side navigation (template site)
- [#587](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/587) Side navigation (component)

**Comment by sharon-rabang** [comment]
UX team doing wholistic mobile design explorations with #[847](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/847), #[853](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/853), and #[854](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/854).

**Comment by extinah** [comment]
@sharon-rabang @hamiltonryan I'll set up a meeting for us to come together again.

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @kkoryaka @extinah 
Here's the latest UX mobile design work for Leads review and approval. 

**02/14/23 Meeting notes**
- Approved UX mobile design changes and recommendations:
- Remove Settings iconMenu drawer modal animation on gray overlay
- Remove branding logo

**Review [02/15/23: UX Mobile Design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3120%3A46750&t=39dTXaYE1vYlbnMD-1) (Figma)**

**Comment by kkoryaka** [comment]
@timothyshambra  maybe you can explore one more navigation option where we are duplicating the side nav in the main nav the way us design does here https://designsystem.digital.gov/components/overview/ 

So, we need to display main navigation dropdowns (subnav) in mobile but hide those dropdowns in desktop.
And vise versa with side navigation: we need to hide in in mobile but display it in desktop

Also, it would be great if both main nav's dropdown (subnav) items and side nav are fed from one json source in eleventy.

**Comment by hamiltonryan** [comment]
@timothyshambra Let me know if you would like a walkthrough of our latest Mobile Navigation designs for context on that too, if that would help.

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @kkoryaka @extinah
We've updated the proposed UX Mobile design with revised branding, and explored how the Color themes would work for other agencies.

Here they are for your review and approval in Figma:
- [Proposed UX Mobile Design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3168%3A32120&t=1RFnwCrZ7ADb7Qkx-1)
- [Color theme explorations](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3168%3A32476&t=1RFnwCrZ7ADb7Qkx-1)

@kkoryaka Under the color theme explorations, we noted one question for you:
If the menu modal's background color is set to "Standout", can we build in a color exception for Oceanside to use it’s Primary hover color?

Let us know if you have any questions or concerns, thanks!

**Comment by timothyshambra** [comment]
Looking at the code, it would require a major structural change to dynamically include the side navigation in the header based on the current page viewed. Currently we have one layout based on the page type, and the dynamic side navigation is pulled in from our content page. I would have to talk it over with @kkoryaka or someone else who is familiar with Eleventy to see if there is a better way of doing that.. but currently I do not think this mobile view proposal would be a simple implementation and would require a heavy structural change.

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @kkoryaka @extinah @timothyshambra 

02/28/23 V6 Mobile Nav Discussion - Meeting notes
- Menu with side nav in [Proposed UX Mobile Design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3168%3A32120&t=1RFnwCrZ7ADb7Qkx-1)](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3168%3A32120&t=Wcrd3TOqqb9XgZS7-1): We will explore this proposed design further in the Design System, due to its high level of effort for the state template at this time.
- Side nav accordion in [Approved UX Mobile Design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3310%3A35075&t=Wcrd3TOqqb9XgZS7-1): We will pursue this design direction for the state template instead.

**Comment by kkoryaka** [comment]
@sharon-rabang @extinah Based on what I see in figma this is one of those complex and time consuming items for development. I would suggest to move it to 6.1.2 release.

**Comment by kkoryaka** [comment]
<img width="371" alt="Screenshot 2023-04-25 at 2 01 02 PM" src="https://user-images.githubusercontent.com/31669748/234419185-7d876089-682c-4dd1-8e2f-f1e26538c3cb.png">
Side nav collapsed version

**Comment by kkoryaka** [comment]
Expanded versions
<img width="371" alt="Screenshot 2023-04-25 at 2 01 06 PM" src="https://user-images.githubusercontent.com/31669748/234419265-16f7437a-5d6d-4108-ae97-3e24bc5a383d.png">

**Comment by kkoryaka** [comment]
This is in dev now. https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/

**Comment by kkoryaka** [comment]
@extinah this is now implemented in dev https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/structure.html

**Comment by sharon-rabang** [comment]
@kkoryaka:
@hamiltonryan and I have completed UX QA. Looks good to go, thank!

**Comment by extinah** [comment]
Hi! Don’t click “close the issue” button. Just move to the column ready to close. We’ll close all of them after they go live. 😊

Christina Florente  |  User Experience Lead
CA Department of Technology  |  ODS Web Design and Development
916.215.5294  |  ***@***.******@***.***%0d>
