### ISSUE TITLE
"On this page" (template site): Mobile view design

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#854]
Create mobile view design based on [#831](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/831) "On this page" Component.

**Comment by kkoryaka** [comment]
@extinah what needs to be done? I checked the figma and I didn't see mobile version of it.

**Comment by extinah** [comment]
@kkoryaka nothing yet - this is still in the queue waiting to be started by sharon or ryan.

**Comment by sharon-rabang** [comment]
UX team doing wholistic mobile design explorations with #[847](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/847), #[853](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/853), and #[854](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/854).

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @kkoryaka @extinah 
Here's the latest UX mobile design work for Leads review and approval. 

**02/14/23 Meeting notes**
- Approved UX mobile design changes and recommendations:
- Remove Settings iconMenu drawer modal animation on gray overlay
- Remove branding logo

**Review [02/15/23: UX Mobile Design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3120%3A46750&t=39dTXaYE1vYlbnMD-1) (Figma)**

**Comment by sharon-rabang** [comment]
@artuoma @rkojik @kkoryaka @extinah @timothyshambra 

**02/28/23 V6 Mobile Nav Discussion - Meeting notes:**
- Menu with side nav in [Proposed UX Mobile Design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3168%3A32120&t=Wcrd3TOqqb9XgZS7-1): We will explore this proposed design further in the Design System, due to its high level of effort for the state template at this time.
- Side nav accordion in [Approved UX Mobile Design](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3310%3A35075&t=Wcrd3TOqqb9XgZS7-1): We will pursue this design direction for the state template instead.

**Comment by kkoryaka** [comment]
@sharon-rabang are there any changes to actual on this page component in mobile? I don't see anything so far. All of mobile improvements are related to other components as far as i see.

**Comment by sharon-rabang** [comment]
@kkoryaka No changes needed since the mobile improvements will allow this "on this page" component to move to the top of the screen. Will close this issue. Thanks for reviewing!
