### ISSUE TITLE
Develop side navigation example content

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#855]
Develop side navigation example pages with Figma prototypes for: 
- [#827](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/827) Usability testing
- Live example in "Multi-level list" section on [#587](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/587) Side nav component page

Figma prototypes:
- [Parties 1](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1381%3A12614&t=5FrWSRnN8WnHjo18-1)
- [Parties 2](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1381%3A12968&t=5FrWSRnN8WnHjo18-1)
- [Parties 3](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1381%3A13155&t=5FrWSRnN8WnHjo18-1)
- [Parties 4](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1381%3A13316&t=5FrWSRnN8WnHjo18-1)
- [Parties 5](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1381%3A13480&t=5FrWSRnN8WnHjo18-1)
- [Parties 6](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1381%3A13641&t=5FrWSRnN8WnHjo18-1)

**Comment by sharon-rabang** [comment]
Reassigning to UX Team - still making adjustments.

**Comment by extinah** [comment]
Also improve how the live examples open up (including for https://template.webstandards.ca.gov/structure/search.html). It can open in a new window with limited browser capability (like getty search). Hopefully this is accessible.

**Comment by extinah** [comment]
@hamiltonryan can you refresh my memory? Wondering why this is in ux internal review - do you have something for us to chat about? :)

**Comment by hamiltonryan** [comment]
@extinah This was way back when we discussed having a live example of the side-navigation from people to go to from the components page. We designed the pages, and they were ready for dev, but it was pushed out of the release, and then became a question of whether to include it at all. If anything it might be a leads review item?

**Comment by extinah** [comment]
Sounds good. I'll send it over for review.

**Comment by extinah** [comment]
Decision: Use website as an example. Add verbiage to component page. (provide content to lead them down a path).

**Comment by extinah** [comment]
@sharon-rabang  @hamiltonryan please review.

Updated content. Review the text highlighted in yellow.
https://docs.google.com/document/d/1hN7vXwYNvhaYJ2MsLYPlPPokBBQ_6Gtrs-XZnqaIkOA/edit#

Here's the text: 
**Multi-level list**
You can review a live example of this on our website. The Get started section goes 3 levels deep. Go to [Get started](https://template.webstandards.ca.gov/get-started.html). From the side navigation, select CSS classes shortcuts. Then select Utility CSS classes.

**Comment by extinah** [comment]
Sharon/Ryan reviewed and approved. Ready for leads review.

**Comment by extinah** [comment]
@carterm ready to assign. just a text update (see the google doc). Thanks!
https://docs.google.com/document/d/1hN7vXwYNvhaYJ2MsLYPlPPokBBQ_6Gtrs-XZnqaIkOA/edit#

**Comment by kkoryaka** [comment]
@carterm I will take care of it

**Comment by kkoryaka** [comment]
@extinah The live site button is added... but lI guess we don't need it anymore. So, let me know what we actually need. https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/side-navigation.html

**Comment by extinah** [comment]
@kkoryaka 
Hi there! Some next steps:

Add content per this google doc (highlighted in yellow - 2 sections.)
https://docs.google.com/document/d/1hN7vXwYNvhaYJ2MsLYPlPPokBBQ_6Gtrs-XZnqaIkOA/edit# 

Edits to the new sample site:
- Opens in a new tab
- Logo and home link goes to "Types of parties" landing page
- Disable search (can't type in it but still appears)

**Comment by kkoryaka** [comment]
@extinah this is now updated https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/side-navigation.html

**Comment by extinah** [comment]
@kkoryaka 
Sorry - it just doesn't look right without the button haha. I'll make this change also in the google doc. 

Can you make these updates:

- Update text: For an example that has 6 levels, review our live example.
- Add in button "Live example"

**Comment by extinah** [comment]
@kkoryaka see previous comment

**Comment by kkoryaka** [comment]
@extinah THis is now updated https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/side-navigation.html

**Comment by extinah** [comment]
@kkoryaka
- Change from "Live example" to "Live example in new tab" for accessibility
- Change outline and text colors from gray to Primary #046B99 for consistency
- Add arrow for consistency
![image](https://user-images.githubusercontent.com/33840424/226749807-47592a05-e976-4b6d-9b68-a83cf8e8f633.png)

**Comment by kkoryaka** [comment]
@extinah this is now updated: https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/side-navigation.html

**Comment by extinah** [comment]
https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/side-navigation-sample-level3.html

Fixes:
Typo: Drinks
2 cards need lorem ipsum (instead of placeholder text). 
- Decor: Usce efficitur ultricies erat, commodo auctor mi tempus.
- Surprise: Change title to Activities. Use this text: Curabitur faucibus venenatis libero ut.

Remove "Surprise?" from left nav
![image](https://user-images.githubusercontent.com/33840424/228067196-3c677de6-6a77-4e8e-a9aa-783eb21afa13.png)

Also updated in figma: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1381%3A13155&t=sLVPn7WKoK6G4wrp-1

Thanks!

**Comment by kkoryaka** [comment]
@extinah this is now updated https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/side-navigation-sample-level3.html
