### ISSUE TITLE
Download and setup: Fix featured cards

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#861]
- Design fix: Improve the featured cards section to help the links with external link icons display better.
- Content fixes: Update some headings with sentence case for consistency.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe 
- [Download and setup - Google doc](https://docs.google.com/document/d/1A--CplY-8qepW4dG_jG0Bdg-eiDgqZ5RQgt7lD8jVPo/edit#)
- [Download and setup - Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=967%3A11651&t=Hliuj6p7HhVOIxa9-1)

Here are the design and content fixes to make on this page:
**Featured cards section:**
- Heading: Change "Common V6 State Web Template file links" to “Common web template files” 
- Cards, outlines: Add 5px corner radius
- Cards, content spacing: Ensure there's 10px spacing between the bold headings and the start or bulleted links.
- Cards, bulleted links: 
-- Font size: Reduce to 16px/29px
-- External link icons: Enlarge icon sizes a bit so they have the same "x" height (lowercase text height) as the text for website consistency.
- Third card, link: Delete "Beta" so it's " V6 CSS/ JS core CDN links"
- After this featured cards section, add this sentence:  Here are the steps to follow when implementing the V6 State Web Template.
![image](https://user-images.githubusercontent.com/99768807/203189574-680991b2-f88a-4453-8dbf-caa16a570f71.png)
**Template implementation roadmap, Step 4**: Change "Or you can download...” to "You can also download"
![image](https://user-images.githubusercontent.com/99768807/203189740-5cfc4cd2-aaf1-49b9-bfba-6cbfaa49f7d4.png)
**Folder structure and files, table - left column:** Replace all dashes after the bold text with colons.
![image](https://user-images.githubusercontent.com/99768807/203189928-e7e47498-9e32-41ce-82f5-ff2d6857368d.png)
**Eleventy, Step 3:** 
- Are Google doc/Figma or Dev correct? Google doc and Figma say: “Step 3. Install Node.jk” 
Dev says: “Step 3. Install Node.js” Please correct in Dev if incorrect.
![image](https://user-images.githubusercontent.com/99768807/203190019-7fd11f1d-6fd0-46c7-b997-e7a0bb0f77f5.png)
- After code example (node   -v), add sentence:  This should print the version number. If you don’t have Node, you can download it from nodejs.org and install it.
**Eleventy, Step 4:** Delete duplicate sentence from Step 3:
Make sure your local machine has Node installed. To see if Node is installed, open Windows Command Prompt, Powershell or a similar command line tool. Type:

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/download-and-setup.html

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good to go, thanks!
