### ISSUE TITLE
Production release communication

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#875]
Production release communication to share with CDT Comms team.

**Highlight areas:**
- Feature improvements per user feedback
- Navigation
- New Patterns 
- New Components
- Getting started
- Next steps

Work with Content Design to QA draft before sharing with CDT Comms team

**Comment by yesenia-gtz** [comment]
@artuoma @ashleydraper @extinah  i've listed some highlight areas for the communication. not sure how we have done comms in the past. is there a process with Amy Norris? I will schedule a workshop for us early next week.

**Comment by ashleydraper** [comment]
@yesenia-gtz [**This draft**](https://docs.google.com/document/d/1hqydYKTOEmEjryuQUbt3OOwhwqmv8HIPGID5cbcGcMI/edit#) is still in progress, but wanted to make sure I'm on the right track. Is this too similar to the What's New page, or do we like this blog version?

Cc: @artuoma

**Comment by yesenia-gtz** [comment]
@artuoma This is ready for comms team review. Can you please forward the draft to them?

**Comment by yesenia-gtz** [comment]
Closing as draft has been shared with comms.
