### ISSUE TITLE
Bug: CDN blocks all requests from outside of the United States.

### ISSUE THREAD

**Issue by machikoyasuda** [Office-of-Digital-Services/California-State-Web-Template-Website#876]
**Description of bug:** Requests to the CA State Web Template CDN links are forbidden when browsing from outside of the United States. This leads to websites that use the CA State Web Template like https://ca.gov to look broken, because there is no CSS, no JavaScript, no images. This is also affecting https://benefits.calitp.org / https://github.com/cal-itp/benefits/, as this site uses a CDN link for the State Web Template.

**Screenshots:** 
Loading https://ca.gov from outside of the United States looks like this - 
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/3673236/204932633-0927125a-7079-4e51-a138-399247376b84.png">

In this screenshot, I am using https://www.opera.com/ browser's free VPN, set to Europe. As you can see, requests to CSS files https://california.azureedge.net/cdt/statetemplate/5.6.2/css/cagov.core.css return a 403. Requests to image files like 
https://california.azureedge.net/cdt/CAgovPortal/images/recovery.jpg are also forbidden.

**Versions affected:**
- Every CDN link here - like CSS files, jQuery/JavaScript files and images - https://california.azureedge.net/cdt/CAgovPortal/images/recovery.jpg returns a 403 outside of the United States
- Examples of images affected: https://california.azureedge.net/cdt/statetemplate/global/images/logo-and-bear.png
- Examples of sites affected: https://www.ca.gov, https://www.ca.gov/privacy-policy/, https://www.ca.gov/sitemap/ (does not load any links at all)

**Steps to reproduce:**
1. Use a VPN and set the VPN to a country/region outside of the United States. Alternatively, go to Mexico or Canada.
1. Open https://www.ca.gov/
1. Check the site to ensure the CSS files and images are loading properly

**Comment by param-pocham** [comment]
this issue is now resolved. Tested using VPN the site loads good with out any problems with CSS styles..

**Comment by machikoyasuda** [comment]
@yesenia-gtz @param-pocham Thank you for taking care of this issue quickly.

I've tested https://benefits.calitp.org/ with a VPN as well, and the CDN is loading properly. Closing this issue.
