### ISSUE TITLE
Tables - refinement

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#877]
Dev: Update striped color to match the design system.
Current: #f2f2f2
Design system color: Gray 75 (#F3F3F4)

Update table examples:
![image](https://user-images.githubusercontent.com/33840424/205184342-cb655ddd-12b9-4024-b0d0-c4bb6259f011.png)

Google doc examples: https://docs.google.com/document/d/1wti96QD3bOLNDnVat3PufHeComN2FF7U76S6VWTKG0g/edit#

**Comment by extinah** [comment]
@hamiltonryan to update figma tables component with real tables (not just screenshots)
https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=545%3A9460&t=CBCBzdXCI3cljNPk-1

**Comment by hamiltonryan** [comment]
@extinah 
The real table examples are done and added into the components page

**Comment by kkoryaka** [comment]
@jon-grant-state-ca-gov please update example modules with the new tabular data from figma

**Comment by extinah** [comment]
@sharon-rabang  please qa :) Thanks!

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov Thanks for making the updates! Here are some design fixes to make:
- Basic, Shaded, and Zebra examples: Change the fonts' color from #212529 to Gray-900, #3B3A48
- Basic and Zebra examples: Change the table headers' bottom dark stroke color from #212529 to Gray-900, #3B3A48

**Comment by jon-grant-state-ca-gov** [comment]
@sharon-rabang I noticed that the Gray-900 value is #212529.  
![image](https://user-images.githubusercontent.com/89486837/206284200-a003d388-8b2c-49a3-b95f-1543f745f1ab.png)

Did you want me to use that specific #3B3A48 value, or use Gray-800 (#343A40)?

Thanks :)

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov Thanks for sharing the Gray-900 value you're seeing on your end. I'm not sure if your screenshot colors are part of the same colors that I worked on with @kkoryaka. The gray values we use are from the [Design System colors](https://www.figma.com/file/3N4dFWhFqiGpWr1DRQoJUM/Design-system-colors?node-id=0%3A1&t=1mWZiYSDghmKMDmA-1), and our typography is set to Gray-900 #3B3A48 in Figma ([website color palette](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=72%3A9374&t=EP7PTQGcVYldMTFG-1)) and the website. Please use #3B3A48 for the type if possible - thanks!
Here's a screenshot of the Website color palette, for reference:
![image](https://user-images.githubusercontent.com/99768807/206286517-936901f0-82a9-4855-b3bd-28592899fca2.png)

**Comment by jon-grant-state-ca-gov** [comment]
@sharon-rabang thanks for this screenshot! I will check with @kkoryaka to make sure the gray-900 value is correct.

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov Thanks! Here's the only change to make:
Zebra example, Rows 1 and 3: Change the table content fonts' color from #212529 to Gray-900, #3B3A48

**Comment by jon-grant-state-ca-gov** [comment]
@sharon-rabang This should be the correct color now :)

**Comment by yesenia-gtz** [comment]
@sharon-rabang I reviewed this one, color is correct. closing :)
