### ISSUE TITLE
Site navigation: Visual design

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template-Website#932]
In the “Visual design” drop down: Use Public Sans, Bold to indicate an active page (Like the [Design System](https://designsystem.webstandards.ca.gov/))
![image](https://user-images.githubusercontent.com/99768807/206815997-b3db6367-0dba-48dd-b28a-0be4866884ad.png)
![image](https://user-images.githubusercontent.com/99768807/206816819-0f7838d6-e08d-4fcf-9b47-17111f3795e9.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this feature is now added.

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
