### ISSUE TITLE
Search bug

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template-Website#937]
When search is not included in the page JavaScript throwing the error. Make sure javaScript have escape clause when search is not included.
![Screen Shot 2022-12-10 at 8 32 00 PM](https://user-images.githubusercontent.com/31669748/206886607-8562938d-b15b-4d2b-8745-a4f59abaa7fa.png)

**Comment by kkoryaka** [comment]
@zakiya @Danny-Guzman  I saw this search console bug the other day in the DOF site (it shows up when search is not activated). This fix will go live with production release.

**Comment by Danny-Guzman** [comment]
@kkoryaka  keep in mind that DOF is using an old version of CAWeb/Divi, releasing a fix to the template will not fix it for DOF automatically

**Comment by zakiya** [comment]
Thanks for the head's up! 

FYI - The version of the site that's live now is using a different stack than it was a few days ago. Search is enabled and there are error messages on the console at https://dof.ca.gov/budget/. 

![CleanShot 2022-12-14 at 09 40 45](https://user-images.githubusercontent.com/915352/207667994-4cb9063b-40f2-43ae-9e5c-5f9d71ea7020.png)
