### ISSUE TITLE
Homepage UI fixes

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#951]
**Banner image:**
- [ ] The image size of the bear and shapes in the banner is too large, throwing off the spacing. 
![Screen Shot 2022-12-13 at 10 17 17 AM](https://user-images.githubusercontent.com/98193284/207413304-75b457d3-5a2a-4912-a380-114daacc0f5f.png)
---------------

**“Partner with us” section**
- [ ] The hover state should include a color change to #EEF8FB upon hover.
- [ ] When switching to mobile view, the shape graphics should appear above the heading, but is showing up under the heading section
---------------

**Graphics**
- [ ] The Bear image in the banner is also not scaling properly when moving to smaller screens still. Sharon provided an example in issue [#307](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/307)
---------------

**Who's using the design system**
- [ ] The arrows before the links appear off center.
Figma
![image](https://user-images.githubusercontent.com/98193284/207412220-cddbebe2-cdad-46e2-883b-bbd8c4eeec8d.png)
Site
![image (1)](https://user-images.githubusercontent.com/98193284/207412228-7d6df787-c79d-4eba-8503-47a93e6fd005.png)

- [ ] The headings in Figma are Bold, but do not appear bold on the site.  
- [ ] The images for both sites are using a stroke around them instead of a drop shadow 
Figma
![image (2)](https://user-images.githubusercontent.com/98193284/207412546-3fb35b35-392c-4fb1-b999-9f2f3ea3c254.png)
Site
![image (3)](https://user-images.githubusercontent.com/98193284/207412573-b09bc65f-f161-41c6-9062-fb8c770a0498.png)

- [ ] Text correction: Add "system" to "Who's using the new design". Should say "Who's using the new design system" , (Figma has been updated to include this edit)
![image](https://user-images.githubusercontent.com/98193284/207411385-0b77f3a9-de25-44f4-963c-287b9b3bc39a.png)

**Comment by timothyshambra** [comment]
1. Header image now scales based on width of the column.
2a. The link hover color is updated to #EEF8FB
2b. Graphic now transitions to the top. Should it also span 100% of the width? Or stay the same width and off to the side?
3. Bear image scales based on column width.
4. Arrows appear to be centered from large to small screens. What browser/OS results in off-centered arrows?
5. Headings are now back to being bold
6. Spoke with Konstantin, and he agreed that a gray stroke fits more with the design style than a shadow.
7. Added system to the heading

**Comment by yesenia-gtz** [comment]
@hamiltonryan this is ready for your review

**Comment by hamiltonryan** [comment]
The image and header look great now. The gray stroke is good, with the minor fix to the sizing. 

I think the only thing left was the arrow thing. It was looking slightly off to us on edge. 
Here's what I'm seeing, on my end at least:
![image](https://user-images.githubusercontent.com/101579462/208165740-a048bbdf-85c3-4e1a-86b1-689bcdfecc63.png)

**Comment by yesenia-gtz** [comment]
@timothyshambra  see review comments above.

**Comment by hamiltonryan** [comment]
@yesenia-gtz oops, forgot the tag. Thank you for tagging that for me :)

**Comment by yesenia-gtz** [comment]
@timothyshambra  checking in, is this ready for review? thanks.

**Comment by timothyshambra** [comment]
> @timothyshambra checking in, is this ready for review? thanks.

Yes. Pushed to staging.

- Verified the arrow is now centered in Edge

**Comment by yesenia-gtz** [comment]
Thank you! closing :)

**Comment by hamiltonryan** [comment]
Looks great on my end. Thanks Tim!
