### ISSUE TITLE
Conditions of use - content update

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#953]
[Conditions of use page](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/conditions-of-use.html) 

There is no google doc. This page needs minor massaging to fit the general style of the site (like no all caps in titles, using bullets instead of carets for bullets, etc)

**Comment by extinah** [comment]
Please apply standard/default styles to this page. Examples:

- [ ] Change triangular bullets to regular bullets
![image](https://user-images.githubusercontent.com/33840424/208781423-ad944737-c101-404d-a5c8-c3d738b0436f.png)

- [ ] update heading styles
![image](https://user-images.githubusercontent.com/33840424/208781458-bc921b3f-eea0-4054-80da-17f45198bab0.png)

**Comment by kkoryaka** [comment]
@extinah this in now updated

**Comment by extinah** [comment]
Looks good. Approved. Thanks @kkoryaka
