### ISSUE TITLE
Privacy policy - Content update

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#954]
[Privacy policy page
](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/privacy-policy.html)

This content did not get reviewed or updated. Needs to at least update the effective date (as a heading... change to regular text) and go a quick style pass. (carets as bullets to actual bullets)

**Comment by extinah** [comment]
Please apply standard/default styles to this page. 

- [ ] change this to normal text, bold

![image](https://user-images.githubusercontent.com/33840424/208781136-b0bb41cf-71f5-42c2-bc65-84698fabe010.png)

- [ ] changes these to normal bullets

![image](https://user-images.githubusercontent.com/33840424/208781213-5fab960a-c8ad-4414-a23b-c1d0a230986a.png)

**Comment by kkoryaka** [comment]
@extinah this is now updated

**Comment by extinah** [comment]
This looks good. Approved. Thanks.
