### ISSUE TITLE
Template Updates - content missing

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#957]
[Template updates page](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/template-updates.html)

- [x] Needs the production release updates (6.1 or 6.0.9). Here’s the github change log

https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/blob/beta-dev/changelog.md

**Comment by jon-grant-state-ca-gov** [comment]
Updates [here](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/template-updates.html)

**Comment by yesenia-gtz** [comment]
@extinah ready for your review.

**Comment by extinah** [comment]
@jon-grant-state-ca-gov  I see 6.0.9. Great. Before go-live, will the changes we've made be included in a 6.1 update? Or is this it? Either way is fine, just wanted to create another backlog issue, if needed. (or put this one in backlog)

**Comment by jon-grant-state-ca-gov** [comment]
@extinah As of now, I have not seen a list of changes for 6.1, but I can update quickly whenever that list is created.

**Comment by extinah** [comment]
The page looks great. Exciting updates. Thanks - approved.
@jon-grant-state-ca-gov  @yesenia-gtz
