### ISSUE TITLE
Potential global issue: "Aria-labelledby" has incorrect (ID) reference

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#959]
The WAI-ARIA 'aria-labelledby' attribute **has a reference to an ID that does not exist or an ID that is not unique**.

Potential global issue

**Pages affected:**
- [Structural elements / Utility header](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/utility-header.html)
- [Structural elements / Settings](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/settings-bar.html)
- [Structural elements / Site header](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/site-header.html)
- [Structural elements / Footer](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/footer.html)
- [Visual design / Color](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/color.html)
![image (2)](https://user-images.githubusercontent.com/98193284/207428308-b6bb58d3-1686-4a57-800e-e29ae4bd4b97.png)

**Correction to be made:**

- [ ] Make sure the ID referred by 'aria-labelledby' exists on the page and that the referred ID is only used on one element on the same page.

**Comment by yesenia-gtz** [comment]
@pglomboy this is ready for your review

**Comment by pglomboy** [comment]
Good to go, errors fixed.
