### ISSUE TITLE
Structural elements / Settings: URL edit

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#960]
[Structural elements / Settings](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/settings-bar.html)

- [ ] Fix URL: The URL has “settings-bar”, instead of “settings” for consistency with the page’s title.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated. https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/settings.html

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks! The URL is now updated, but the browser tab still has "Settings bar" by the favicon. Is this something we can fix, too?

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thannks!
