### ISSUE TITLE
Structural elements / Search - A11y and link fix

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#961]
[Structural elements / Search](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/search.html)

**A11y:**
A local link (anchor link) occurs but the destination does not exist.

- [x] When using local links they must refer to an existing element on the page.
------------------

- [x] Fix link: Under “Inactive search”, add link to [icon menu](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/site-navigation.html#Icon-menu) in second sentence.

**Comment by kkoryaka** [comment]
@yesenia-gtz this is now fixed.

**Comment by yesenia-gtz** [comment]
Thank you @kkoryaka, closing out

**Comment by yesenia-gtz** [comment]
@pglomboy this is ready for your review

**Comment by pglomboy** [comment]
a11y issues resolved. good to go. @kkoryaka
