### ISSUE TITLE
Structural elements / Footer - A11y and content corrections

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#962]
[Structural elements / Footer](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/footer.html)

**A11y:**
A local link (anchor link) occurs but the destination does not exist.

- [x] When using local links they must refer to an existing element on the page.
------------------

**Content**

- [x] Fix periods after bullets: Most of the bullets on this page end with a period in the Google doc and Figma. 

- [x] Add periods at the end of these bullets:

> The footer always includes:
> * The copyright notice.
> 
> The footer can also include:
> * An optional logo on the left that links back to the homepage for the website.
> * Customizable links.
> 
> Each time a new component version is published:
> * Test with the [axe accessibility tool](https://www.deque.com/axe/).
> * Review with the [VoiceOver](https://www.apple.com/voiceover/info/guide/_1121.html) or [NVDA](https://www.nvaccess.org/download/) screen reader.
> * Ensure all actionable elements are accessible by keyboard command and tab in a logical order. 
> * Check the component layout on a variety of screen sizes.

**Comment by yesenia-gtz** [comment]
Assigning @pglomboy for a11y review when ready and @sharon-rabang  for design/content review

**Comment by kkoryaka** [comment]
@sharon-rabang please review. After you are done (no more content edits needed) please assign it to Pia

**Comment by pglomboy** [comment]
a11y issues resolved. good to go. @kkoryaka

**Comment by yesenia-gtz** [comment]
@sharon-rabang please close out once design review is complete

**Comment by sharon-rabang** [comment]
@kkoryaka Content changes look good to go, based on the 12/14/22 decision to remove periods from all the bullets under the Accessibility section for now. UX team can create standard to follow after production.
