### ISSUE TITLE
Structural elements / Site navigation - UI updates

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#963]
[Structural elements / Site navigation](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure/site-navigation.html)

- [x] Dropdown menu: Remove outer gray outline from ‘around’ the image, for consistency with all other examples in Figma:
![image](https://user-images.githubusercontent.com/98193284/207432085-59db9f5b-797d-4443-b3cb-795e9a182d17.png)

- [x] Megamenu: Remove outer gray outline from ‘around’ the image, for consistency with all other examples in Figma:
![image (1)](https://user-images.githubusercontent.com/98193284/207432144-57e8ff4c-92ad-46ee-ab7c-846b7c9103de.png)

- [ ] Fix CAGov: Under Icon menu in sentence, change “CAGov”  to “Ca.gov” for consistency across the site.

**Comment by kkoryaka** [comment]
@sharon-rabang  this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Thanks for the improved updates! Looks good to go.
