### ISSUE TITLE
Visual design / Icons page - Browser inconsistencies

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#964]
[Visual design / Icons](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/icons.html)

**In Edge the navigation doesn’t bold the selected item**. In Chrome and Firefox the navigation doesn’t bold the selected item but slightly darkens font color when cursor hovers over. 

The “On this page” menu is smaller font than what’s in Figma on all browsers.

cc @Angsv

**Comment by extinah** [comment]
Can not replicate issue. May have been addressed before production release. Tim resolved the viewer issue.
