### ISSUE TITLE
Visual design / Color - UI fixes

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#966]
[Visual design / Color](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/color.html)

 **UI**
- [ ] We should add content to the individual color pages to let the user know the page is displaying the color theme selected.
- [ ] Stroke on cards is currently #aaa, can we make that our gray200 (# D4D4D7) color for consistency?

**Browser review:**

- [ ]  In Edge the navigation doesn’t bold the selected item. In Chrome and Firefox the navigation doesn’t bold the selected item but slightly darkens font color when cursor hovers over.

**Comment by Greg-Watanabe** [comment]
"We should add content to the individual color pages to..." 
Has this content been written?

**Comment by Greg-Watanabe** [comment]
The other two issues are complete.
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/color.html
