### ISSUE TITLE
Visual design / Typography - adjust table spacing

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#967]
[Visual design / Typography](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/visual-design/typography.html)

- [x] Spacing in the table is a bit cramped compared to design.

Figma
![image](https://user-images.githubusercontent.com/98193284/207439796-69d263ff-c26c-46d7-81eb-70e9d59fbeee.png)

Site
![image (1)](https://user-images.githubusercontent.com/98193284/207439874-00bd915d-d742-41be-b38a-7f04bf989049.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
