### ISSUE TITLE
Components - missing items

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#968]
[Components](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components.html)

- [ ] “On this page” menu is smaller font than what’s in Figma. 

- [ ] Page Navigation and Pagination cards and side navigation links are missing from the design. 

@sharon-rabang  @extinah @hamiltonryan Not sure if those pages are available yet.

**Comment by extinah** [comment]
@yesenia-gtz if the first item is from Ashley, she didn't realize the font is smaller. we can mark that as done. Also, we may want to assign the component cards to Ryan or Sharon (i'm making the assumption that Konstantin will be busy with QA items - he made most of those I think).

**Comment by kkoryaka** [comment]
@extinah do we have pagination component page in figma and word doc?

**Comment by extinah** [comment]
@kkoryaka I just moved this component page to UX in progress. We plan to have it done next, so creating the card would be good (and we can add it in if we choose to include it, or wait until post production).

**Comment by kkoryaka** [comment]
@extinah will get back to pagination component in the separate issues. @yesenia-gtz this one is ready to close out.
