### ISSUE TITLE
Components / Alert - content and links

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#970]
[Components / Alert](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/alert.html)

**Content**
- [x] Missing the last bullet from figma(and now google doc).
![Screen Shot 2022-12-13 at 12 58 16 PM](https://user-images.githubusercontent.com/98193284/207442066-9bb49ecc-3da3-4131-87c6-0af1aca37c51.png)

- [x] Utility Header link goes to a 404 page.
- [x] The “On this page” menu font is smaller than how it appears in Figma.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
