### ISSUE TITLE
Components / Modal - Break out copy in paragraphs

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#976]
[Components / Modal](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/modal.html)

Google doc shows the highlighted content in a tab titled “implementation notes” not a new page section titled “how it works.”

If we keep, copy should be broken into more paragraphs.

![Screen Shot 2022-12-13 at 1 23 38 PM](https://user-images.githubusercontent.com/98193284/207446435-a63e6670-55d1-477d-a5e0-0fc7962f759a.png)

**Comment by extinah** [comment]
@yesenia-gtz  this doesn't seem ready for review but still needs to be developed.

**Comment by kkoryaka** [comment]
@yesenia-gtz please review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/modal.html

**Comment by extinah** [comment]
@kkoryaka 

Please use the content in the figma design/google doc
![image](https://user-images.githubusercontent.com/33840424/208491685-86f16498-8409-4428-9a0e-4fddd92f50f6.png)

https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1693%3A15697&t=ACSv6iAaQNneWyCL-1

https://docs.google.com/document/d/14z_UcGPcS6JNjYgcYHNaKDnoJEZF-UawClz-F76qPIM/edit

**Comment by kkoryaka** [comment]
@extinah this is now updated

**Comment by extinah** [comment]
Approved. Thanks.
