### ISSUE TITLE
Global issue: examples scroll user back to the top of the page.

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#978]
Review linked items in “example”  section. Under Accordion list example, subpages scroll user back to the top of the page. need to uncouple the “back to top” function from example. Please see recording to preview issue. 

![Screen Shot 2022-12-13 at 1 30 32 PM](https://user-images.githubusercontent.com/98193284/207447995-30459995-930e-4771-b402-5fe769ada461.png)

**[Recording here]**(https://www.loom.com/share/e155d51fa60c4e16babe8539fc86ab9a)

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by yesenia-gtz** [comment]
Tested issue on a couple pages, looks good.
