### ISSUE TITLE
Components / Side navigation - text edits

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#979]
[Components / Side navigation](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/side-navigation.html)

**Other names has the wrong example.** 
- [x] Update to: " Other names: Left navigation, side menu

**Content fix to match google doc. This is the correct content for the scroll bar section (highlighted the part that needs fixing)**
- [x] This built-in feature only activates when side navigation is longer than the current viewport area.

**Under usage** 
- [x] delete the extra “a”. "Use a single level when navigation is simple and direct."

**Under multi-level behavior**
![Screen Shot 2022-12-13 at 1 37 35 PM](https://user-images.githubusercontent.com/98193284/207449135-cadecacd-294c-45ad-8140-1c15940279c3.png)

- [x] #3. delete question mark in the example for Surprise**?**

**Comment by yesenia-gtz** [comment]
@extinah  ready for your review

**Comment by yesenia-gtz** [comment]
fyi @extinah  I did a review and didn't see any issues, closing this out.

**Comment by extinah** [comment]
Looks great. Thanks for reviewing, @yesenia-gtz .
