### ISSUE TITLE
Components / Side navigation - A11y corrections

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#980]
Visible label and accessible name do not match

The accessible name of any interactive element should contain its visible text label.

Include the label text in the accessible name of the element.

Make aria label and text identical.

Current: <a id="tab-notes3" href="#pane-notes3" class="nav-link active" data-bs-toggle="tab" role="tab" aria-label="Accordion list source code" aria-selected="true">Implementation notes</a>

**Recommendation:**
 <a id="tab-notes3" href="#pane-notes3" class="nav-link active" data-bs-toggle="tab" role="tab" aria-label="Implementation notes" aria-selected="true">Implementation notes</a>

**Comment by extinah** [comment]
@pglomboy please provide screenshots and more context and how to fix this. Thanks!

**Comment by pglomboy** [comment]
@extinah I think this is the one that we worked on a couple weeks ago? The text and the anchor links?

**Comment by extinah** [comment]
@pglomboy is this no longer an issue? If not, you can close the issue (or I can) :)

**Comment by pglomboy** [comment]
yep I'll do it
