### ISSUE TITLE
Components / Social media icons - Content review

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#981]
[Components / Social media icons](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/social-media-icons.html)

Per @extinah 
From what I recall, this content is not technically correct. Need to triage how to move forward (make some updates to content this week or omit it from the production release).

**Comment by extinah** [comment]
@kkoryaka  I'll set up a meeting to discuss this component.

**Comment by extinah** [comment]
Meeting set for tomorrow at 9 am (12/14)

**Comment by extinah** [comment]
We met and discussed. Here's the updated content.
@kkoryaka  @ashleydraper  please review before Koji and Art review. Thanks.
https://docs.google.com/document/d/1WQZ71PA9ZIit5Y48mLNxdgHChrq3qdDN6ZJM57T1VxY/edit#

**Comment by ashleydraper** [comment]
@extinah Done with my review

**Comment by yesenia-gtz** [comment]
@extinah  @ashleydraper This looks good to me, OK to proceed on my end.

**Comment by extinah** [comment]
@kkoryaka @carterm  this is ready to update (or assign to a dev).
Changes are highlighted in yellow: https://docs.google.com/document/d/1WQZ71PA9ZIit5Y48mLNxdgHChrq3qdDN6ZJM57T1VxY/edit#

**Comment by kkoryaka** [comment]
@sharon-rabang  please review: https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/social-media-icons.html

**Comment by extinah** [comment]
@kkoryaka  this looks good. approved. ready to close.

**Comment by sharon-rabang** [comment]
@extinah Thanks for the review and approval! Figma has also been updated to align with the google doc.
