### ISSUE TITLE
Components / Tabs - link fix

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#982]
- [x] Fix link: Under “Usage” in the last bullet, add a link to “[side navigation](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/side-navigation.html)”.

**Comment by yesenia-gtz** [comment]
@sharon-rabang this is ready for you to review

**Comment by sharon-rabang** [comment]
@jon-grant-state-ca-gov Looks good to go, thanks!
