### ISSUE TITLE
CSS Style Shortcuts - update link address

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#983]
[CSS Style Shortcuts](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/get-started/css-classes-shortcuts/)

**[Spacing page:]**(https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/get-started/css-classes-shortcuts/spacing.html#Using-the-spacing-class)

![Screen Shot 2022-12-13 at 1 51 00 PM](https://user-images.githubusercontent.com/98193284/207451480-66f44740-8bd1-4955-8fef-513c60f30acf.png)

[Utility CSS classes](https://beta.template.webstandards.ca.gov/get-started/css-classes-shortcuts/utility-css-classes.html) is linking to beta, please  link to Production page when available

**Comment by jon-grant-state-ca-gov** [comment]
@yesenia-gtz Did you mean to link to the Utility CSS classes page on production?
[Utility CSS classes: Prod](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/get-started/css-classes-shortcuts/utility-css-classes.html)

I might be misunderstanding, but I thought you wanted that link you included to be the target destination, but it just links back to the same page.

**Comment by yesenia-gtz** [comment]
@jon-grant-state-ca-gov thatvis correct, I meant link to the Utility CSS classes page on production.

Thanks you for clarifying!

**Comment by jon-grant-state-ca-gov** [comment]
Thanks!
I didn't want to 'assume' :)

**Comment by yesenia-gtz** [comment]
Thanks @jon-grant-state-ca-gov, looks good, closing this out!
