### ISSUE TITLE
Patterns - Banner card missing

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#984]
[Patterns](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns.html)

- [x] Fix cards: Add the missing [Banner card](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A6623&t=0MCEHK963fVBq1qt-1) image and content from Figma.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns.html

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
