### ISSUE TITLE
Patterns / Card grid - design fixes

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#986]
[Patterns / Card grid](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/card-grid.html)

**Design Fixes**

per @sharon-rabang 
- [x] Fix examples: Make cards have fixed height to display evenly across each triptych like in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=45%3A7548&t=D73jc5PQPitRtYfs-1) and mobile view:
 
![Screen Shot 2022-12-13 at 1 58 47 PM](https://user-images.githubusercontent.com/98193284/207452931-7b4263e9-18f7-4bcd-acff-a21f8652e78e.png)

![Screen Shot 2022-12-13 at 1 58 59 PM](https://user-images.githubusercontent.com/98193284/207452974-e8500fe6-05f1-47d6-9cea-a9cf7bab174e.png)

- [x] Imagery, mobile view: Add more spacing between the cards like in the Basic and News gird examples
![image](https://user-images.githubusercontent.com/98193284/207453058-44439467-a8a1-4c4a-a312-d302d1589e47.png)

Per @artuoma

- [x] In the Basic Title example card - the headings link should link to the headings hierarchy section of the Typography page

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go, thanks!
