### ISSUE TITLE
Patterns / Link grid - text edits

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#987]
[Patterns / Link grid](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/link-grid.html)

Per @sharon-rabang 

- [x] Fix periods after bullets: Add periods at the end of these bullets like in the Google doc and Figma. 

>  Each time a new component version is published:
> * Test with the [axe accessibility tool](https://www.deque.com/axe/).
> * Review with the [VoiceOver](https://www.apple.com/voiceover/info/guide/_1121.html) or [NVDA](https://www.nvaccess.org/download/) screen reader.
> * Ensure all actionable elements are accessible by keyboard command and tab in a logical order. 
> * Check the component layout on a variety of screen sizes.

**Comment by jon-grant-state-ca-gov** [comment]
In the comments of [Pull request #1037](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1037), there were notes from @kkoryaka and @ashleydraper about not adding in the periods at this time, and adding a colon to color.html

**Comment by extinah** [comment]
Yep - these really should be documented under global fixes. This is a learning opportunity. Thanks, Jon.

**Comment by extinah** [comment]
@kkoryaka  can this be closed now? 
cc: @yesenia-gtz
