### ISSUE TITLE
Sitemap - link edits

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#989]
per @extinah 

- [x] We should run a report and validate no other content is missing.
- [x] Add side navigation to the list.
- [x] Broken link (need to remove the “s”): https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/buttons.html

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated

**Comment by extinah** [comment]
@kkoryaka Can you also run a report for the pages on the site so we can validate that other content isn't missing?

Also, if it's not clear who the reviewer is, you can assign it to me and I can assign to the team. This one, I submitted this feedback (as noted in the first comment)

**Comment by kkoryaka** [comment]
@extinah I went through all the content inside of the repo and I deleted all the orphan pages. So, all pages on website and repo should be active and linked.

**Comment by extinah** [comment]
@kkoryaka reviewed again. All looks good. Thanks for deleting the orphan pages. Approved.
