### ISSUE TITLE
Download and setup - Design and Content edits

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#990]
[Download and setup](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/download-and-setup.html)

**Design and Layout**
- [x] The alignment of Step list is slightly off on this page. It should be aligned with the text. 
![Screen Shot 2022-12-13 at 2 13 40 PM](https://user-images.githubusercontent.com/98193284/207455769-53a3585c-dda2-4f13-9e7e-287086b1121a.png)

- [x] These have red in figma and the google doc, but not on the site. Not sure which is correct though:
![Screen Shot 2022-12-13 at 2 14 06 PM](https://user-images.githubusercontent.com/98193284/207455849-8b9d925d-dea1-4799-b2bb-28d143dc0c3c.png)

------------------

**Content**

- [x] On this page - the first H2 and the first one this page bullet don’t match. Correct the on this page text.
![Screen Shot 2022-12-13 at 2 14 46 PM](https://user-images.githubusercontent.com/98193284/207455958-9bf416dd-8085-4639-a6e0-d4f9c54f0de7.png)
Look at this google doc - edits are highlighted in yellow. https://docs.google.com/document/d/1A--CplY-8qepW4dG_jG0Bdg-eiDgqZ5RQgt7lD8jVPo/edit#
- [x] Update the link text to match the new heading. New heading is: Common web template resources

> 4. Download or clone the State Web Template from GitHub
> You can clone it from our [Template GitHub Repository](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/).
> You can also download or access the different frameworks. Review [Common V6 State Web Template file links](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/download-and-setup.html#Commonlinks). This is also a good time to have your security office perform a scan of the files.

(updated the google doc and figma)
**per @extinah "NOTE don’t fix this yet. Looking to see if this is a good change or not. It may not be accurate."**

- [x] Delete unnecessary sentence. content was moved to the download and setup page, so it no longer makes sense.

> Folder structure and files
> Discover what’s in the V6 State Template package. Review [Download and setup](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/download-and-setup.html) for more details.

- [x] Change “clear” to “clean”
![Screen Shot 2022-12-13 at 2 17 05 PM](https://user-images.githubusercontent.com/98193284/207456336-bd1b7c1f-a5e9-42fe-a099-ebbe4915626b.png)

**Comment by extinah** [comment]
Discussed with Tim. Changed the heading to Common web template resources. Updated in figma and google doc.
https://docs.google.com/document/d/1A--CplY-8qepW4dG_jG0Bdg-eiDgqZ5RQgt7lD8jVPo/edit#

Edits are highlighted.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated.

**Comment by sharon-rabang** [comment]
@kkoryaka All the content edits look good, thanks! Here are the only 2 questions about design and layout:

- Is it possible to left-align the yellow step list graphic with the text?
![image](https://user-images.githubusercontent.com/99768807/208156468-28be4f22-3ba1-4f6d-8e26-e9326a9a70a9.png)

- "The words 'html' and 'njk' have red text in Figma and the Google doc, but not on the site. Is the site correct and consistent for not having them in red in this instance? If so, we'll update Figma and the Google doc.
![image](https://user-images.githubusercontent.com/99768807/208156981-a884d9f6-7c6a-4710-b747-32fc7284cabe.png)

**Comment by kkoryaka** [comment]
@sharon-rabang I am trying my best to align it... I though i did but I guess i need couple more px. 
And. I will make those red.

**Comment by kkoryaka** [comment]
@sharon-rabang this is now updated. I also added critical information into css section that was missing. 
![Screen Shot 2022-12-16 at 12 12 16 PM](https://user-images.githubusercontent.com/31669748/208183489-002beb72-ad8d-4728-b729-1710789ba72a.png)

**Comment by sharon-rabang** [comment]
@kkoryaka Looks good to go! Thanks for making the content updates in the Google doc, too. Figma has been updated to reflect the Custom CSS content changes in both the Google doc and dev.
