### ISSUE TITLE
Example tab font color is incorrect

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#991]
**Pages affected:**
Component and patterns

**Correction:**
Current color (wrong): black #000

Correct color: gray 900 #3b3a48

![Screen Shot 2022-12-13 at 2 21 38 PM](https://user-images.githubusercontent.com/98193284/207457351-abcfe355-c7a2-4285-b923-82dc34dc2e3d.png)

**Comment by kkoryaka** [comment]
@sharon-rabang this one is now updated

**Comment by yesenia-gtz** [comment]
looks good
