### ISSUE TITLE
Main website logo colors

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#992]
**Affected areas:**
Header

**For review**
Should we use the dark blue color of the website to better integrate the logo? 

![Screen Shot 2022-12-13 at 2 23 41 PM](https://user-images.githubusercontent.com/98193284/207457698-a0432079-8683-4f8c-b2b3-f07c9755407b.png)

cc @artuoma @extinah @kkoryaka

**Comment by extinah** [comment]
@sharon-rabang When you have time, please check this out. Feel free to call a quick meeting to talk through your thoughts. Thanks.

**Comment by sharon-rabang** [comment]
@extinah Thanks for the good meeting. Let's keep this issue open for exploration. 
One approach to consider is for users to apply their color theme's Standout color to the website title.
